import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { closeDatabase, openDatabase, sqlite } from '../infrastructure/database/connection';
import { runMigrations } from '../infrastructure/database/migrate';
import { OrganisationRepository } from '../infrastructure/database/repositories/OrganisationRepository';
import { ContactRepository } from '../infrastructure/database/repositories/ContactRepository';
import { EngagementRepository } from '../infrastructure/database/repositories/EngagementRepository';
import { ContactService, EngagementService, OrganisationService } from '../application/services/CrmDomainServices';
import { OrganisationCreateSchema, ContactCreateSchema, EngagementCreateSchema, OrganisationUpdateSchema, ContactUpdateSchema, EngagementUpdateSchema } from 'shared';

let tempDir:string; const migrationsFolder=path.resolve(__dirname,'../../drizzle');
beforeEach(()=>{tempDir=fs.mkdtempSync(path.join(os.tmpdir(),'whitelabel-crm-test-')); const db = openDatabase(path.join(tempDir,'test.sqlite')); runMigrations(db,migrationsFolder);});
afterEach(()=>{closeDatabase(); fs.rmSync(tempDir,{recursive:true,force:true});});
const services=()=>{const o=new OrganisationRepository(), c=new ContactRepository(), e=new EngagementRepository(); return {org:new OrganisationService(o), contact:new ContactService(o,c), engagement:new EngagementService(o,c,e)} };

describe('shared crm schemas',()=>{
 it('normalizes organisation fields and rejects invalid input',()=>{const parsed=OrganisationCreateSchema.parse({name:' Acme ',website:'',country:' us ',legalName:' '}); expect(parsed).toMatchObject({name:'Acme',website:null,country:'US',legalName:null,status:'prospect'}); expect(()=>OrganisationCreateSchema.parse({name:' '})).toThrow(); expect(()=>OrganisationCreateSchema.parse({name:'A',website:'notaurl'})).toThrow(); expect(()=>OrganisationUpdateSchema.parse({id:'x'})).toThrow(); expect(()=>OrganisationUpdateSchema.parse({})).toThrow();});
 it('validates contact identity and engagement dates',()=>{expect(ContactCreateSchema.parse({organisationId:'00000000-0000-4000-8000-000000000001',email:' TEST@EXAMPLE.COM '})).toMatchObject({email:'test@example.com',status:'active',isPrimary:false}); expect(()=>ContactCreateSchema.parse({organisationId:'00000000-0000-4000-8000-000000000001',firstName:' '})).toThrow(); expect(()=>ContactUpdateSchema.parse({organisationId:'00000000-0000-4000-8000-000000000001'})).toThrow(); expect(()=>EngagementCreateSchema.parse({organisationId:'00000000-0000-4000-8000-000000000001',name:'E',type:'diagnostic',startDate:'2026-02-31'})).toThrow(); expect(()=>EngagementCreateSchema.parse({organisationId:'00000000-0000-4000-8000-000000000001',name:'E',type:'diagnostic',startDate:'2026-03-02',endDate:'2026-03-01'})).toThrow(); expect(()=>EngagementUpdateSchema.parse({organisationId:'x'})).toThrow();});
});

describe('crm repositories/services',()=>{
 it('creates, lists, searches, archives and protects organisations',async()=>{const {org}=services(); const a=await org.create(OrganisationCreateSchema.parse({name:'Beta % Co',status:'active_client'})); await org.create(OrganisationCreateSchema.parse({name:'alpha'})); expect(a.id).toMatch(/[0-9a-f-]{36}/); expect(a.createdAt).toBeTruthy(); expect((await org.list({limit:50,offset:0})).map(o=>o.name)).toEqual(['alpha','Beta % Co']); expect(await org.list({search:'%',limit:50,offset:0})).toHaveLength(1); await org.archive(a.id); expect(await org.list({limit:50,offset:0})).toHaveLength(1); expect(await org.list({includeArchived:true,limit:50,offset:0})).toHaveLength(2); await expect(org.update(a.id,{name:'new'})).rejects.toThrow(/Archived/);});
 it('enforces contact creation, primary contact and archive rules',async()=>{const {org,contact}=services(); const o=await org.create({name:'Org',status:'prospect'} as any); const c1=await contact.create({organisationId:o.id,firstName:'A',isPrimary:true,status:'active'} as any); const c2=await contact.create({organisationId:o.id,lastName:'B',isPrimary:true,status:'active'} as any); expect((await contact.get(c1.id)).isPrimary).toBe(false); expect((await contact.get(c2.id)).isPrimary).toBe(true); await contact.update(c2.id,{status:'inactive'}); expect((await contact.get(c2.id)).isPrimary).toBe(false); await expect(contact.update(c1.id,{firstName:null,lastName:null,email:null})).rejects.toThrow(/At least one/); await contact.archive(c1.id); expect(await contact.list({organisationId:o.id,includeArchived:true,limit:50,offset:0})).toHaveLength(2); await org.archive(o.id); await expect(contact.create({organisationId:o.id,email:'x@y.com'} as any)).rejects.toThrow(/Archived/);});
 it('enforces engagement contact eligibility, date merging and archival',async()=>{const {org,contact,engagement}=services(); const o1=await org.create({name:'Org1',status:'prospect'} as any); const o2=await org.create({name:'Org2',status:'prospect'} as any); const c=await contact.create({organisationId:o1.id,email:'a@b.com'} as any); const other=await contact.create({organisationId:o2.id,email:'c@d.com'} as any); const e=await engagement.create({organisationId:o1.id,name:'Discovery',type:'diagnostic',startDate:'2026-01-01',primaryContactId:c.id} as any); await expect(engagement.update(e.id,{primaryContactId:other.id})).rejects.toThrow(/belong/); await expect(engagement.update(e.id,{startDate:'2026-02-01',endDate:'2026-01-01'})).rejects.toThrow(/End date/); expect((await engagement.update(e.id,{primaryContactId:null,endDate:null})).primaryContactId).toBeNull(); await engagement.archive(e.id); await expect(engagement.update(e.id,{name:'No'})).rejects.toThrow(/Archived/);});
 it('has expected migration tables, indexes, foreign key enforcement and no cascade delete',()=>{for(const t of ['organisations','contacts','engagements']) expect(sqlite.prepare("select name from sqlite_master where type='table' and name=?").get(t)).toBeTruthy(); expect(sqlite.pragma('foreign_keys')[0].foreign_keys).toBe(1); expect(sqlite.pragma('foreign_key_check')).toEqual([]); expect(sqlite.pragma('integrity_check')[0].integrity_check).toBe('ok'); const fk=sqlite.pragma('foreign_key_list(contacts)') as any[]; expect(fk[0].on_delete.toLowerCase()).toBe('restrict'); expect(sqlite.prepare("select name from sqlite_master where type='index' and name='contact_email_idx'").get()).toBeTruthy(); expect(sqlite.prepare("select sql from sqlite_master where type='index' and name='contact_email_idx'").get().sql).not.toMatch(/unique/i);});
});
