import { randomUUID } from 'crypto';
import { sqlite } from '../connection';
import type { IContactRepository, ContactListOptions } from '../../../application/interfaces/IRepositories';
import type { Contact, ContactCreate, ContactUpdate } from 'shared';
const row=(r:any):Contact=>({id:r.id,organisationId:r.organisation_id,firstName:r.first_name,lastName:r.last_name,jobTitle:r.job_title,email:r.email,phone:r.phone,isPrimary:!!r.is_primary,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at});
const cols:any={firstName:'first_name',lastName:'last_name',jobTitle:'job_title',isPrimary:'is_primary'};
export class ContactRepository implements IContactRepository{
 async create(input:ContactCreate){const now=new Date().toISOString(),id=randomUUID(); sqlite.prepare(`insert into contacts (id,organisation_id,first_name,last_name,job_title,email,phone,is_primary,status,created_at,updated_at,archived_at) values (@id,@organisationId,@firstName,@lastName,@jobTitle,@email,@phone,@isPrimary,@status,@now,@now,null)`).run({id,now,...input,status:(input as any).status ?? 'active',firstName:input.firstName??null,lastName:input.lastName??null,jobTitle:input.jobTitle??null,email:input.email??null,phone:input.phone??null,isPrimary:input.isPrimary?1:0}); return (await this.getById(id,{includeArchived:true}))!}
 async createPrimary(input:ContactCreate){let id=''; sqlite.transaction(()=>{sqlite.prepare('update contacts set is_primary=0, updated_at=@now where organisation_id=@organisationId and archived_at is null and is_primary=1').run({organisationId:input.organisationId,now:new Date().toISOString()}); id=randomUUID(); const now=new Date().toISOString(); sqlite.prepare(`insert into contacts (id,organisation_id,first_name,last_name,job_title,email,phone,is_primary,status,created_at,updated_at,archived_at) values (@id,@organisationId,@firstName,@lastName,@jobTitle,@email,@phone,1,@status,@now,@now,null)`).run({id,now,...input,status:(input as any).status ?? 'active',firstName:input.firstName??null,lastName:input.lastName??null,jobTitle:input.jobTitle??null,email:input.email??null,phone:input.phone??null});})(); return (await this.getById(id,{includeArchived:true}))!}
 async getById(id:string,o?:{includeArchived?:boolean}){const r=sqlite.prepare(`select * from contacts where id=? ${o?.includeArchived?'':'and archived_at is null'}`).get(id);return r?row(r):null}
 async list(o:ContactListOptions){const w=['organisation_id=@organisationId']; if(!o.includeArchived)w.push('archived_at is null'); if(o.status)w.push('status=@status'); return sqlite.prepare(`select * from contacts where ${w.join(' and ')} order by is_primary desc, lower(coalesce(last_name,'')) asc, lower(coalesce(first_name,'')) asc, id asc limit @limit offset @offset`).all(o).map(row)}
 async update(id:string,patch:ContactUpdate){const now=new Date().toISOString(); const sets=Object.keys(patch).map(k=>`${cols[k]??k}=@${k}`); const info=sqlite.prepare(`update contacts set ${sets.join(',')}, updated_at=@now where id=@id and archived_at is null`).run({id,now,...patch,isPrimary:patch.isPrimary===undefined?undefined:(patch.isPrimary?1:0)}); return info.changes?this.getById(id,{includeArchived:true}):null}
 async updatePrimary(id:string,patch:ContactUpdate){sqlite.transaction(()=>{const cur=sqlite.prepare('select * from contacts where id=? and archived_at is null and status=\'active\'').get(id); if(!cur) throw new Error('CONTACT_PRIMARY_NOT_ELIGIBLE'); sqlite.prepare('update contacts set is_primary=0, updated_at=@now where organisation_id=@org and id<>@id and archived_at is null and is_primary=1').run({org:cur.organisation_id,id,now:new Date().toISOString()}); this.update(id,{...patch,isPrimary:true} as ContactUpdate);})(); return this.getById(id,{includeArchived:true})}
 async archive(id:string,archivedAt:string){const ex=await this.getById(id,{includeArchived:true}); if(!ex)return null; if(ex.archivedAt)return ex; sqlite.prepare('update contacts set archived_at=@archivedAt, updated_at=@archivedAt, is_primary=0 where id=@id').run({id,archivedAt}); return this.getById(id,{includeArchived:true})}
}
