import { randomUUID } from 'crypto';
import { sqlite } from '../connection';
import type { IOrganisationRepository, OrganisationListOptions } from '../../../application/interfaces/IRepositories';
import type { Organisation, OrganisationCreate, OrganisationUpdate } from 'shared';
const row = (r: any): Organisation => ({ id: r.id, name: r.name, legalName: r.legal_name, website: r.website, industry: r.industry, employeeBand: r.employee_band, annualRevenueBand: r.annual_revenue_band, country: r.country, status: r.status, source: r.source, createdAt: r.created_at, updatedAt: r.updated_at, archivedAt: r.archived_at });
const esc = (s: string) => s.replace(/[\\%_]/g, '\\$&');
export class OrganisationRepository implements IOrganisationRepository {
  async create(input: OrganisationCreate): Promise<Organisation> { const now = new Date().toISOString(), id = randomUUID(); sqlite.prepare(`insert into organisations (id,name,legal_name,website,industry,employee_band,annual_revenue_band,country,status,source,created_at,updated_at,archived_at) values (@id,@name,@legalName,@website,@industry,@employeeBand,@annualRevenueBand,@country,@status,@source,@now,@now,null)`).run({ id, now, ...input, status:(input as any).status ?? 'prospect', legalName: input.legalName ?? null, website: input.website ?? null, industry: input.industry ?? null, employeeBand: input.employeeBand ?? null, annualRevenueBand: input.annualRevenueBand ?? null, country: input.country ?? null, source: input.source ?? null }); return (await this.getById(id, { includeArchived: true }))!; }
  async getById(id: string, options?: { includeArchived?: boolean }): Promise<Organisation | null> { const r = sqlite.prepare(`select * from organisations where id=? ${options?.includeArchived ? '' : 'and archived_at is null'}`).get(id); return r ? row(r) : null; }
  async list(o: OrganisationListOptions): Promise<Organisation[]> { const where: string[]=[]; const p:any={limit:o.limit,offset:o.offset}; if(!o.includeArchived) where.push('archived_at is null'); if(o.status){where.push('status=@status');p.status=o.status} if(o.search){where.push("lower(name) like lower(@search) escape '\\'");p.search=`%${esc(o.search)}%`} const sql=`select * from organisations ${where.length?'where '+where.join(' and '):''} order by lower(name) asc, id asc limit @limit offset @offset`; return sqlite.prepare(sql).all(p).map(row); }
  async update(id: string, patch: OrganisationUpdate): Promise<Organisation | null> { const now = new Date().toISOString(); const sets = Object.keys(patch).map(k => `${({legalName:'legal_name',employeeBand:'employee_band',annualRevenueBand:'annual_revenue_band'} as any)[k] ?? k}=@${k}`); const info=sqlite.prepare(`update organisations set ${sets.join(',')}, updated_at=@now where id=@id and archived_at is null`).run({id,now,...patch}); return info.changes ? this.getById(id,{includeArchived:true}) : null; }
  async archive(id: string, archivedAt: string): Promise<Organisation | null> { const existing=await this.getById(id,{includeArchived:true}); if(!existing) return null; if(existing.archivedAt) return existing; sqlite.prepare('update organisations set archived_at=@archivedAt, updated_at=@archivedAt where id=@id').run({id,archivedAt}); return this.getById(id,{includeArchived:true}); }
}
