import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import { sqlite } from './connection';
import type { EmailAddress } from '../integrations/ConnectedAdapters';
import type { CalendarWriteInput } from '../integrations/OutboundAdapters';

const now=()=>new Date().toISOString();
function json<T>(value:unknown,fallback:T):T{if(typeof value!=='string')return fallback;try{return JSON.parse(value) as T;}catch{return fallback;}}

export interface DraftInput {
  accountId:string;threadId?:string|null;organisationId?:string|null;contactId?:string|null;engagementId?:string|null;
  mode?:'new'|'reply'|'reply_all'|'forward';inReplyToMessageId?:string|null;to:EmailAddress[];cc?:EmailAddress[];bcc?:EmailAddress[];
  subject:string;bodyText:string;bodyHtml?:string|null;documentIds?:string[];
}

export class CommunicationsHubRepository {
  constructor(private readonly connection:Database.Database=sqlite as Database.Database){}

  createDraft(input:DraftInput){const id=randomUUID();const timestamp=now();this.connection.transaction(()=>{
    this.connection.prepare(`INSERT INTO email_drafts(id,account_id,thread_id,organisation_id,contact_id,engagement_id,mode,in_reply_to_message_id,to_json,cc_json,bcc_json,subject,body_text,body_html,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?)`).run(id,input.accountId,input.threadId??null,input.organisationId??null,input.contactId??null,input.engagementId??null,input.mode??'new',input.inReplyToMessageId??null,JSON.stringify(input.to),JSON.stringify(input.cc??[]),JSON.stringify(input.bcc??[]),input.subject.trim(),input.bodyText,input.bodyHtml??null,timestamp,timestamp);
    for(const documentId of new Set(input.documentIds??[]))this.connection.prepare('INSERT INTO email_draft_documents(id,draft_id,document_id,created_at) VALUES(?,?,?,?)').run(randomUUID(),id,documentId,timestamp);
  })();return this.getDraft(id)!;}

  updateDraft(id:string,input:Partial<DraftInput>){const current=this.getDraft(id);if(!current)throw new Error('Draft not found');if(!['draft','failed'].includes(current.status))throw new Error('Only draft or failed email can be edited');const timestamp=now();this.connection.transaction(()=>{
    this.connection.prepare(`UPDATE email_drafts SET account_id=?,thread_id=?,organisation_id=?,contact_id=?,engagement_id=?,mode=?,in_reply_to_message_id=?,to_json=?,cc_json=?,bcc_json=?,subject=?,body_text=?,body_html=?,status='draft',last_error=NULL,updated_at=? WHERE id=?`).run(input.accountId??current.accountId,input.threadId===undefined?current.threadId:input.threadId,input.organisationId===undefined?current.organisationId:input.organisationId,input.contactId===undefined?current.contactId:input.contactId,input.engagementId===undefined?current.engagementId:input.engagementId,input.mode??current.mode,input.inReplyToMessageId===undefined?current.inReplyToMessageId:input.inReplyToMessageId,JSON.stringify(input.to??current.to),JSON.stringify(input.cc??current.cc),JSON.stringify(input.bcc??current.bcc),input.subject??current.subject,input.bodyText??current.bodyText,input.bodyHtml===undefined?current.bodyHtml:input.bodyHtml,timestamp,id);
    if(input.documentIds){this.connection.prepare('DELETE FROM email_draft_documents WHERE draft_id=?').run(id);for(const documentId of new Set(input.documentIds))this.connection.prepare('INSERT INTO email_draft_documents(id,draft_id,document_id,created_at) VALUES(?,?,?,?)').run(randomUUID(),id,documentId,timestamp);}
  })();return this.getDraft(id)!;}

  getDraft(id:string){const row=this.connection.prepare(`SELECT d.*,a.name AS account_name,a.username AS account_username,a.server_url,a.settings_json,a.credential_key FROM email_drafts d JOIN communication_accounts a ON a.id=d.account_id WHERE d.id=?`).get(id) as Record<string,unknown>|undefined;if(!row)return null;const documents=this.connection.prepare(`SELECT x.document_id,d.title,d.current_filename,d.mime_type,d.byte_size FROM email_draft_documents x JOIN documents d ON d.id=x.document_id WHERE x.draft_id=? ORDER BY d.title`).all(id) as Array<Record<string,unknown>>;return {id:row.id,accountId:row.account_id,accountName:row.account_name,accountUsername:row.account_username,serverUrl:row.server_url,settings:json(row.settings_json,{}),credentialKey:row.credential_key,threadId:row.thread_id,organisationId:row.organisation_id,contactId:row.contact_id,engagementId:row.engagement_id,mode:row.mode,inReplyToMessageId:row.in_reply_to_message_id,to:json<EmailAddress[]>(row.to_json,[]),cc:json<EmailAddress[]>(row.cc_json,[]),bcc:json<EmailAddress[]>(row.bcc_json,[]),subject:row.subject,bodyText:row.body_text,bodyHtml:row.body_html,status:row.status,lastError:row.last_error,sentMessageId:row.sent_message_id,createdAt:row.created_at,updatedAt:row.updated_at,sentAt:row.sent_at,discardedAt:row.discarded_at,documents:documents.map((item)=>({documentId:item.document_id,title:item.title,filename:item.current_filename,mimeType:item.mime_type,byteSize:item.byte_size}))};}
  listDrafts(input:{status?:string;organisationId?:string;limit?:number}={}){const rows=this.connection.prepare(`SELECT id FROM email_drafts WHERE (@status IS NULL OR status=@status) AND (@organisationId IS NULL OR organisation_id=@organisationId) ORDER BY updated_at DESC LIMIT @limit`).all({status:input.status??null,organisationId:input.organisationId??null,limit:input.limit??200}) as Array<{id:string}>;return rows.map((row)=>this.getDraft(row.id)!);}
  discardDraft(id:string){const timestamp=now();const result=this.connection.prepare(`UPDATE email_drafts SET status='discarded',discarded_at=?,updated_at=? WHERE id=? AND status IN ('draft','failed')`).run(timestamp,timestamp,id);if(!result.changes)throw new Error('Editable draft not found');return this.getDraft(id)!;}
  markDraftSending(id:string){const result=this.connection.prepare(`UPDATE email_drafts SET status='sending',last_error=NULL,updated_at=? WHERE id=? AND status IN ('draft','failed')`).run(now(),id);if(!result.changes)throw new Error('Draft is not available to send');}
  markDraftFailed(id:string,error:string){this.connection.prepare(`UPDATE email_drafts SET status='failed',last_error=?,updated_at=? WHERE id=?`).run(error,now(),id);return this.getDraft(id)!;}

  startSendAttempt(draftId:string,accountId:string){const id=randomUUID();const startedAt=now();this.connection.prepare(`INSERT INTO outbound_email_attempts(id,draft_id,account_id,explicit_confirmation,status,started_at) VALUES(?,?,?,1,'running',?)`).run(id,draftId,accountId,startedAt);return {id,startedAt};}
  finishSendAttempt(id:string,input:{status:'succeeded'|'failed';providerMessageKey?:string|null;rfcMessageId?:string|null;errorSummary?:string|null}){this.connection.prepare(`UPDATE outbound_email_attempts SET status=?,provider_message_key=?,rfc_message_id=?,error_summary=?,completed_at=? WHERE id=?`).run(input.status,input.providerMessageKey??null,input.rfcMessageId??null,input.errorSummary??null,now(),id);}

  recordSentMessage(draftId:string,input:{providerMessageKey:string;rfcMessageId:string;from:EmailAddress;sentAt:string}){const draft=this.getDraft(draftId);if(!draft)throw new Error('Draft not found');const timestamp=now();const organisationId=draft.organisationId??this.fallbackOrganisationId();return this.connection.transaction(()=>{
    let threadId=draft.threadId as string|null;
    if(!threadId){threadId=randomUUID();this.connection.prepare(`INSERT INTO email_threads(id,account_id,provider_thread_key,subject,latest_message_at,organisation_id,contact_id,match_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'matched',?,?)`).run(threadId,draft.accountId,input.providerMessageKey,draft.subject,input.sentAt,organisationId,draft.contactId,timestamp,timestamp);}else this.connection.prepare('UPDATE email_threads SET latest_message_at=?,subject=coalesce(nullif(?,\'\'),subject),updated_at=? WHERE id=?').run(input.sentAt,draft.subject,timestamp,threadId);
    const communicationId=randomUUID();this.connection.prepare(`INSERT INTO communications(id,organisation_id,contact_id,engagement_id,channel,direction,subject,body,occurred_at,external_id,thread_key,status,created_at,updated_at,archived_at) VALUES(?,?,?,?,'email','outbound',?,?,?,?,?,'sent',?,?,NULL)`).run(communicationId,organisationId,draft.contactId,draft.engagementId,draft.subject||null,draft.bodyText||'(No message body)',input.sentAt,input.providerMessageKey,threadId,timestamp,timestamp);
    const messageId=randomUUID();this.connection.prepare(`INSERT INTO email_messages(id,account_id,thread_id,provider_message_key,rfc_message_id,direction,sender_json,recipients_json,subject,body_text,body_html,sent_at,received_at,is_read,raw_headers_json,communication_id,created_at,updated_at) VALUES(?,?,?,?,?,'outbound',?,?,?,?,?,?,?,1,'{}',?,?,?)`).run(messageId,draft.accountId,threadId,input.providerMessageKey,input.rfcMessageId,JSON.stringify(input.from),JSON.stringify({to:draft.to,cc:draft.cc,bcc:draft.bcc}),draft.subject,draft.bodyText,draft.bodyHtml,input.sentAt,input.sentAt,communicationId,timestamp,timestamp);
    for(const document of draft.documents)this.connection.prepare(`INSERT OR IGNORE INTO email_attachments(id,email_message_id,document_id,content_id,inline,created_at) VALUES(?,?,?,NULL,0,?)`).run(randomUUID(),messageId,document.documentId,timestamp);
    this.connection.prepare(`UPDATE email_drafts SET status='sent',sent_message_id=?,sent_at=?,updated_at=?,last_error=NULL WHERE id=?`).run(messageId,input.sentAt,timestamp,draftId);
    return {messageId,threadId,communicationId};
  })();}

  getOriginalMessage(id:string){const row=this.connection.prepare('SELECT * FROM email_messages WHERE id=?').get(id) as Record<string,unknown>|undefined;return row?{id:row.id,rfcMessageId:row.rfc_message_id,subject:row.subject,from:json<EmailAddress>(row.sender_json,{address:''}),recipients:json<{to:EmailAddress[];cc:EmailAddress[];bcc:EmailAddress[]}>(row.recipients_json,{to:[],cc:[],bcc:[]}),bodyText:row.body_text,threadId:row.thread_id}:null;}
  getAccount(id:string){const row=this.connection.prepare('SELECT * FROM communication_accounts WHERE id=? AND kind=\'email\' AND archived_at IS NULL').get(id) as Record<string,unknown>|undefined;return row?{id:row.id,username:row.username,serverUrl:row.server_url,settings:json<Record<string,unknown>>(row.settings_json,{}),credentialKey:row.credential_key,enabled:Boolean(row.enabled)}:null;}
  getCalendar(id:string){const row=this.connection.prepare(`SELECT c.*,a.server_url,a.username,a.settings_json,a.credential_key,a.enabled FROM calendars c JOIN communication_accounts a ON a.id=c.account_id WHERE c.id=? AND a.archived_at IS NULL`).get(id) as Record<string,unknown>|undefined;return row?{id:row.id,accountId:row.account_id,providerCalendarKey:row.provider_calendar_key,displayName:row.display_name,serverUrl:row.server_url,username:row.username,settings:json<Record<string,unknown>>(row.settings_json,{}),credentialKey:row.credential_key,enabled:Boolean(row.enabled)}:null;}
  getCalendarEvent(id:string){const row=this.connection.prepare('SELECT * FROM calendar_events WHERE id=?').get(id) as Record<string,unknown>|undefined;return row?{id:row.id,calendarId:row.calendar_id,providerEventKey:row.provider_event_key,etag:row.etag,title:row.title,description:row.description,location:row.location,startsAt:row.starts_at,endsAt:row.ends_at,timezone:row.timezone,recurrence:json<Record<string,unknown>>(row.recurrence_json,{}),attendees:json<EmailAddress[]>(row.attendees_json,[]),cancelled:Boolean(row.cancelled),organisationId:row.organisation_id,contactId:row.contact_id,engagementId:row.engagement_id,communicationId:row.communication_id}:null;}

  startCalendarOperation(calendarId:string,operation:'create'|'update'|'cancel'|'complete',eventId:string|null,expectedEtag:string|null,request:unknown){const id=randomUUID();const startedAt=now();this.connection.prepare(`INSERT INTO calendar_write_operations(id,calendar_event_id,calendar_id,operation,status,expected_etag,request_json,started_at) VALUES(?,?,?,?,'running',?,?,?)`).run(id,eventId,calendarId,operation,expectedEtag,JSON.stringify(request),startedAt);return {id,startedAt};}
  finishCalendarOperation(id:string,input:{status:'succeeded'|'conflict'|'failed';etag?:string|null;providerEventKey?:string|null;error?:string|null}){this.connection.prepare(`UPDATE calendar_write_operations SET status=?,resulting_etag=?,provider_event_key=?,error_summary=?,completed_at=? WHERE id=?`).run(input.status,input.etag??null,input.providerEventKey??null,input.error??null,now(),id);}
  createLocalCalendarEvent(calendarId:string,event:CalendarWriteInput,input:{organisationId?:string|null;contactId?:string|null;engagementId?:string|null;etag?:string|null}){const id=randomUUID();const communicationId=randomUUID();const timestamp=now();const organisationId=input.organisationId??this.fallbackOrganisationId();this.connection.transaction(()=>{this.connection.prepare(`INSERT INTO communications(id,organisation_id,contact_id,engagement_id,channel,direction,subject,body,occurred_at,external_id,status,created_at,updated_at,archived_at) VALUES(?,?,?,?,'meeting','internal',?,?,?,?, 'matched',?,?,NULL)`).run(communicationId,organisationId,input.contactId??null,input.engagementId??null,event.title,event.description??event.location??'Calendar event',event.startsAt,event.providerEventKey,timestamp,timestamp);this.connection.prepare(`INSERT INTO calendar_events(id,calendar_id,provider_event_key,etag,title,description,location,starts_at,ends_at,timezone,recurrence_json,attendees_json,cancelled,organisation_id,contact_id,engagement_id,match_status,communication_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,'matched',?,?,?)`).run(id,calendarId,event.providerEventKey,input.etag??null,event.title,event.description??null,event.location??null,event.startsAt,event.endsAt,event.timezone,JSON.stringify(event.recurrence??{}),JSON.stringify(event.attendees),organisationId,input.contactId??null,input.engagementId??null,communicationId,timestamp,timestamp);})();return this.getCalendarEvent(id)!;}
  updateLocalCalendarEvent(id:string,event:CalendarWriteInput,etag:string|null){const timestamp=now();const current=this.getCalendarEvent(id);if(!current)throw new Error('Calendar event not found');this.connection.transaction(()=>{this.connection.prepare(`UPDATE calendar_events SET etag=?,title=?,description=?,location=?,starts_at=?,ends_at=?,timezone=?,recurrence_json=?,attendees_json=?,cancelled=?,updated_at=? WHERE id=?`).run(etag,event.title,event.description??null,event.location??null,event.startsAt,event.endsAt,event.timezone,JSON.stringify(event.recurrence??{}),JSON.stringify(event.attendees),event.cancelled?1:0,timestamp,id);this.connection.prepare(`UPDATE communications SET subject=?,body=?,occurred_at=?,status=?,updated_at=? WHERE id=?`).run(event.title,event.description??event.location??'Calendar event',event.startsAt,event.cancelled?'ignored':'matched',timestamp,current.communicationId);})();return this.getCalendarEvent(id)!;}
  completeMeeting(id:string,notes:string){const event=this.getCalendarEvent(id);if(!event)throw new Error('Calendar event not found');const activityId=randomUUID();const timestamp=now();const organisationId=event.organisationId??this.fallbackOrganisationId();this.connection.transaction(()=>{this.connection.prepare(`INSERT INTO activities(id,organisation_id,contact_id,engagement_id,type,body,author,occurred_at,follow_up_date,follow_up_completed_at,source,source_reference,created_at,updated_at,archived_at) VALUES(?,?,?,?,'meeting',?,'Calendar completion',?,NULL,NULL,'system',?,?,?,NULL)`).run(activityId,organisationId,event.contactId,event.engagementId,notes.trim()||`Completed meeting: ${event.title}`,event.endsAt,`calendar-complete:${id}`,timestamp,timestamp);this.connection.prepare('UPDATE communications SET body=?,status=\'matched\',updated_at=? WHERE id=?').run(notes.trim()||`Completed meeting: ${event.title}`,timestamp,event.communicationId);})();return {activityId,event:this.getCalendarEvent(id)};}

  listTemplates(){return (this.connection.prepare('SELECT * FROM workflow_templates ORDER BY name').all() as Array<Record<string,unknown>>).map((row)=>({id:row.id,key:row.key,name:row.name,description:row.description,triggerType:row.trigger_type,conditions:json(row.condition_json,{}),actions:json(row.action_json,[]),builtIn:Boolean(row.built_in)}));}
  getTemplate(key:string){return this.listTemplates().find((item)=>item.key===key)??null;}
  duplicateWorkflow(id:string,name:string){const row=this.connection.prepare('SELECT * FROM workflow_definitions WHERE id=? AND archived_at IS NULL').get(id) as Record<string,unknown>|undefined;if(!row)throw new Error('Workflow not found');const newId=randomUUID();const timestamp=now();this.connection.prepare(`INSERT INTO workflow_definitions(id,name,description,enabled,version,trigger_type,condition_json,action_json,created_at,updated_at,archived_at) VALUES(?,?,?,0,1,?,?,?,?,?,NULL)`).run(newId,name.trim(),row.description,row.trigger_type,row.condition_json,row.action_json,timestamp,timestamp);return newId;}
  setWorkflowPolicy(id:string,input:{maxRunsPerHour:number;timeoutMs:number;maxDepth:number;dryRun:boolean}){const timestamp=now();this.connection.prepare(`INSERT INTO workflow_policies(workflow_definition_id,max_runs_per_hour,timeout_ms,max_depth,dry_run,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(workflow_definition_id) DO UPDATE SET max_runs_per_hour=excluded.max_runs_per_hour,timeout_ms=excluded.timeout_ms,max_depth=excluded.max_depth,dry_run=excluded.dry_run,updated_at=excluded.updated_at`).run(id,input.maxRunsPerHour,input.timeoutMs,input.maxDepth,input.dryRun?1:0,timestamp);return this.getWorkflowPolicy(id);}
  getWorkflowPolicy(id:string){const row=this.connection.prepare('SELECT * FROM workflow_policies WHERE workflow_definition_id=?').get(id) as Record<string,unknown>|undefined;return row?{workflowDefinitionId:row.workflow_definition_id,maxRunsPerHour:row.max_runs_per_hour,timeoutMs:row.timeout_ms,maxDepth:row.max_depth,dryRun:Boolean(row.dry_run),updatedAt:row.updated_at}:{workflowDefinitionId:id,maxRunsPerHour:100,timeoutMs:10000,maxDepth:3,dryRun:false,updatedAt:null};}
  recentWorkflowRuns(id:string,since:string){return Number((this.connection.prepare('SELECT count(*) AS count FROM workflow_runs WHERE workflow_definition_id=? AND started_at>=?').get(id,since) as {count:number}).count);}

  startMaintenance(operation:'document_integrity'|'search_reindex'|'communication_relink'|'storage_report'){const id=randomUUID();const startedAt=now();this.connection.prepare(`INSERT INTO maintenance_runs(id,operation,status,started_at) VALUES(?,?,'running',?)`).run(id,operation,startedAt);return {id,startedAt};}
  finishMaintenance(id:string,status:'succeeded'|'failed',result:unknown,error:string|null=null){this.connection.prepare(`UPDATE maintenance_runs SET status=?,result_json=?,error_summary=?,completed_at=? WHERE id=?`).run(status,result===undefined?null:JSON.stringify(result),error,now(),id);}
  health(){const scalar=(sql:string)=>Number((this.connection.prepare(sql).get() as {count:number}).count);return {generatedAt:now(),accounts:{failed:scalar("SELECT count(*) AS count FROM communication_accounts WHERE health_status='failed' AND archived_at IS NULL"),degraded:scalar("SELECT count(*) AS count FROM communication_accounts WHERE health_status='degraded' AND archived_at IS NULL")},synchronization:{failed:scalar("SELECT count(*) AS count FROM synchronization_runs WHERE status='failed'")},reminders:{failed:scalar("SELECT count(*) AS count FROM reminders WHERE status='failed'")},workflows:{failed:scalar("SELECT count(*) AS count FROM workflow_runs WHERE status IN ('failed','partially_failed')")},drafts:{failed:scalar("SELECT count(*) AS count FROM email_drafts WHERE status='failed'")},calendarWrites:{failed:scalar("SELECT count(*) AS count FROM calendar_write_operations WHERE status IN ('failed','conflict')")},documents:{count:scalar('SELECT count(*) AS count FROM documents WHERE archived_at IS NULL'),bytes:scalar('SELECT coalesce(sum(byte_size),0) AS count FROM documents WHERE archived_at IS NULL')}};}

  private fallbackOrganisationId(){const row=this.connection.prepare(`SELECT id FROM organisations WHERE archived_at IS NULL ORDER BY CASE WHEN name='Good Order Ltd' THEN 0 ELSE 1 END,created_at LIMIT 1`).get() as {id:string}|undefined;if(!row)throw new Error('At least one active organisation is required');return row.id;}
}
