import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import { sqlite } from './connection';
import type { RemoteCalendar,RemoteCalendarEvent,RemoteEmailMessage } from '../integrations/ConnectedAdapters';

const now=()=>new Date().toISOString();
function parseJson<T>(value:unknown,fallback:T):T{if(typeof value!=='string')return fallback;try{return JSON.parse(value) as T;}catch{return fallback;}}

export interface AccountCreateInput {
  kind:'email'|'calendar';name:string;serverUrl:string;username:string;credentialKey:string;settings?:Record<string,unknown>;enabled?:boolean;
}

export class ConnectedCommunicationsRepository {
  constructor(private readonly connection:Database.Database=sqlite as Database.Database){}

  createAccount(input:AccountCreateInput){
    const id=randomUUID();const timestamp=now();
    this.connection.prepare(`INSERT INTO communication_accounts(id,kind,name,server_url,username,credential_key,settings_json,enabled,health_status,created_at,updated_at,archived_at) VALUES(@id,@kind,@name,@serverUrl,@username,@credentialKey,@settings,@enabled,'unverified',@timestamp,@timestamp,NULL)`).run({id,...input,name:input.name.trim(),serverUrl:input.serverUrl.trim(),username:input.username.trim(),settings:JSON.stringify(input.settings??{}),enabled:input.enabled===false?0:1,timestamp});
    return this.getAccount(id)!;
  }
  getAccount(id:string){const row=this.connection.prepare('SELECT * FROM communication_accounts WHERE id=?').get(id) as Record<string,unknown>|undefined;return row?this.mapAccount(row):null;}
  listAccounts(includeArchived=false){return (this.connection.prepare('SELECT * FROM communication_accounts WHERE (?=1 OR archived_at IS NULL) ORDER BY kind,name').all(includeArchived?1:0) as Array<Record<string,unknown>>).map((row)=>this.mapAccount(row));}
  updateAccountHealth(id:string,status:'unverified'|'healthy'|'degraded'|'failed'|'paused',error:string|null=null){const result=this.connection.prepare('UPDATE communication_accounts SET health_status=?,last_error=?,updated_at=? WHERE id=?').run(status,error,now(),id);if(!result.changes)throw new Error('Communication account not found');return this.getAccount(id)!;}
  updateAccountCursor(id:string,cursor:string|null,lastSyncAt:string,status:'healthy'|'degraded'|'failed',error:string|null){this.connection.prepare('UPDATE communication_accounts SET sync_cursor=?,last_sync_at=?,health_status=?,last_error=?,updated_at=? WHERE id=?').run(cursor,lastSyncAt,status,error,lastSyncAt,id);}
  archiveAccount(id:string){const timestamp=now();const result=this.connection.prepare("UPDATE communication_accounts SET archived_at=coalesce(archived_at,?),enabled=0,health_status='paused',updated_at=? WHERE id=?").run(timestamp,timestamp,id);if(!result.changes)throw new Error('Communication account not found');return this.getAccount(id)!;}

  startSync(accountId:string,type:'email'|'calendar'|'account_test',cursorBefore:string|null){const id=randomUUID();const startedAt=now();this.connection.prepare(`INSERT INTO synchronization_runs(id,account_id,sync_type,status,cursor_before,started_at) VALUES(?,?,?,'running',?,?)`).run(id,accountId,type,cursorBefore,startedAt);return {id,startedAt};}
  finishSync(id:string,input:{status:'succeeded'|'partially_failed'|'failed';cursorAfter?:string|null;fetchedCount?:number;createdCount?:number;updatedCount?:number;matchedCount?:number;failureCount?:number;errorSummary?:string|null}){this.connection.prepare(`UPDATE synchronization_runs SET status=@status,cursor_after=@cursorAfter,fetched_count=@fetchedCount,created_count=@createdCount,updated_count=@updatedCount,matched_count=@matchedCount,failure_count=@failureCount,error_summary=@errorSummary,completed_at=@completedAt WHERE id=@id`).run({id,status:input.status,cursorAfter:input.cursorAfter??null,fetchedCount:input.fetchedCount??0,createdCount:input.createdCount??0,updatedCount:input.updatedCount??0,matchedCount:input.matchedCount??0,failureCount:input.failureCount??0,errorSummary:input.errorSummary??null,completedAt:now()});return this.getSyncRun(id)!;}
  getSyncRun(id:string){const row=this.connection.prepare(`SELECT r.*,a.name AS account_name FROM synchronization_runs r JOIN communication_accounts a ON a.id=r.account_id WHERE r.id=?`).get(id) as Record<string,unknown>|undefined;return row?this.mapSyncRun(row):null;}
  listSyncRuns(limit=100){return (this.connection.prepare(`SELECT r.*,a.name AS account_name FROM synchronization_runs r JOIN communication_accounts a ON a.id=r.account_id ORDER BY r.started_at DESC LIMIT ?`).all(limit) as Array<Record<string,unknown>>).map((row)=>this.mapSyncRun(row));}

  upsertEmailMessage(accountId:string,message:RemoteEmailMessage,match:{organisationId:string|null;contactId:string|null;status:'matched'|'suggested'|'unmatched'}):{messageId:string;threadId:string;created:boolean;communicationId:string}{
    const existing=this.connection.prepare('SELECT id,thread_id,communication_id FROM email_messages WHERE account_id=? AND provider_message_key=?').get(accountId,message.providerMessageKey) as {id:string;thread_id:string;communication_id:string}|undefined;
    if(existing){this.connection.prepare('UPDATE email_messages SET is_read=?,updated_at=? WHERE id=?').run(message.isRead?1:0,now(),existing.id);return {messageId:existing.id,threadId:existing.thread_id,created:false,communicationId:existing.communication_id};}
    const timestamp=now();const threadExisting=this.connection.prepare('SELECT id FROM email_threads WHERE account_id=? AND provider_thread_key=?').get(accountId,message.providerThreadKey) as {id:string}|undefined;const threadId=threadExisting?.id??randomUUID();
    if(threadExisting){this.connection.prepare(`UPDATE email_threads SET subject=coalesce(?,subject),latest_message_at=?,organisation_id=coalesce(?,organisation_id),contact_id=coalesce(?,contact_id),match_status=?,updated_at=? WHERE id=?`).run(message.subject??null,message.sentAt,match.organisationId,match.contactId,match.status,timestamp,threadId);}else{this.connection.prepare(`INSERT INTO email_threads(id,account_id,provider_thread_key,subject,latest_message_at,organisation_id,contact_id,match_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(threadId,accountId,message.providerThreadKey,message.subject??null,message.sentAt,match.organisationId,match.contactId,match.status,timestamp,timestamp);}
    const communicationId=randomUUID();const body=message.bodyText||message.bodyHtml?.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()||'(No message body)';
    this.connection.prepare(`INSERT INTO communications(id,organisation_id,contact_id,channel,direction,subject,body,occurred_at,external_id,thread_key,status,created_at,updated_at,archived_at) VALUES(?,?,?,'email',?,?,?,?,?,?,?,?,?,NULL)`).run(communicationId,match.organisationId??this.fallbackOrganisationId(),match.contactId,message.direction,message.subject??null,body,message.sentAt,message.providerMessageKey,message.providerThreadKey,match.status==='matched'?'matched':'unmatched',timestamp,timestamp);
    const messageId=randomUUID();
    this.connection.prepare(`INSERT INTO email_messages(id,account_id,thread_id,provider_message_key,rfc_message_id,direction,sender_json,recipients_json,subject,body_text,body_html,sent_at,received_at,is_read,raw_headers_json,communication_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(messageId,accountId,threadId,message.providerMessageKey,message.rfcMessageId??null,message.direction,JSON.stringify(message.from),JSON.stringify({to:message.to,cc:message.cc??[],bcc:message.bcc??[]}),message.subject??null,message.bodyText,message.bodyHtml??null,message.sentAt,message.receivedAt,message.isRead?1:0,JSON.stringify(message.headers??{}),communicationId,timestamp,timestamp);
    return {messageId,threadId,created:true,communicationId};
  }

  linkEmailAttachment(emailMessageId:string,documentId:string,contentId:string|null,inline:boolean){this.connection.prepare(`INSERT OR IGNORE INTO email_attachments(id,email_message_id,document_id,content_id,inline,created_at) VALUES(?,?,?,?,?,?)`).run(randomUUID(),emailMessageId,documentId,contentId,inline?1:0,now());}
  listEmailThreads(input:{status?:string;organisationId?:string;limit?:number}={}){const rows=this.connection.prepare(`SELECT t.*,a.name AS account_name,o.name AS organisation_name FROM email_threads t JOIN communication_accounts a ON a.id=t.account_id LEFT JOIN organisations o ON o.id=t.organisation_id WHERE (@status IS NULL OR t.match_status=@status) AND (@organisationId IS NULL OR t.organisation_id=@organisationId) ORDER BY t.latest_message_at DESC LIMIT @limit`).all({status:input.status??null,organisationId:input.organisationId??null,limit:input.limit??200}) as Array<Record<string,unknown>>;return rows.map((row)=>({id:row.id,accountId:row.account_id,accountName:row.account_name,providerThreadKey:row.provider_thread_key,subject:row.subject,latestMessageAt:row.latest_message_at,organisationId:row.organisation_id,organisationName:row.organisation_name,contactId:row.contact_id,matchStatus:row.match_status}));}
  getEmailThread(id:string){const thread=this.connection.prepare(`SELECT t.*,a.name AS account_name,o.name AS organisation_name FROM email_threads t JOIN communication_accounts a ON a.id=t.account_id LEFT JOIN organisations o ON o.id=t.organisation_id WHERE t.id=?`).get(id) as Record<string,unknown>|undefined;if(!thread)return null;const messages=this.connection.prepare('SELECT * FROM email_messages WHERE thread_id=? ORDER BY sent_at').all(id) as Array<Record<string,unknown>>;return {...this.listEmailThreads({limit:1000}).find((item)=>item.id===id),messages:messages.map((row)=>({id:row.id,direction:row.direction,from:parseJson(row.sender_json,{}),recipients:parseJson(row.recipients_json,{}),subject:row.subject,bodyText:row.body_text,bodyHtml:row.body_html,sentAt:row.sent_at,receivedAt:row.received_at,isRead:Boolean(row.is_read),communicationId:row.communication_id}))};}
  matchEmailThread(id:string,organisationId:string,contactId:string|null){const thread=this.connection.prepare('SELECT id FROM email_threads WHERE id=?').get(id);if(!thread)throw new Error('Email thread not found');this.connection.transaction(()=>{this.connection.prepare("UPDATE email_threads SET organisation_id=?,contact_id=?,match_status='matched',updated_at=? WHERE id=?").run(organisationId,contactId,now(),id);this.connection.prepare("UPDATE communications SET organisation_id=?,contact_id=?,status='matched',updated_at=? WHERE id IN (SELECT communication_id FROM email_messages WHERE thread_id=?)").run(organisationId,contactId,now(),id);this.connection.prepare("UPDATE match_suggestions SET status='accepted',resolved_at=? WHERE source_type='email_thread' AND source_id=? AND suggested_organisation_id=? AND (suggested_contact_id IS ? OR suggested_contact_id=?)").run(now(),id,organisationId,contactId,contactId);})();return this.getEmailThread(id);}

  upsertCalendar(accountId:string,calendar:RemoteCalendar){const existing=this.connection.prepare('SELECT id FROM calendars WHERE account_id=? AND provider_calendar_key=?').get(accountId,calendar.providerCalendarKey) as {id:string}|undefined;const timestamp=now();if(existing){this.connection.prepare('UPDATE calendars SET display_name=?,color=?,updated_at=? WHERE id=?').run(calendar.displayName,calendar.color??null,timestamp,existing.id);return this.getCalendar(existing.id)!;}const id=randomUUID();this.connection.prepare(`INSERT INTO calendars(id,account_id,provider_calendar_key,display_name,color,selected,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)`).run(id,accountId,calendar.providerCalendarKey,calendar.displayName,calendar.color??null,timestamp,timestamp);return this.getCalendar(id)!;}
  getCalendar(id:string){const row=this.connection.prepare(`SELECT c.*,a.name AS account_name FROM calendars c JOIN communication_accounts a ON a.id=c.account_id WHERE c.id=?`).get(id) as Record<string,unknown>|undefined;return row?{id:row.id,accountId:row.account_id,accountName:row.account_name,providerCalendarKey:row.provider_calendar_key,displayName:row.display_name,color:row.color,selected:Boolean(row.selected),createdAt:row.created_at,updatedAt:row.updated_at}:null;}
  listCalendars(accountId?:string){return (this.connection.prepare(`SELECT c.*,a.name AS account_name FROM calendars c JOIN communication_accounts a ON a.id=c.account_id WHERE (? IS NULL OR c.account_id=?) ORDER BY c.display_name`).all(accountId??null,accountId??null) as Array<Record<string,unknown>>).map((row)=>({id:row.id,accountId:row.account_id,accountName:row.account_name,providerCalendarKey:row.provider_calendar_key,displayName:row.display_name,color:row.color,selected:Boolean(row.selected),createdAt:row.created_at,updatedAt:row.updated_at}));}

  upsertCalendarEvent(calendarId:string,event:RemoteCalendarEvent,match:{organisationId:string|null;contactId:string|null;status:'matched'|'suggested'|'unmatched'}):{id:string;created:boolean}{const existing=this.connection.prepare('SELECT id,communication_id FROM calendar_events WHERE calendar_id=? AND provider_event_key=?').get(calendarId,event.providerEventKey) as {id:string;communication_id:string}|undefined;const timestamp=now();if(existing){this.connection.prepare(`UPDATE calendar_events SET etag=@etag,title=@title,description=@description,location=@location,starts_at=@startsAt,ends_at=@endsAt,timezone=@timezone,recurrence_json=@recurrence,attendees_json=@attendees,cancelled=@cancelled,organisation_id=coalesce(@organisationId,organisation_id),contact_id=coalesce(@contactId,contact_id),match_status=@matchStatus,updated_at=@timestamp WHERE id=@id`).run({id:existing.id,etag:event.etag??null,title:event.title,description:event.description??null,location:event.location??null,startsAt:event.startsAt,endsAt:event.endsAt,timezone:event.timezone,recurrence:JSON.stringify(event.recurrence??{}),attendees:JSON.stringify(event.attendees),cancelled:event.cancelled?1:0,organisationId:match.organisationId,contactId:match.contactId,matchStatus:match.status,timestamp});this.connection.prepare(`UPDATE communications SET subject=?,body=?,occurred_at=?,organisation_id=coalesce(?,organisation_id),contact_id=coalesce(?,contact_id),status=?,updated_at=? WHERE id=?`).run(event.title,event.description??event.location??'Calendar event',event.startsAt,match.organisationId,match.contactId,match.status==='matched'?'matched':'unmatched',timestamp,existing.communication_id);return {id:existing.id,created:false};}
    const id=randomUUID();const communicationId=randomUUID();const organisationId=match.organisationId??this.fallbackOrganisationId();this.connection.prepare(`INSERT INTO communications(id,organisation_id,contact_id,channel,direction,subject,body,occurred_at,external_id,status,created_at,updated_at,archived_at) VALUES(?,?,?,'meeting','internal',?,?,?,?,?,?,?,NULL)`).run(communicationId,organisationId,match.contactId,event.title,event.description??event.location??'Calendar event',event.startsAt,event.providerEventKey,match.status==='matched'?'matched':'unmatched',timestamp,timestamp);this.connection.prepare(`INSERT INTO calendar_events(id,calendar_id,provider_event_key,etag,title,description,location,starts_at,ends_at,timezone,recurrence_json,attendees_json,cancelled,organisation_id,contact_id,match_status,communication_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,calendarId,event.providerEventKey,event.etag??null,event.title,event.description??null,event.location??null,event.startsAt,event.endsAt,event.timezone,JSON.stringify(event.recurrence??{}),JSON.stringify(event.attendees),event.cancelled?1:0,match.organisationId,match.contactId,match.status,communicationId,timestamp,timestamp);return {id,created:true};}
  listCalendarEvents(input:{from?:string;to?:string;status?:string;organisationId?:string;limit?:number}={}){const rows=this.connection.prepare(`SELECT e.*,c.display_name AS calendar_name,a.name AS account_name,o.name AS organisation_name FROM calendar_events e JOIN calendars c ON c.id=e.calendar_id JOIN communication_accounts a ON a.id=c.account_id LEFT JOIN organisations o ON o.id=e.organisation_id WHERE (@from IS NULL OR e.ends_at>=@from) AND (@to IS NULL OR e.starts_at<=@to) AND (@status IS NULL OR e.match_status=@status) AND (@organisationId IS NULL OR e.organisation_id=@organisationId) ORDER BY e.starts_at LIMIT @limit`).all({from:input.from??null,to:input.to??null,status:input.status??null,organisationId:input.organisationId??null,limit:input.limit??500}) as Array<Record<string,unknown>>;return rows.map((row)=>({id:row.id,calendarId:row.calendar_id,calendarName:row.calendar_name,accountName:row.account_name,providerEventKey:row.provider_event_key,etag:row.etag,title:row.title,description:row.description,location:row.location,startsAt:row.starts_at,endsAt:row.ends_at,timezone:row.timezone,recurrence:parseJson(row.recurrence_json,{}),attendees:parseJson(row.attendees_json,[]),cancelled:Boolean(row.cancelled),organisationId:row.organisation_id,organisationName:row.organisation_name,contactId:row.contact_id,engagementId:row.engagement_id,matchStatus:row.match_status,communicationId:row.communication_id}));}
  matchCalendarEvent(id:string,organisationId:string,contactId:string|null,engagementId:string|null){const event=this.connection.prepare('SELECT communication_id FROM calendar_events WHERE id=?').get(id) as {communication_id:string}|undefined;if(!event)throw new Error('Calendar event not found');this.connection.transaction(()=>{this.connection.prepare("UPDATE calendar_events SET organisation_id=?,contact_id=?,engagement_id=?,match_status='matched',updated_at=? WHERE id=?").run(organisationId,contactId,engagementId,now(),id);this.connection.prepare("UPDATE communications SET organisation_id=?,contact_id=?,engagement_id=?,status='matched',updated_at=? WHERE id=?").run(organisationId,contactId,engagementId,now(),event.communication_id);this.connection.prepare("UPDATE match_suggestions SET status='accepted',resolved_at=? WHERE source_type='calendar_event' AND source_id=? AND suggested_organisation_id=?").run(now(),id,organisationId);})();return this.listCalendarEvents({limit:1000}).find((item)=>item.id===id);}

  createSuggestion(input:{sourceType:'email_thread'|'calendar_event';sourceId:string;organisationId:string|null;contactId:string|null;reason:string;confidence:number}){const id=randomUUID();this.connection.prepare(`INSERT OR IGNORE INTO match_suggestions(id,source_type,source_id,suggested_organisation_id,suggested_contact_id,reason,confidence,status,created_at) VALUES(?,?,?,?,?,?,?,'pending',?)`).run(id,input.sourceType,input.sourceId,input.organisationId,input.contactId,input.reason,input.confidence,now());}
  listSuggestions(status='pending'){return (this.connection.prepare(`SELECT s.*,o.name AS organisation_name,trim(coalesce(c.first_name,'') || ' ' || coalesce(c.last_name,'')) AS contact_name FROM match_suggestions s LEFT JOIN organisations o ON o.id=s.suggested_organisation_id LEFT JOIN contacts c ON c.id=s.suggested_contact_id WHERE s.status=? ORDER BY s.confidence DESC,s.created_at`).all(status) as Array<Record<string,unknown>>).map((row)=>({id:row.id,sourceType:row.source_type,sourceId:row.source_id,suggestedOrganisationId:row.suggested_organisation_id,organisationName:row.organisation_name,suggestedContactId:row.suggested_contact_id,contactName:row.contact_name,reason:row.reason,confidence:row.confidence,status:row.status,createdAt:row.created_at,resolvedAt:row.resolved_at}));}
  rejectSuggestion(id:string){const result=this.connection.prepare("UPDATE match_suggestions SET status='rejected',resolved_at=? WHERE id=? AND status='pending'").run(now(),id);if(!result.changes)throw new Error('Pending match suggestion not found');}

  findContactByEmail(email:string){return this.connection.prepare(`SELECT c.id AS contact_id,c.organisation_id,o.name AS organisation_name FROM contacts c JOIN organisations o ON o.id=c.organisation_id WHERE lower(c.email)=lower(?) AND c.archived_at IS NULL AND c.status='active'`).all(email) as Array<{contact_id:string;organisation_id:string;organisation_name:string}>;}
  findOrganisationByDomain(domain:string){return this.connection.prepare(`SELECT id,name,website FROM organisations WHERE archived_at IS NULL AND website IS NOT NULL AND lower(replace(replace(replace(website,'https://',''),'http://',''),'www.','')) LIKE lower(?)`).all(`${domain}%`) as Array<{id:string;name:string;website:string}>;}

  private fallbackOrganisationId():string {const row=this.connection.prepare(`SELECT id FROM organisations WHERE archived_at IS NULL ORDER BY CASE WHEN name='Good Order Ltd' THEN 0 ELSE 1 END,created_at LIMIT 1`).get() as {id:string}|undefined;if(!row)throw new Error('At least one active organisation is required');return row.id;}
  private mapAccount(row:Record<string,unknown>){return {id:row.id,kind:row.kind,name:row.name,serverUrl:row.server_url,username:row.username,credentialKey:row.credential_key,settings:parseJson(row.settings_json,{}),enabled:Boolean(row.enabled),healthStatus:row.health_status,syncCursor:row.sync_cursor,lastSyncAt:row.last_sync_at,lastError:row.last_error,createdAt:row.created_at,updatedAt:row.updated_at,archivedAt:row.archived_at};}
  private mapSyncRun(row:Record<string,unknown>){return {id:row.id,accountId:row.account_id,accountName:row.account_name,syncType:row.sync_type,status:row.status,cursorBefore:row.cursor_before,cursorAfter:row.cursor_after,fetchedCount:row.fetched_count,createdCount:row.created_count,updatedCount:row.updated_count,matchedCount:row.matched_count,failureCount:row.failure_count,errorSummary:row.error_summary,startedAt:row.started_at,completedAt:row.completed_at};}
}
