import crypto from 'node:crypto';
import type Database from 'better-sqlite3';
import { sqlite } from './connection';
import type { RequestIdentity } from './SecurityRepository';

export type ReportKey='executive'|'revenue'|'pipeline'|'activity'|'workload'|'concentration'|'operations';
export interface ReportFilters {from?:string;to?:string;ownerUserId?:string;teamId?:string;}

const now=()=>new Date().toISOString();
function parse<T>(value:unknown,fallback:T):T{if(typeof value!=='string')return fallback;try{return JSON.parse(value) as T;}catch{return fallback;}}
function monthStart(date:Date):string{return new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),1)).toISOString();}
function range(filters:ReportFilters){const to=filters.to?new Date(filters.to):new Date();const from=filters.from?new Date(filters.from):new Date(Date.UTC(to.getUTCFullYear(),to.getUTCMonth()-11,1));if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||from>to)throw new Error('Invalid report date range');if(to.getTime()-from.getTime()>1000*60*60*24*366*5)throw new Error('Report range cannot exceed five years');return {from:from.toISOString(),to:to.toISOString(),fromMonth:monthStart(from).slice(0,7),toMonth:monthStart(to).slice(0,7)};}
function invoiceCte(){return `WITH invoice_totals AS (SELECT i.id,i.customer_id,i.status,i.created_at,MAX(0,CAST(ROUND(COALESCE(SUM(ii.quantity*ii.unit_price*(1+(ii.tax_rate/100.0))),0)-i.discount) AS INTEGER)) AS total_cents FROM invoices i LEFT JOIN invoice_items ii ON ii.invoice_id=i.id GROUP BY i.id), payment_totals AS (SELECT invoice_id,COALESCE(SUM(amount),0) AS paid_cents FROM payments GROUP BY invoice_id)`;}
function visibilityAllowed(row:{owner_user_id:string;owner_team_id:string|null;visibility:string},identity:RequestIdentity):boolean{return row.owner_user_id===identity.id||row.visibility==='all'||(row.visibility==='team'&&Boolean(row.owner_team_id&&identity.teams.some((team)=>team.id===row.owner_team_id)));}
function canAdminister(identity:RequestIdentity):boolean{return identity.roles.some((role)=>role.key==='owner'||role.key==='administrator');}
function csvCell(value:unknown):string{const text=value===null||value===undefined?'':typeof value==='object'?JSON.stringify(value):String(value);return /[",\n\r]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}

export class ReportingRepository {
  constructor(private readonly connection:Database.Database=sqlite as Database.Database){}

  run(key:ReportKey,filters:ReportFilters={}){switch(key){case'executive':return this.executive(filters);case'revenue':return this.revenue(filters);case'pipeline':return this.pipeline(filters);case'activity':return this.activity(filters);case'workload':return this.workload(filters);case'concentration':return this.concentration(filters);case'operations':return this.operations(filters);}}

  executive(filters:ReportFilters={}){
    const dates=range(filters);const params={from:dates.from,to:dates.to,now:now()};
    const kpis={
      activeClients:(this.connection.prepare(`SELECT count(*) AS count FROM organisations WHERE status='active_client' AND archived_at IS NULL`).get() as {count:number}).count,
      activeEngagements:(this.connection.prepare(`SELECT count(*) AS count FROM engagements WHERE status='active' AND archived_at IS NULL`).get() as {count:number}).count,
      openTasks:(this.connection.prepare(`SELECT count(*) AS count FROM tasks WHERE status IN ('open','in_progress','blocked') AND archived_at IS NULL`).get() as {count:number}).count,
      overdueTasks:(this.connection.prepare(`SELECT count(*) AS count FROM tasks WHERE status IN ('open','in_progress','blocked') AND archived_at IS NULL AND due_at IS NOT NULL AND due_at<@now`).get(params) as {count:number}).count,
      activities:(this.connection.prepare(`SELECT count(*) AS count FROM activities WHERE archived_at IS NULL AND occurred_at BETWEEN @from AND @to`).get(params) as {count:number}).count,
      collectedRevenueCents:(this.connection.prepare(`SELECT COALESCE(SUM(amount),0) AS value FROM payments WHERE payment_date BETWEEN @from AND @to`).get(params) as {value:number}).value,
      outstandingCents:(this.connection.prepare(`${invoiceCte()} SELECT COALESCE(SUM(MAX(it.total_cents-COALESCE(pt.paid_cents,0),0)),0) AS value FROM invoice_totals it LEFT JOIN payment_totals pt ON pt.invoice_id=it.id WHERE it.status NOT IN ('paid','cancelled')`).get() as {value:number}).value,
      auditEvents:(this.connection.prepare(`SELECT count(*) AS count FROM audit_events WHERE occurred_at BETWEEN @from AND @to`).get(params) as {count:number}).count,
    };
    return {key:'executive',generatedAt:now(),filters:dates,kpis,revenue:this.revenue(filters),pipeline:this.pipeline(filters),workload:this.workload(filters),concentration:this.concentration(filters)};
  }

  revenue(filters:ReportFilters={}){
    const dates=range(filters);const params={from:dates.from,to:dates.to};const months=new Map<string,{month:string;invoicedCents:number;collectedCents:number}>();
    const invoiced=this.connection.prepare(`${invoiceCte()} SELECT substr(created_at,1,7) AS month,COALESCE(SUM(total_cents),0) AS value FROM invoice_totals WHERE created_at BETWEEN @from AND @to AND status<>'cancelled' GROUP BY substr(created_at,1,7) ORDER BY month`).all(params) as Array<{month:string;value:number}>;
    const collected=this.connection.prepare(`SELECT substr(payment_date,1,7) AS month,COALESCE(SUM(amount),0) AS value FROM payments WHERE payment_date BETWEEN @from AND @to GROUP BY substr(payment_date,1,7) ORDER BY month`).all(params) as Array<{month:string;value:number}>;
    for(const row of invoiced)months.set(row.month,{month:row.month,invoicedCents:Number(row.value),collectedCents:0});for(const row of collected){const item=months.get(row.month)??{month:row.month,invoicedCents:0,collectedCents:0};item.collectedCents=Number(row.value);months.set(row.month,item);}
    const aging=this.connection.prepare(`${invoiceCte()} SELECT CASE WHEN julianday('now')-julianday(it.created_at)<=30 THEN '0-30' WHEN julianday('now')-julianday(it.created_at)<=60 THEN '31-60' WHEN julianday('now')-julianday(it.created_at)<=90 THEN '61-90' ELSE '90+' END AS bucket,COALESCE(SUM(MAX(it.total_cents-COALESCE(pt.paid_cents,0),0)),0) AS value FROM invoice_totals it LEFT JOIN payment_totals pt ON pt.invoice_id=it.id WHERE it.status NOT IN ('paid','cancelled') GROUP BY bucket ORDER BY CASE bucket WHEN '0-30' THEN 1 WHEN '31-60' THEN 2 WHEN '61-90' THEN 3 ELSE 4 END`).all() as Array<{bucket:string;value:number}>;
    const series=[...months.values()].sort((a,b)=>a.month.localeCompare(b.month));
    return {key:'revenue',generatedAt:now(),filters:dates,series,aging,totals:{invoicedCents:series.reduce((sum,row)=>sum+row.invoicedCents,0),collectedCents:series.reduce((sum,row)=>sum+row.collectedCents,0),outstandingCents:aging.reduce((sum,row)=>sum+Number(row.value),0)}};
  }

  pipeline(filters:ReportFilters={}){
    const dates=range(filters);const organisationStatus=this.connection.prepare(`SELECT status AS name,count(*) AS value FROM organisations WHERE archived_at IS NULL GROUP BY status ORDER BY value DESC,status`).all();
    const engagementStatus=this.connection.prepare(`SELECT status AS name,count(*) AS value FROM engagements WHERE archived_at IS NULL GROUP BY status ORDER BY value DESC,status`).all();
    const engagementType=this.connection.prepare(`SELECT type AS name,count(*) AS value FROM engagements WHERE archived_at IS NULL GROUP BY type ORDER BY value DESC,type`).all();
    const newOrganisations=this.connection.prepare(`SELECT substr(created_at,1,7) AS month,count(*) AS value FROM organisations WHERE archived_at IS NULL AND created_at BETWEEN ? AND ? GROUP BY substr(created_at,1,7) ORDER BY month`).all(dates.from,dates.to);
    return {key:'pipeline',generatedAt:now(),filters:dates,organisationStatus,engagementStatus,engagementType,newOrganisations};
  }

  activity(filters:ReportFilters={}){
    const dates=range(filters);const params={from:dates.from,to:dates.to};
    const monthly=this.connection.prepare(`SELECT substr(occurred_at,1,7) AS month,count(*) AS value FROM activities WHERE archived_at IS NULL AND occurred_at BETWEEN @from AND @to GROUP BY substr(occurred_at,1,7) ORDER BY month`).all(params);
    const byType=this.connection.prepare(`SELECT type AS name,count(*) AS value FROM activities WHERE archived_at IS NULL AND occurred_at BETWEEN @from AND @to GROUP BY type ORDER BY value DESC,type`).all(params);
    const communications=this.connection.prepare(`SELECT channel AS name,count(*) AS value FROM communications WHERE archived_at IS NULL AND occurred_at BETWEEN @from AND @to GROUP BY channel ORDER BY value DESC,channel`).all(params);
    const followUps=this.connection.prepare(`SELECT CASE WHEN follow_up_completed_at IS NULL THEN 'open' ELSE 'completed' END AS name,count(*) AS value FROM activities WHERE archived_at IS NULL AND follow_up_date IS NOT NULL AND occurred_at BETWEEN @from AND @to GROUP BY name`).all(params);
    return {key:'activity',generatedAt:now(),filters:dates,monthly,byType,communications,followUps};
  }

  workload(filters:ReportFilters={}){
    const dates=range(filters);const params={from:dates.from,to:dates.to,ownerUserId:filters.ownerUserId??null,teamId:filters.teamId??null,now:now()};
    const owners=this.connection.prepare(`SELECT COALESCE(u.id,'unassigned') AS ownerId,COALESCE(u.display_name,NULLIF(t.assigned_to,''),'Unassigned') AS name,SUM(CASE WHEN t.status IN ('open','in_progress','blocked') THEN 1 ELSE 0 END) AS open,SUM(CASE WHEN t.status IN ('open','in_progress','blocked') AND t.due_at IS NOT NULL AND t.due_at<@now THEN 1 ELSE 0 END) AS overdue,SUM(CASE WHEN t.status='completed' AND t.completed_at BETWEEN @from AND @to THEN 1 ELSE 0 END) AS completed FROM tasks t LEFT JOIN users u ON u.id=t.owner_user_id WHERE t.archived_at IS NULL AND (@ownerUserId IS NULL OR t.owner_user_id=@ownerUserId) AND (@teamId IS NULL OR t.owner_team_id=@teamId) GROUP BY COALESCE(u.id,'unassigned'),COALESCE(u.display_name,NULLIF(t.assigned_to,''),'Unassigned') ORDER BY overdue DESC,open DESC,name`).all(params);
    return {key:'workload',generatedAt:now(),filters:dates,owners};
  }

  concentration(filters:ReportFilters={}){
    const dates=range(filters);const rows=this.connection.prepare(`SELECT COALESCE(o.id,'unmapped') AS organisationId,COALESCE(o.name,'Unmapped customers') AS name,COALESCE(SUM(p.amount),0) AS collectedCents FROM payments p JOIN invoices i ON i.id=p.invoice_id LEFT JOIN legacy_customer_crm_mappings m ON m.customer_id=i.customer_id LEFT JOIN organisations o ON o.id=m.organisation_id WHERE p.payment_date BETWEEN ? AND ? GROUP BY COALESCE(o.id,'unmapped'),COALESCE(o.name,'Unmapped customers') ORDER BY collectedCents DESC,name LIMIT 20`).all(dates.from,dates.to) as Array<{organisationId:string;name:string;collectedCents:number}>;
    const total=rows.reduce((sum,row)=>sum+Number(row.collectedCents),0);return {key:'concentration',generatedAt:now(),filters:dates,totalCollectedCents:total,organisations:rows.map((row)=>({...row,sharePercent:total?Math.round((Number(row.collectedCents)/total)*10000)/100:0}))};
  }

  operations(filters:ReportFilters={}){
    const dates=range(filters);const scalar=(sql:string)=>(this.connection.prepare(sql).get() as {count:number}).count;
    return {key:'operations',generatedAt:now(),filters:dates,metrics:{failedSyncRuns:scalar(`SELECT count(*) AS count FROM synchronization_runs WHERE status IN ('failed','partially_failed')`),failedReminders:scalar(`SELECT count(*) AS count FROM reminders WHERE status='failed'`),failedWorkflowRuns:scalar(`SELECT count(*) AS count FROM workflow_runs WHERE status IN ('failed','partially_failed')`),failedDrafts:scalar(`SELECT count(*) AS count FROM email_drafts WHERE status='failed'`),calendarWriteFailures:scalar(`SELECT count(*) AS count FROM calendar_write_operations WHERE status IN ('failed','conflict')`),pendingReconciliation:scalar(`SELECT count(*) AS count FROM outbound_reconciliation_records WHERE status IN ('pending','failed')`),disabledUsers:scalar(`SELECT count(*) AS count FROM users WHERE status='disabled' AND archived_at IS NULL`),activeSessions:scalar(`SELECT count(*) AS count FROM auth_sessions WHERE revoked_at IS NULL AND expires_at>strftime('%Y-%m-%dT%H:%M:%fZ','now')`)}};
  }

  listSavedReports(identity:RequestIdentity){return (this.connection.prepare(`SELECT * FROM saved_reports WHERE archived_at IS NULL ORDER BY updated_at DESC,name`).all() as Array<any>).filter((row)=>visibilityAllowed(row,identity)).map((row)=>this.mapSavedReport(row));}
  createSavedReport(identity:RequestIdentity,input:{name:string;description?:string|null;reportKey:ReportKey;filters?:ReportFilters;visibility?:'private'|'team'|'all';teamId?:string|null}){const id=crypto.randomUUID();const timestamp=now();const teamId=input.visibility==='team'?(input.teamId||identity.teams[0]?.id||null):null;if(input.visibility==='team'&&!teamId)throw new Error('Team visibility requires a team');this.connection.prepare(`INSERT INTO saved_reports(id,name,description,report_key,filters_json,visibility,owner_user_id,owner_team_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,input.name.trim(),input.description?.trim()||null,input.reportKey,JSON.stringify(input.filters??{}),input.visibility??'private',identity.id,teamId,timestamp,timestamp);return this.mapSavedReport(this.connection.prepare(`SELECT * FROM saved_reports WHERE id=?`).get(id) as any);}
  updateSavedReport(identity:RequestIdentity,id:string,input:{name?:string;description?:string|null;filters?:ReportFilters;visibility?:'private'|'team'|'all';teamId?:string|null;archived?:boolean}){const row=this.connection.prepare(`SELECT * FROM saved_reports WHERE id=?`).get(id) as any;if(!row||(!visibilityAllowed(row,identity)&&!canAdminister(identity)))throw new Error('Saved report not found');if(row.owner_user_id!==identity.id&&!canAdminister(identity))throw new Error('Only the owner or administrator can change this report');const visibility=input.visibility??row.visibility;const teamId=visibility==='team'?(input.teamId??row.owner_team_id??identity.teams[0]?.id??null):null;if(visibility==='team'&&!teamId)throw new Error('Team visibility requires a team');this.connection.prepare(`UPDATE saved_reports SET name=?,description=?,filters_json=?,visibility=?,owner_team_id=?,archived_at=?,updated_at=? WHERE id=?`).run(input.name?.trim()||row.name,input.description===undefined?row.description:input.description?.trim()||null,JSON.stringify(input.filters??parse(row.filters_json,{})),visibility,teamId,input.archived?now():row.archived_at,now(),id);return this.mapSavedReport(this.connection.prepare(`SELECT * FROM saved_reports WHERE id=?`).get(id) as any);}

  listDashboards(identity:RequestIdentity){return (this.connection.prepare(`SELECT * FROM report_dashboards WHERE archived_at IS NULL ORDER BY is_default DESC,updated_at DESC,name`).all() as Array<any>).filter((row)=>visibilityAllowed(row,identity)).map((row)=>this.mapDashboard(row));}
  createDashboard(identity:RequestIdentity,input:{name:string;description?:string|null;visibility?:'private'|'team'|'all';teamId?:string|null;widgets?:Array<{widgetKey:string;title?:string;config?:unknown}>}){const id=crypto.randomUUID();const timestamp=now();const teamId=input.visibility==='team'?(input.teamId||identity.teams[0]?.id||null):null;if(input.visibility==='team'&&!teamId)throw new Error('Team visibility requires a team');this.connection.transaction(()=>{this.connection.prepare(`INSERT INTO report_dashboards(id,name,description,visibility,owner_user_id,owner_team_id,is_default,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)`).run(id,input.name.trim(),input.description?.trim()||null,input.visibility??'private',identity.id,teamId,timestamp,timestamp);for(const [position,widget] of (input.widgets??[]).entries())this.addWidgetInternal(id,widget.widgetKey,widget.title,position,widget.config,timestamp);})();return this.mapDashboard(this.connection.prepare(`SELECT * FROM report_dashboards WHERE id=?`).get(id) as any);}
  updateDashboard(identity:RequestIdentity,id:string,input:{name?:string;description?:string|null;visibility?:'private'|'team'|'all';teamId?:string|null;isDefault?:boolean;archived?:boolean}){const row=this.connection.prepare(`SELECT * FROM report_dashboards WHERE id=?`).get(id) as any;if(!row||(!visibilityAllowed(row,identity)&&!canAdminister(identity)))throw new Error('Dashboard not found');if(row.owner_user_id!==identity.id&&!canAdminister(identity))throw new Error('Only the owner or administrator can change this dashboard');const visibility=input.visibility??row.visibility;const teamId=visibility==='team'?(input.teamId??row.owner_team_id??identity.teams[0]?.id??null):null;if(input.isDefault)this.connection.prepare(`UPDATE report_dashboards SET is_default=0 WHERE owner_user_id=?`).run(row.owner_user_id);this.connection.prepare(`UPDATE report_dashboards SET name=?,description=?,visibility=?,owner_team_id=?,is_default=?,archived_at=?,updated_at=? WHERE id=?`).run(input.name?.trim()||row.name,input.description===undefined?row.description:input.description?.trim()||null,visibility,teamId,input.isDefault===undefined?row.is_default:input.isDefault?1:0,input.archived?now():row.archived_at,now(),id);return this.mapDashboard(this.connection.prepare(`SELECT * FROM report_dashboards WHERE id=?`).get(id) as any);}
  addDashboardWidget(identity:RequestIdentity,dashboardId:string,input:{widgetKey:string;title?:string;position?:number;config?:unknown}){const row=this.connection.prepare(`SELECT * FROM report_dashboards WHERE id=?`).get(dashboardId) as any;if(!row||row.owner_user_id!==identity.id&&!canAdminister(identity))throw new Error('Dashboard not found');const timestamp=now();const id=this.addWidgetInternal(dashboardId,input.widgetKey,input.title,input.position??999,input.config,timestamp);return this.connection.prepare(`SELECT * FROM dashboard_widgets WHERE id=?`).get(id);}
  removeDashboardWidget(identity:RequestIdentity,id:string){const row=this.connection.prepare(`SELECT w.id,d.owner_user_id FROM dashboard_widgets w JOIN report_dashboards d ON d.id=w.dashboard_id WHERE w.id=?`).get(id) as {id:string;owner_user_id:string}|undefined;if(!row||row.owner_user_id!==identity.id&&!canAdminister(identity))throw new Error('Dashboard widget not found');this.connection.prepare(`DELETE FROM dashboard_widgets WHERE id=?`).run(id);return {id,deleted:true};}

  createSchedule(identity:RequestIdentity,input:{savedReportId:string;cadence:'daily'|'weekly'|'monthly';nextRunAt:string}){const report=this.connection.prepare(`SELECT * FROM saved_reports WHERE id=? AND archived_at IS NULL`).get(input.savedReportId) as any;if(!report||report.owner_user_id!==identity.id&&!canAdminister(identity))throw new Error('Saved report not found');const id=crypto.randomUUID();const timestamp=now();this.connection.prepare(`INSERT INTO report_schedules(id,saved_report_id,cadence,delivery_mode,enabled,next_run_at,created_at,updated_at) VALUES(?,?,?,'download_queue',1,?,?,?)`).run(id,input.savedReportId,input.cadence,input.nextRunAt,timestamp,timestamp);return this.connection.prepare(`SELECT * FROM report_schedules WHERE id=?`).get(id);}
  listSchedules(identity:RequestIdentity){const rows=this.connection.prepare(`SELECT s.*,r.name AS report_name,r.owner_user_id,r.owner_team_id,r.visibility FROM report_schedules s JOIN saved_reports r ON r.id=s.saved_report_id WHERE r.archived_at IS NULL ORDER BY s.next_run_at`).all() as Array<any>;return rows.filter((row)=>visibilityAllowed(row,identity));}

  exportCsv(key:ReportKey,filters:ReportFilters={}):{filename:string;content:string}{const report=this.run(key,filters) as any;let rows:Array<Record<string,unknown>>=[];if(key==='revenue')rows=report.series;else if(key==='pipeline')rows=report.organisationStatus;else if(key==='activity')rows=report.monthly;else if(key==='workload')rows=report.owners;else if(key==='concentration')rows=report.organisations;else if(key==='operations')rows=Object.entries(report.metrics).map(([metric,value])=>({metric,value}));else rows=Object.entries(report.kpis).map(([metric,value])=>({metric,value}));const headers=[...new Set(rows.flatMap((row)=>Object.keys(row)))];const content=[headers.join(','),...rows.map((row)=>headers.map((header)=>csvCell(row[header])).join(','))].join('\r\n');return {filename:`${key}-report-${new Date().toISOString().slice(0,10)}.csv`,content};}

  private mapSavedReport(row:any){return {id:row.id,name:row.name,description:row.description,reportKey:row.report_key,filters:parse(row.filters_json,{}),visibility:row.visibility,ownerUserId:row.owner_user_id,ownerTeamId:row.owner_team_id,createdAt:row.created_at,updatedAt:row.updated_at,archivedAt:row.archived_at};}
  private mapDashboard(row:any){const widgets=(this.connection.prepare(`SELECT id,widget_key,title,position,config_json,created_at,updated_at FROM dashboard_widgets WHERE dashboard_id=? ORDER BY position,id`).all(row.id) as Array<any>).map((widget)=>({id:widget.id,widgetKey:widget.widget_key,title:widget.title,position:widget.position,config:parse(widget.config_json,{}),createdAt:widget.created_at,updatedAt:widget.updated_at}));return {id:row.id,name:row.name,description:row.description,visibility:row.visibility,ownerUserId:row.owner_user_id,ownerTeamId:row.owner_team_id,isDefault:Boolean(row.is_default),widgets,createdAt:row.created_at,updatedAt:row.updated_at,archivedAt:row.archived_at};}
  private addWidgetInternal(dashboardId:string,widgetKey:string,title:string|undefined,position:number,config:unknown,timestamp:string){const allowed=['executive_kpis','revenue_trend','pipeline_status','activity_mix','workload','concentration','operations'];if(!allowed.includes(widgetKey))throw new Error('Unsupported dashboard widget');const id=crypto.randomUUID();this.connection.prepare(`INSERT INTO dashboard_widgets(id,dashboard_id,widget_key,title,position,config_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,dashboardId,widgetKey,title?.trim()||widgetKey.split('_').map((part)=>part[0].toUpperCase()+part.slice(1)).join(' '),Math.max(0,position),JSON.stringify(config??{}),timestamp,timestamp);return id;}
}
