import { Router } from 'express';
import { z } from 'zod';
import { EXTENSION_CAPABILITIES } from '../../application/extensions/ExtensionManifest';
import { ExtensionRepository } from '../../infrastructure/database/ExtensionRepository';
import { ExtensionRuntimeRepository } from '../../infrastructure/database/ExtensionRuntimeRepository';
import { PlatformRepository,type PlatformRequestIdentity } from '../../infrastructure/database/PlatformRepository';
import type { CrmRequest } from '../middleware/security';

const router=Router();const extensions=new ExtensionRepository();const runtime=new ExtensionRuntimeRepository();const platform=new PlatformRepository();const uuid=z.string().uuid();const key=z.string().trim().min(1).max(100);const capabilities=z.array(z.enum(EXTENSION_CAPABILITIES)).max(EXTENSION_CAPABILITIES.length);
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new Error(result.error.issues.map((issue)=>`${issue.path.join('.')||'request'}: ${issue.message}`).join('; '));return result.data;}
function identity(req:CrmRequest):PlatformRequestIdentity{if(!req.crm?.identity)throw new Error('Authenticated identity is required');return req.crm.identity as PlatformRequestIdentity;}
function fail(res:any,error:unknown):void{const message=error instanceof Error?error.message:String(error);const status=/not found|unavailable|no recovery/i.test(message)?404:/cannot|requires|approved|permission|system-managed|must be disabled|confirmation must/i.test(message)?403:/newer|already|conflict|exists/i.test(message)?409:400;res.status(status).json({error:'EXTENSION_ERROR',message});}
function sendJsonDownload(res:any,filename:string,value:unknown):void{const content=JSON.stringify(value,null,2);res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('content-disposition',`attachment; filename="${filename.replace(/[^a-zA-Z0-9._-]/g,'-')}"`);res.send(content);}
const filters=z.object({from:z.string().datetime({offset:true}).optional(),to:z.string().datetime({offset:true}).optional(),ownerUserId:uuid.optional(),teamId:uuid.optional()}).strict();

router.get('/extensions/runtime',(req,res)=>{try{const query=parse(z.object({locale:z.string().trim().min(2).max(20).default('en')}).strict(),req.query);res.json(runtime.runtime(query.locale));}catch(error){fail(res,error);}});
router.get('/extensions/runtime/assets/:extensionId/:key',(req,res)=>{try{const params=parse(z.object({extensionId:uuid,key}).strict(),req.params);const asset=runtime.asset(params.extensionId,params.key);res.type(asset.mediaType);res.setHeader('cache-control','private, max-age=3600, immutable');res.sendFile(asset.path);}catch(error){fail(res,error);}});
router.get('/extensions/runtime/reports/:extensionId/:key',(req,res)=>{try{const params=parse(z.object({extensionId:uuid,key}).strict(),req.params);res.json(runtime.runReport(params.extensionId,params.key,parse(filters,req.query)));}catch(error){fail(res,error);}});

router.get('/extensions',(_req,res)=>res.json({items:extensions.listExtensions(),supportedCapabilities:EXTENSION_CAPABILITIES}));
router.post('/extensions/validate',(req,res)=>{try{const body=parse(z.object({package:z.unknown(),approvedCapabilities:capabilities.default([])}).strict(),req.body);res.json(extensions.validate(body.package,body.approvedCapabilities??[]));}catch(error){fail(res,error);}});
router.post('/extensions/install',async(req:CrmRequest,res)=>{try{const body=parse(z.object({package:z.unknown(),approvedCapabilities:capabilities.default([])}).strict(),req.body);const actor=identity(req);const result=await extensions.install(body.package,{actorUserId:actor.id,approvedCapabilities:body.approvedCapabilities??[]}) as any;if(!result.reused){const eventType=result.releases?.length>1?'extension.upgraded.v1':'extension.installed.v1';platform.recordEvent({eventType,aggregateType:'extension',aggregateId:String(result.id),actorUserId:actor.id,apiTokenId:actor.apiTokenId??null,requestId:req.crm?.requestId||'unknown',payload:{packageKey:result.packageKey,version:result.currentVersion,status:result.status}});}res.status(result.reused?200:201).json(result);}catch(error){fail(res,error);}});
router.get('/extensions/:id/export',(req,res)=>{try{const {id}=parse(z.object({id:uuid}).strict(),req.params);const value=extensions.exportExtension(id) as any;sendJsonDownload(res,`${value.extension.packageKey}-${value.extension.currentVersion}-metadata.json`,value);}catch(error){fail(res,error);}});
router.get('/extensions/:id/data-export',(req,res)=>{try{const {id}=parse(z.object({id:uuid}).strict(),req.params);const value=runtime.exportData(id) as any;sendJsonDownload(res,`${value.extension.packageKey}-${value.extension.version}-data.json`,value);}catch(error){fail(res,error);}});
router.get('/extensions/:id',(req,res)=>{try{const {id}=parse(z.object({id:uuid}).strict(),req.params);const extension=extensions.getExtension(id);if(!extension)return res.status(404).json({error:'EXTENSION_NOT_FOUND',message:'Extension not found'});res.json(extension);}catch(error){fail(res,error);}});
router.post('/extensions/:id/enable',(req:CrmRequest,res)=>{try{const {id}=parse(z.object({id:uuid}).strict(),req.params);const actor=identity(req);const result=extensions.setEnabled(id,true) as any;platform.recordEvent({eventType:'extension.enabled.v1',aggregateType:'extension',aggregateId:id,actorUserId:actor.id,apiTokenId:actor.apiTokenId??null,requestId:req.crm?.requestId||'unknown',payload:{packageKey:result.packageKey,version:result.currentVersion,status:result.status}});res.json(result);}catch(error){fail(res,error);}});
router.post('/extensions/:id/disable',(req:CrmRequest,res)=>{try{const {id}=parse(z.object({id:uuid}).strict(),req.params);const actor=identity(req);const result=extensions.setEnabled(id,false) as any;platform.recordEvent({eventType:'extension.disabled.v1',aggregateType:'extension',aggregateId:id,actorUserId:actor.id,apiTokenId:actor.apiTokenId??null,requestId:req.crm?.requestId||'unknown',payload:{packageKey:result.packageKey,version:result.currentVersion,status:result.status}});res.json(result);}catch(error){fail(res,error);}});
router.post('/extensions/:id/workflow-templates/:key/instantiate',(req:CrmRequest,res)=>{try{const params=parse(z.object({id:uuid,key}).strict(),req.params);const body=parse(z.object({name:z.string().trim().min(1).max(200).optional()}).strict(),req.body??{});const result=runtime.instantiateWorkflow(params.id,params.key,body.name);res.status((result as any).reused?200:201).json(result);}catch(error){fail(res,error);}});
router.post('/extensions/:id/data-purge',async(req:CrmRequest,res)=>{try{const {id}=parse(z.object({id:uuid}).strict(),req.params);const body=parse(z.object({confirmation:z.string().min(1).max(300)}).strict(),req.body);res.json(await runtime.purgeData(id,identity(req).id,body.confirmation));}catch(error){fail(res,error);}});
router.post('/extensions/:id/releases/:releaseId/restore',async(req,res)=>{try{const params=parse(z.object({id:uuid,releaseId:uuid}).strict(),req.params);const body=parse(z.object({confirmation:z.string().min(1).max(300)}).strict(),req.body);res.json(await runtime.restoreRelease(params.id,params.releaseId,body.confirmation));}catch(error){fail(res,error);}});

export default router;
