import { Router } from 'express';
import { z } from 'zod';
import { OrganisationCreateSchema, OrganisationUpdateSchema, OrganisationStatusSchema } from 'shared';
import { OrganisationRepository } from '../../infrastructure/database/repositories/OrganisationRepository';
import { OrganisationService } from '../../application/services/CrmDomainServices';
import { ValidationError } from '../../application/errors';
const router=Router(); const service=new OrganisationService(new OrganisationRepository());
const Id=z.object({id:z.string().uuid('Invalid ID')}).strict();
const Query=z.object({status:OrganisationStatusSchema.optional(),search:z.string().trim().optional(),includeArchived:z.enum(['true','false']).optional().transform(v=>v==='true'),limit:z.coerce.number().int().min(0).max(200).default(50),offset:z.coerce.number().int().min(0).default(0)}).strict();
const parse=(s:z.ZodTypeAny,v:unknown)=>{const r=s.safeParse(v); if(!r.success)throw new ValidationError('Request validation failed',r.error.format()); return r.data as any};
router.post('/',async(req,res,next)=>{try{res.status(201).json(await service.create(parse(OrganisationCreateSchema,req.body)))}catch(e){next(e)}});
router.get('/',async(req,res,next)=>{try{res.json(await service.list(parse(Query,req.query)))}catch(e){next(e)}});
router.get('/:id',async(req,res,next)=>{try{res.json(await service.get(parse(Id,req.params).id))}catch(e){next(e)}});
router.patch('/:id',async(req,res,next)=>{try{res.json(await service.update(parse(Id,req.params).id,parse(OrganisationUpdateSchema,req.body)))}catch(e){next(e)}});
router.post('/:id/archive',async(req,res,next)=>{try{res.json(await service.archive(parse(Id,req.params).id))}catch(e){next(e)}});
export default router;
