import { FormEvent,useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { KeyRound,ShieldCheck,UsersRound,UserPlus,ScrollText,RefreshCw } from 'lucide-react';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { useIdentity } from '../hooks/useIdentity';

interface Role {id:string;key:string;name:string;description:string|null;systemRole:boolean;permissions:string[];}
interface Permission {key:string;category:string;description:string;}
interface Team {id:string;name:string;description:string|null;members:Array<{id:string;displayName:string;email:string}>;}
interface User {id:string;email:string;displayName:string;status:'active'|'invited'|'disabled';roles:Array<{key:string;name:string}>;teams:Array<{id:string;name:string}>;permissions:string[];hasPassword:boolean;lastLoginAt:string|null;}
interface AuditEvent {id:string;actorName:string|null;actorEmail:string|null;action:string;entityType:string|null;entityId:string|null;organisationId:string|null;route:string;method:string;metadata:Record<string,unknown>;occurredAt:string;requestId:string;}

export default function Administration(){
  const identity=useIdentity();const [tab,setTab]=useState<'users'|'teams'|'roles'|'audit'>('users');
  if(!identity.isAdministrator&&!identity.can('audit.read'))return <State danger text="This account does not have access to administration."/>;
  return <div className="space-y-6"><header><div className="flex items-center gap-2 text-primary"><ShieldCheck className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.16em]">WI9 administration</span></div><h1 className="mt-2 text-3xl font-black tracking-tight">Users, permissions & audit</h1><p className="mt-1 text-sm text-muted-foreground">Named users, team membership, role-derived permissions and immutable accountability.</p></header><div className="flex flex-wrap gap-2">{(['users','teams','roles','audit'] as const).map((value)=><button key={value} onClick={()=>setTab(value)} className={`rounded-full border px-4 py-2 text-xs font-bold capitalize ${tab===value?'border-primary bg-primary text-primary-foreground':'bg-card hover:bg-muted'}`}>{value}</button>)}</div>{tab==='users'?<UsersPanel/>:tab==='teams'?<TeamsPanel/>:tab==='roles'?<RolesPanel/>:<AuditPanel/>}</div>;
}

function UsersPanel(){
  const client=useQueryClient();const users=useQuery<User[]>({queryKey:['admin-users'],queryFn:()=>api.get('/api/admin/users')});const roles=useQuery<{roles:Role[];permissions:Permission[]}>({queryKey:['admin-roles'],queryFn:()=>api.get('/api/admin/roles')});const teams=useQuery<Team[]>({queryKey:['admin-teams'],queryFn:()=>api.get('/api/admin/teams')});
  const [email,setEmail]=useState('');const [displayName,setDisplayName]=useState('');const [password,setPassword]=useState('');const [roleKey,setRoleKey]=useState('member');const [teamId,setTeamId]=useState('');const [message,setMessage]=useState('');
  const create=useMutation({mutationFn:()=>api.post('/api/admin/users',{email,displayName,password:password||undefined,roleKeys:[roleKey],teamIds:[teamId||teams.data?.[0]?.id].filter(Boolean)}),onSuccess:()=>{setEmail('');setDisplayName('');setPassword('');setMessage('User created.');client.invalidateQueries({queryKey:['admin-users']});client.invalidateQueries({queryKey:['admin-teams']});},onError:(error)=>setMessage((error as Error).message)});
  const update=useMutation({mutationFn:({id,body}:{id:string;body:unknown})=>api.patch(`/api/admin/users/${id}`,body),onSuccess:()=>{client.invalidateQueries({queryKey:['admin-users']});client.invalidateQueries({queryKey:['admin-teams']});},onError:(error)=>setMessage((error as Error).message)});
  const reset=useMutation({mutationFn:({id,password}:{id:string;password:string})=>api.post(`/api/admin/users/${id}/password`,{password}),onSuccess:()=>{setMessage('Password reset and active sessions revoked.');client.invalidateQueries({queryKey:['admin-users']});},onError:(error)=>setMessage((error as Error).message)});
  const submit=(event:FormEvent)=>{event.preventDefault();create.mutate();};
  if(users.isLoading||roles.isLoading||teams.isLoading)return <State text="Loading users and roles…"/>;
  if(users.isError||roles.isError||teams.isError)return <State danger text={(users.error||roles.error||teams.error as Error)?.message||'Administration data could not be loaded'}/>;
  return <div className="grid gap-6 xl:grid-cols-[380px_1fr]"><section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><UserPlus className="h-5 w-5 text-primary"/><h2 className="font-bold">Create user</h2></div><form onSubmit={submit} className="mt-4 space-y-3"><Field label="Display name"><input value={displayName} onChange={(event)=>setDisplayName(event.target.value)} required className="control"/></Field><Field label="Email"><input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} required className="control"/></Field><Field label="Initial password"><input type="password" value={password} onChange={(event)=>setPassword(event.target.value)} minLength={12} placeholder="Optional for local profile" className="control"/></Field><Field label="Role"><select value={roleKey} onChange={(event)=>setRoleKey(event.target.value)} className="control">{roles.data?.roles.map((role)=><option key={role.key} value={role.key}>{role.name}</option>)}</select></Field><Field label="Team"><select value={teamId} onChange={(event)=>setTeamId(event.target.value)} className="control"><option value="">Default team</option>{teams.data?.map((team)=><option key={team.id} value={team.id}>{team.name}</option>)}</select></Field><Button className="w-full" disabled={create.isPending}>Create user</Button></form>{message&&<p className="mt-3 rounded-lg border p-3 text-xs">{message}</p>}</section><section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-primary"/><h2 className="font-bold">User directory</h2></div><span className="text-xs text-muted-foreground">{users.data?.length} users</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-2">User</th><th>Status</th><th>Role</th><th>Team</th><th>Password</th><th>Actions</th></tr></thead><tbody className="divide-y">{users.data?.map((user)=><UserRow key={user.id} user={user} roles={roles.data!.roles} teams={teams.data!} update={(body)=>update.mutate({id:user.id,body})} reset={(newPassword)=>reset.mutate({id:user.id,password:newPassword})}/>)}</tbody></table></div></section></div>;
}
function UserRow({user,roles,teams,update,reset}:{user:User;roles:Role[];teams:Team[];update:(body:unknown)=>void;reset:(password:string)=>void}){const [newPassword,setNewPassword]=useState('');const role=user.roles[0]?.key||'member';const team=user.teams[0]?.id||'';return <tr><td className="py-4"><p className="font-bold">{user.displayName}</p><p className="text-xs text-muted-foreground">{user.email}</p></td><td><select value={user.status} onChange={(event)=>update({status:event.target.value})} className="small-control"><option value="active">Active</option><option value="invited">Invited</option><option value="disabled">Disabled</option></select></td><td><select value={role} onChange={(event)=>update({roleKeys:[event.target.value]})} className="small-control">{roles.map((item)=><option key={item.key} value={item.key}>{item.name}</option>)}</select></td><td><select value={team} onChange={(event)=>update({teamIds:[event.target.value]})} className="small-control">{teams.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${user.hasPassword?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{user.hasPassword?'Set':'Local only'}</span></td><td><div className="flex gap-2"><input value={newPassword} onChange={(event)=>setNewPassword(event.target.value)} placeholder="New password" type="password" className="h-8 w-32 rounded border px-2 text-xs"/><Button size="sm" variant="outline" disabled={newPassword.length<12} onClick={()=>{reset(newPassword);setNewPassword('');}}><KeyRound className="h-3.5 w-3.5"/></Button></div></td></tr>}

function TeamsPanel(){
  const client=useQueryClient();const teams=useQuery<Team[]>({queryKey:['admin-teams'],queryFn:()=>api.get('/api/admin/teams')});const users=useQuery<User[]>({queryKey:['admin-users'],queryFn:()=>api.get('/api/admin/users')});const [name,setName]=useState('');const [description,setDescription]=useState('');const [message,setMessage]=useState('');
  const create=useMutation({mutationFn:()=>api.post('/api/admin/teams',{name,description,userIds:[]}),onSuccess:()=>{setName('');setDescription('');setMessage('Team created.');client.invalidateQueries({queryKey:['admin-teams']});},onError:(error)=>setMessage((error as Error).message)});
  const update=useMutation({mutationFn:({id,userIds}:{id:string;userIds:string[]})=>api.patch(`/api/admin/teams/${id}`,{userIds}),onSuccess:()=>{client.invalidateQueries({queryKey:['admin-teams']});client.invalidateQueries({queryKey:['admin-users']});},onError:(error)=>setMessage((error as Error).message)});
  if(teams.isLoading||users.isLoading)return <State text="Loading teams…"/>;
  return <div className="grid gap-6 xl:grid-cols-[340px_1fr]"><section className="rounded-xl border bg-card p-5"><h2 className="font-bold">Create team</h2><div className="mt-4 space-y-3"><Field label="Name"><input value={name} onChange={(event)=>setName(event.target.value)} className="control"/></Field><Field label="Description"><textarea value={description} onChange={(event)=>setDescription(event.target.value)} className="control min-h-24 py-2"/></Field><Button disabled={!name.trim()||create.isPending} onClick={()=>create.mutate()}>Create team</Button>{message&&<p className="text-xs">{message}</p>}</div></section><section className="space-y-4">{teams.data?.map((team)=><div key={team.id} className="rounded-xl border bg-card p-5"><div><p className="font-bold">{team.name}</p><p className="text-xs text-muted-foreground">{team.description||'No description'} · {team.members.length} members</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{users.data?.map((user)=>{const selected=team.members.some((member)=>member.id===user.id);return <label key={user.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected} onChange={(event)=>{const current=team.members.map((member)=>member.id);const next=event.target.checked?[...new Set([...current,user.id])]:current.filter((id)=>id!==user.id);update.mutate({id:team.id,userIds:next});}}/><span><strong>{user.displayName}</strong><span className="block text-xs text-muted-foreground">{user.email}</span></span></label>})}</div></div>)}</section></div>;
}

function RolesPanel(){const data=useQuery<{roles:Role[];permissions:Permission[]}>({queryKey:['admin-roles'],queryFn:()=>api.get('/api/admin/roles')});const categories=useMemo(()=>[...new Set(data.data?.permissions.map((item)=>item.category)||[])],[data.data]);if(data.isLoading)return <State text="Loading role matrix…"/>;return <section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-bold">Role and permission matrix</h2><p className="mt-1 text-xs text-muted-foreground">System roles are intentionally fixed in this pass. Assignments are mutable; the permission baseline is deterministic.</p><div className="mt-5 overflow-x-auto"><table className="min-w-[900px] w-full text-xs"><thead><tr><th className="pb-3 text-left">Permission</th>{data.data?.roles.map((role)=><th key={role.id} className="px-3 pb-3 text-center">{role.name}</th>)}</tr></thead><tbody>{categories.map((category)=><FragmentRows key={category} category={category} permissions={data.data!.permissions.filter((item)=>item.category===category)} roles={data.data!.roles}/>)}</tbody></table></div></section>}
function FragmentRows({category,permissions,roles}:{category:string;permissions:Permission[];roles:Role[]}){return <>{<tr className="bg-muted/50"><td colSpan={roles.length+1} className="px-2 py-2 font-bold uppercase tracking-wider text-muted-foreground">{category}</td></tr>}{permissions.map((permission)=><tr key={permission.key} className="border-b"><td className="py-3"><p className="font-bold">{permission.key}</p><p className="text-[10px] text-muted-foreground">{permission.description}</p></td>{roles.map((role)=><td key={role.id} className="text-center">{role.permissions.includes(permission.key)?<span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-emerald-100 font-bold text-emerald-800">✓</span>:<span className="text-muted-foreground">—</span>}</td>)}</tr>)}</>}

function AuditPanel(){const [action,setAction]=useState('');const [entityType,setEntityType]=useState('');const query=new URLSearchParams();if(action)query.set('action',action);if(entityType)query.set('entityType',entityType);query.set('limit','200');const audit=useQuery<{items:AuditEvent[];total:number}>({queryKey:['admin-audit',action,entityType],queryFn:()=>api.get(`/api/admin/audit?${query}`)});return <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-2"><ScrollText className="h-5 w-5 text-primary"/><div><h2 className="font-bold">Immutable audit log</h2><p className="text-xs text-muted-foreground">Successful mutations, exports and authentication events.</p></div></div><div className="flex gap-2"><input value={action} onChange={(event)=>setAction(event.target.value)} placeholder="Action" className="h-9 rounded-md border px-3 text-sm"/><input value={entityType} onChange={(event)=>setEntityType(event.target.value)} placeholder="Entity type" className="h-9 rounded-md border px-3 text-sm"/><Button variant="outline" size="sm" onClick={()=>audit.refetch()}><RefreshCw className="h-4 w-4"/></Button></div></div>{audit.isLoading?<State text="Reading audit events…"/>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-xs"><thead className="text-left uppercase tracking-wider text-muted-foreground"><tr><th className="pb-2">Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Route</th><th>Request</th></tr></thead><tbody className="divide-y">{audit.data?.items.map((event)=><tr key={event.id}><td className="py-3 whitespace-nowrap">{new Date(event.occurredAt).toLocaleString()}</td><td><p className="font-bold">{event.actorName||'System'}</p><p className="text-[10px] text-muted-foreground">{event.actorEmail}</p></td><td className="font-mono">{event.action}</td><td>{event.entityType||'—'}{event.entityId&&<span className="block max-w-32 truncate font-mono text-[10px] text-muted-foreground">{event.entityId}</span>}</td><td><span className="font-bold">{event.method}</span> {event.route}</td><td className="max-w-32 truncate font-mono text-[10px]">{event.requestId}</td></tr>)}</tbody></table></div>}</section>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-bold text-muted-foreground">{label}<div className="mt-1">{children}</div></label>}
function State({text,danger=false}:{text:string;danger?:boolean}){return <div className={`rounded-xl border bg-card p-10 text-center text-sm ${danger?'text-destructive':'text-muted-foreground'}`}>{text}</div>}
