import { type ReactNode,useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, Copy, FlaskConical, Play, Plus, Power, RotateCcw, Workflow } from 'lucide-react';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';

interface Policy { maxRunsPerHour:number;timeoutMs:number;maxDepth:number;dryRun:boolean; }
interface WorkflowDefinition { id:string;name:string;description:string|null;enabled:boolean;version:number;triggerType:string;conditions:Record<string,unknown>;actions:Array<{type:string;title?:string;subject?:string}>;policy:Policy; }
interface WorkflowRun { id:string;workflowName:string;workflowDefinitionId:string;status:string;sourceType:string;sourceId:string;startedAt:string;completedAt:string|null;actions:Array<{actionType:string;status:string;failureDetails?:string|null}>; }
interface WorkflowTemplate { key:string;name:string;description:string|null;triggerType:string;actions:Array<{type:string}>; }
interface OrganisationDirectory { items:Array<{id:string;name:string}>; }

export default function Automation(){
  const client=useQueryClient();const [showCreate,setShowCreate]=useState(false);const [error,setError]=useState('');
  const definitions=useQuery<WorkflowDefinition[]>({queryKey:['workflow-studio'],queryFn:()=>api.get('/api/workflow-studio')});
  const templates=useQuery<WorkflowTemplate[]>({queryKey:['workflow-templates'],queryFn:()=>api.get('/api/workflow-templates')});
  const runs=useQuery<WorkflowRun[]>({queryKey:['workflow-studio-runs'],queryFn:()=>api.get('/api/workflow-studio/runs?limit=100')});
  const refresh=()=>{client.invalidateQueries({queryKey:['workflow-studio']});client.invalidateQueries({queryKey:['workflow-studio-runs']});client.invalidateQueries({queryKey:['work']});client.invalidateQueries({queryKey:['email-drafts']});};
  const action=useMutation({mutationFn:({path,body}:{path:string;body?:unknown})=>api.post(path,body??{}),onSuccess:refresh,onError:(value:Error)=>setError(value.message)});
  return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-extrabold tracking-tight">Workflow studio</h1><p className="mt-1 text-sm text-muted-foreground">Declarative, allow-listed automation with dry-runs, limits, cycle protection and auditable retries.</p></div><Button onClick={()=>setShowCreate(true)}><Plus className="mr-2 h-4 w-4"/>Create workflow</Button></header>{error&&<div className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
    <section className="space-y-3"><h2 className="font-bold">Templates</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{templates.data?.map((template)=><article key={template.key} className="rounded-xl border bg-card p-4 shadow-sm"><h3 className="font-bold">{template.name}</h3><p className="mt-2 text-xs text-muted-foreground">{template.description}</p><p className="mt-3 text-[10px] font-bold uppercase text-muted-foreground">{template.triggerType} · {template.actions.length} actions</p><Button className="mt-4" size="sm" variant="outline" onClick={()=>action.mutate({path:'/api/workflow-studio/from-template',body:{key:template.key}})}>Use template</Button></article>)}</div></section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><div className="space-y-3"><h2 className="font-bold">Definitions</h2>{definitions.isLoading?<State text="Loading workflows…"/>:!definitions.data?.length?<State text="No workflows defined."/>:definitions.data.map((workflow)=><article key={workflow.id} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Workflow className="h-5 w-5 text-primary"/><h3 className="font-bold">{workflow.name}</h3><span className={`rounded px-2 py-0.5 text-[10px] font-bold uppercase ${workflow.enabled?'bg-emerald-100 text-emerald-700':'bg-muted text-muted-foreground'}`}>{workflow.enabled?'enabled':'disabled'}</span></div><p className="mt-2 text-sm text-muted-foreground">{workflow.description||'No description'}</p><p className="mt-3 text-xs text-muted-foreground">Trigger: {workflow.triggerType} · {workflow.actions.length} action(s) · v{workflow.version}</p><p className="mt-1 text-xs text-muted-foreground">Limit {workflow.policy.maxRunsPerHour}/hour · timeout {workflow.policy.timeoutMs}ms · depth {workflow.policy.maxDepth}{workflow.policy.dryRun?' · policy dry-run':''}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>action.mutate({path:`/api/workflow-studio/${workflow.id}/enable`,body:{enabled:!workflow.enabled}})}><Power className="mr-1 h-4 w-4"/>{workflow.enabled?'Disable':'Enable'}</Button><Button size="sm" variant="outline" onClick={()=>action.mutate({path:`/api/workflow-studio/${workflow.id}/dry-run`,body:{context:{organisationId:'20000000-0000-4000-8000-000000000001',accountId:'60000000-0000-4000-8000-000000000001',subject:'Acme dry run'}}})}><FlaskConical className="mr-1 h-4 w-4"/>Dry run</Button><Button size="sm" variant="outline" onClick={()=>{const name=window.prompt('Name for duplicate',`${workflow.name} copy`);if(name?.trim())action.mutate({path:`/api/workflow-studio/${workflow.id}/duplicate`,body:{name}});}}><Copy className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={()=>{if(window.confirm(`Archive ${workflow.name}?`))action.mutate({path:`/api/workflow-studio/${workflow.id}/archive`});}}><Archive className="h-4 w-4"/></Button></div></div></article>)}</div>
      <div className="space-y-3"><h2 className="font-bold">Recent runs</h2>{runs.isLoading?<State text="Loading runs…"/>:!runs.data?.length?<State text="No workflow executions."/>:runs.data.slice(0,30).map((run)=><article key={run.id} className="rounded-xl border bg-card p-4 shadow-sm"><div className="flex justify-between gap-3"><div><h3 className="text-sm font-bold">{run.workflowName}</h3><p className="text-xs text-muted-foreground">{new Date(run.startedAt).toLocaleString()} · {run.actions.length} action(s)</p></div><span className={`rounded px-2 py-1 text-[10px] font-bold uppercase ${run.status==='succeeded'?'bg-emerald-100 text-emerald-700':run.status==='failed'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{run.status}</span></div>{['failed','partially_failed'].includes(run.status)&&<Button className="mt-3" size="sm" variant="outline" onClick={()=>action.mutate({path:`/api/workflow-runs/${run.id}/retry`})}><RotateCcw className="mr-1 h-4 w-4"/>Safe retry</Button>}</article>)}</div></section>
    {showCreate&&<CreateDialog templates={templates.data??[]} onClose={()=>setShowCreate(false)} onCreated={()=>{setShowCreate(false);refresh();}}/>}
  </div>;
}

function CreateDialog({templates,onClose,onCreated}:{templates:WorkflowTemplate[];onClose:()=>void;onCreated:()=>void}){const [templateKey,setTemplateKey]=useState(templates[0]?.key??'');const [name,setName]=useState('');const [error,setError]=useState('');const create=useMutation({mutationFn:()=>templateKey?api.post('/api/workflow-studio/from-template',{key:templateKey,name:name||undefined}):api.post('/api/workflow-studio',{name,description:null,enabled:false,triggerType:'manual',conditions:{},actions:[{type:'create_task',title:'Workflow task',priority:'normal'}]}),onSuccess:onCreated,onError:(value:Error)=>setError(value.message)});return <Modal title="Create workflow" onClose={onClose}><form className="space-y-3" onSubmit={(event)=>{event.preventDefault();create.mutate();}}><select value={templateKey} onChange={(event)=>setTemplateKey(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Blank allow-listed workflow</option>{templates.map((template)=><option key={template.key} value={template.key}>{template.name}</option>)}</select><Input required={!templateKey} value={name} onChange={(event)=>setName(event.target.value)} placeholder={templateKey?'Optional custom name':'Workflow name'}/><p className="rounded-lg bg-muted p-3 text-xs text-muted-foreground">Workflows may create tasks, reminders, activities and reviewable email drafts. They cannot send external email.</p>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={create.isPending}>Create</Button></div></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-xl border bg-card p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}
function State({text}:{text:string}){return <div className="rounded-xl border bg-card p-8 text-center text-sm text-muted-foreground">{text}</div>}
