import { useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { CheckCircle2,FileSpreadsheet,Upload,AlertTriangle } from 'lucide-react';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { useIdentity } from '../hooks/useIdentity';

interface ImportField {key:string;label:string;required:boolean;kind:'standard'|'custom'|'connection';}
interface ImportTarget {key:string;label:string;definitionId:string|null;fields:ImportField[];}
interface ImportIssue {row:number;field:string;message:string;}
interface Preview {
  target:ImportTarget;headers:string[];mapping:Record<string,string>;rowCount:number;validRowCount:number;
  issues:ImportIssue[];previewRows:Array<Record<string,string>>;
}
interface ImportResult {importedCount:number;rejectedCount:number;issues:ImportIssue[];}
interface ImportHistory {id:string;targetKey:string;filename:string;importedCount:number;rejectedCount:number;createdAt:string;}

export default function BulkImport(){
  const identity=useIdentity();const client=useQueryClient();
  const targets=useQuery<ImportTarget[]>({queryKey:['bulk-import-targets'],queryFn:()=>api.get('/api/bulk-import/targets')});
  const history=useQuery<ImportHistory[]>({queryKey:['bulk-import-history'],queryFn:()=>api.get('/api/bulk-import/history')});
  const [targetKey,setTargetKey]=useState('customers');const [filename,setFilename]=useState('');const [csvData,setCsvData]=useState('');const [preview,setPreview]=useState<Preview|null>(null);const [mapping,setMapping]=useState<Record<string,string>>({});const [validatedMapping,setValidatedMapping]=useState<Record<string,string>>({});const [result,setResult]=useState<ImportResult|null>(null);const [error,setError]=useState('');
  const selected=targets.data?.find((target)=>target.key===targetKey);
  const previewMutation=useMutation({mutationFn:()=>api.post<Preview>('/api/bulk-import/preview',{targetKey,filename,csvData,mapping}),onSuccess:(value)=>{setPreview(value);setMapping(value.mapping);setValidatedMapping(value.mapping);setResult(null);setError('');},onError:(value:Error)=>setError(value.message)});
  const execute=useMutation({mutationFn:()=>api.post<ImportResult>('/api/bulk-import/execute',{targetKey,filename,csvData,mapping}),onSuccess:async(value)=>{setResult(value);await Promise.all([client.invalidateQueries({queryKey:['bulk-import-history']}),client.invalidateQueries({queryKey:['workspace-model']}),client.invalidateQueries({queryKey:['customers']})]);},onError:(value:Error)=>setError(value.message)});
  const mappedRequired=useMemo(()=>selected?.fields.filter((field)=>field.required&&!mapping[field.key])??[],[selected,mapping]);
  const mappingIsCurrent=JSON.stringify(mapping)===JSON.stringify(validatedMapping);
  if(!identity.can('data.import'))return <State message="This account cannot import CRM data."/>;
  return <div className="space-y-6">
    <header><div className="flex items-center gap-2 text-primary"><Upload className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-[0.16em]">Bulk import</span></div><h1 className="mt-2 text-3xl font-black tracking-tight">Bring existing data into the workspace</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Choose what the rows represent, upload a CSV, match its columns, then review every rejection before importing. Nothing is written during preview.</p></header>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
      <main className="space-y-5">
        <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><Field label="What are you importing?"><select className="control" value={targetKey} onChange={(event)=>{setTargetKey(event.target.value);setPreview(null);setMapping({});setResult(null);}}>{targets.data?.map((target)=><option key={target.key} value={target.key}>{target.label}</option>)}</select></Field><Field label="CSV file"><label className="flex h-10 cursor-pointer items-center gap-2 rounded-md border bg-background px-3 text-sm"><FileSpreadsheet className="h-4 w-4 text-primary"/><span className="min-w-0 flex-1 truncate">{filename||'Choose a CSV file'}</span><input className="sr-only" type="file" accept=".csv,text/csv" onChange={async(event)=>{const file=event.target.files?.[0];if(!file)return;setFilename(file.name);setCsvData(await file.text());setPreview(null);setMapping({});setResult(null);}}/></label></Field></div><Button className="mt-4" disabled={!csvData||previewMutation.isPending} onClick={()=>previewMutation.mutate()}>{previewMutation.isPending?'Reading file…':'Preview and match columns'}</Button>{error&&<p className="mt-4 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}</section>
        {preview&&<section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-black">Match CSV columns</h2><p className="mt-1 text-sm text-muted-foreground">Tell the CRM where each piece of information belongs. Unneeded columns can remain unused.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{preview.rowCount} rows</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{selected?.fields.map((field)=><Field key={field.key} label={`${field.label}${field.required?' *':''}`}><select className="control" value={mapping[field.key]??''} onChange={(event)=>{setMapping((current)=>({...current,[field.key]:event.target.value}));setResult(null);}}><option value="">Do not import</option>{preview.headers.map((header)=><option key={header} value={header}>{header}</option>)}</select></Field>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><Button variant="outline" onClick={()=>previewMutation.mutate()}>Refresh validation</Button><Button disabled={mappedRequired.length>0||!mappingIsCurrent||execute.isPending} onClick={()=>execute.mutate()}>{execute.isPending?'Importing…':`Import ${preview.validRowCount} valid rows`}</Button>{mappedRequired.length>0?<p className="text-xs font-bold text-destructive">Map: {mappedRequired.map((field)=>field.label).join(', ')}</p>:!mappingIsCurrent&&<p className="text-xs font-bold text-amber-700">Refresh validation after changing a column match.</p>}</div></section>}
        {preview&&<section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-black">Validation</h2><p className="mt-1 text-xs text-muted-foreground">{preview.validRowCount} ready · {preview.rowCount-preview.validRowCount} need attention</p></div>{preview.issues.length?<AlertTriangle className="h-5 w-5 text-amber-600"/>:<CheckCircle2 className="h-5 w-5 text-emerald-600"/>}</div>{preview.issues.length?<IssueTable issues={preview.issues}/>:<p className="p-5 text-sm text-emerald-800">All rows passed validation.</p>}</section>}
        {result&&<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-950"><div className="flex gap-3"><CheckCircle2 className="h-6 w-6 shrink-0"/><div><h2 className="font-black">Import complete</h2><p className="mt-1 text-sm">{result.importedCount} rows imported. {result.rejectedCount} rejected.</p>{result.issues.length>0&&<p className="mt-2 text-xs">Rejected rows remain unchanged in the CSV. Correct them and import again.</p>}</div></div></section>}
      </main>
      <aside className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-black">Recent imports</h2><p className="mt-1 text-xs text-muted-foreground">A local audit of completed import attempts.</p><div className="mt-4 space-y-3">{history.data?.map((item)=><div key={item.id} className="rounded-xl border p-3"><p className="truncate text-sm font-bold">{item.filename}</p><p className="mt-1 text-xs text-muted-foreground">{item.importedCount} imported · {item.rejectedCount} rejected</p><p className="mt-1 text-[10px] text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></div>)}</div>{!history.data?.length&&<p className="mt-4 rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No bulk imports yet.</p>}</aside>
    </div>
  </div>;
}
function IssueTable({issues}:{issues:ImportIssue[]}){return <div className="max-h-80 overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-muted"><tr><th className="p-3">Row</th><th className="p-3">Field</th><th className="p-3">Problem</th></tr></thead><tbody className="divide-y">{issues.map((issue,index)=><tr key={`${issue.row}:${issue.field}:${index}`}><td className="p-3 font-mono">{issue.row}</td><td className="p-3 font-bold">{issue.field}</td><td className="p-3 text-muted-foreground">{issue.message}</td></tr>)}</tbody></table></div>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-bold text-muted-foreground">{label}<div className="mt-1.5">{children}</div></label>;}
function State({message}:{message:string}){return <div className="rounded-2xl border bg-card p-10 text-center text-sm text-muted-foreground">{message}</div>;}
