import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, FileText, Mail, MessageSquare, Phone, Plus, Send, Users } from 'lucide-react';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';

interface OrganisationDirectory { items:Array<{id:string;name:string}>; }
interface Account { id:string;kind:'email'|'calendar';name:string;username:string;enabled:boolean; }
interface DocumentItem { id:string;title:string;currentFilename:string; }
interface Communication { id:string;organisationId:string;organisationName:string;channel:string;direction:string;subject:string|null;body:string;occurredAt:string;status:string; }
interface Draft { id:string;accountName:string;organisationId:string|null;to:Array<{address:string}>;subject:string;bodyText:string;status:string;lastError:string|null;updatedAt:string;documents:Array<{documentId:string;title:string}>; }
interface CalendarEvent { id:string;title:string;startsAt:string;endsAt:string;organisationName:string|null;cancelled:boolean;matchStatus:string; }

type View='timeline'|'drafts'|'meetings';

export default function Communications(){
  const client=useQueryClient();
  const [organisationId,setOrganisationId]=useState('');
  const [channel,setChannel]=useState('');
  const [view,setView]=useState<View>('timeline');
  const [showCreate,setShowCreate]=useState(false);
  const organisations=useQuery<OrganisationDirectory>({queryKey:['workspace-organisations','communications'],queryFn:()=>api.get('/api/workspace/organisations?limit=200&offset=0')});
  const accounts=useQuery<Account[]>({queryKey:['communication-accounts'],queryFn:()=>api.get('/api/communication-accounts')});
  const documents=useQuery<DocumentItem[]>({queryKey:['documents','communications'],queryFn:()=>api.get('/api/documents?includeArchived=false')});
  const communications=useQuery<Communication[]>({queryKey:['communications',organisationId,channel],queryFn:()=>api.get(`/api/communications?limit=300${organisationId?`&organisationId=${encodeURIComponent(organisationId)}`:''}${channel?`&channel=${encodeURIComponent(channel)}`:''}`)});
  const drafts=useQuery<Draft[]>({queryKey:['email-drafts',organisationId],queryFn:()=>api.get(`/api/email-drafts?limit=300${organisationId?`&organisationId=${encodeURIComponent(organisationId)}`:''}`)});
  const meetings=useQuery<CalendarEvent[]>({queryKey:['calendar-events','hub',organisationId],queryFn:()=>api.get(`/api/calendar-events?limit=300${organisationId?`&organisationId=${encodeURIComponent(organisationId)}`:''}`)});
  const refresh=()=>{client.invalidateQueries({queryKey:['communications']});client.invalidateQueries({queryKey:['email-drafts']});client.invalidateQueries({queryKey:['email-threads']});client.invalidateQueries({queryKey:['calendar-events']});client.invalidateQueries({queryKey:['search']});};
  const send=useMutation({mutationFn:(id:string)=>api.post(`/api/email-drafts/${id}/send`,{explicitConfirmation:true}),onSuccess:refresh});
  const discard=useMutation({mutationFn:(id:string)=>api.post(`/api/email-drafts/${id}/discard`,{}),onSuccess:refresh});
  const complete=useMutation({mutationFn:({id,notes}:{id:string;notes:string})=>api.post(`/api/calendar-events/${id}/complete`,{notes}),onSuccess:refresh});
  const activeEmailAccounts=useMemo(()=>accounts.data?.filter((item)=>item.kind==='email'&&item.enabled)??[],[accounts.data]);

  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-extrabold tracking-tight">Communications hub</h1><p className="mt-1 text-sm text-muted-foreground">Email, meetings, documents and follow-up work in one organisation-centred workspace.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setShowCreate(true)}><MessageSquare className="mr-2 h-4 w-4"/>Log communication</Button><Button onClick={()=>setShowCreate(true)}><Plus className="mr-2 h-4 w-4"/>Compose</Button></div></header>
    <div className="flex flex-wrap items-center gap-3 rounded-xl border bg-card p-4 shadow-sm"><select value={organisationId} onChange={(event)=>setOrganisationId(event.target.value)} className="h-10 min-w-64 rounded-md border bg-background px-3 text-sm"><option value="">All organisations</option>{organisations.data?.items.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select>{view==='timeline'&&<select value={channel} onChange={(event)=>setChannel(event.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All channels</option>{['email','meeting','phone','sms','whatsapp','teams','slack','voip','other'].map((value)=><option key={value}>{value}</option>)}</select>}<div className="ml-auto flex rounded-lg border bg-muted/30 p-1">{(['timeline','drafts','meetings'] as View[]).map((item)=><button key={item} onClick={()=>setView(item)} className={`rounded-md px-3 py-1.5 text-xs font-bold capitalize ${view===item?'bg-background shadow-sm':'text-muted-foreground'}`}>{item}</button>)}</div></div>
    {view==='timeline'&&<Timeline items={communications.data??[]} loading={communications.isLoading} error={communications.error as Error|null}/>} 
    {view==='drafts'&&<Drafts items={drafts.data??[]} loading={drafts.isLoading} onSend={(id)=>send.mutate(id)} onDiscard={(id)=>discard.mutate(id)} sending={send.isPending}/>} 
    {view==='meetings'&&<Meetings items={meetings.data??[]} loading={meetings.isLoading} onComplete={(id)=>{const notes=window.prompt('Meeting outcome and notes');if(notes?.trim())complete.mutate({id,notes});}}/>}
    {showCreate&&<ComposeDialog organisations={organisations.data?.items??[]} accounts={activeEmailAccounts} documents={documents.data??[]} initialOrganisationId={organisationId} onClose={()=>setShowCreate(false)} onCreated={()=>{setShowCreate(false);setView('drafts');refresh();}}/>}
  </div>;
}

function Timeline({items,loading,error}:{items:Communication[];loading:boolean;error:Error|null}){if(loading)return <State text="Loading communications…"/>;if(error)return <State danger text={error.message}/>;if(!items.length)return <State text="No communication records match this view."/>;return <div className="space-y-3">{items.map((item)=><article key={item.id} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">{icon(item.channel)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded bg-muted px-2 py-0.5 text-[10px] font-bold uppercase">{item.channel}</span><h2 className="mt-2 font-bold">{item.subject||`${item.channel} communication`}</h2></div><time className="text-xs text-muted-foreground">{new Date(item.occurredAt).toLocaleString()}</time></div><p className="mt-2 whitespace-pre-wrap text-sm text-foreground/80">{item.body}</p><p className="mt-3 text-xs text-muted-foreground">{item.organisationName} · {item.direction} · {item.status}</p></div></div></article>)}</div>}
function Drafts({items,loading,onSend,onDiscard,sending}:{items:Draft[];loading:boolean;onSend:(id:string)=>void;onDiscard:(id:string)=>void;sending:boolean}){if(loading)return <State text="Loading drafts…"/>;if(!items.length)return <State text="No drafts."/>;return <div className="space-y-3">{items.map((item)=><article key={item.id} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-primary"/><span className="rounded bg-muted px-2 py-0.5 text-[10px] font-bold uppercase">{item.status}</span></div><h2 className="mt-2 font-bold">{item.subject||'(No subject)'}</h2><p className="mt-1 text-xs text-muted-foreground">To {item.to.map((value)=>value.address).join(', ')||'no recipients'} · {item.accountName}</p></div><div className="flex gap-2">{['draft','failed'].includes(item.status)&&<><Button size="sm" variant="outline" onClick={()=>onDiscard(item.id)}>Discard</Button><Button size="sm" disabled={sending} onClick={()=>{if(window.confirm('Send this email now? This action transmits it through the configured SMTP account.'))onSend(item.id);}}><Send className="mr-1 h-4 w-4"/>Send</Button></>}</div></div><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm text-foreground/75">{item.bodyText||'(No body)'}</p>{item.documents.length>0&&<p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><FileText className="h-3.5 w-3.5"/>{item.documents.map((value)=>value.title).join(', ')}</p>}{item.lastError&&<p className="mt-3 rounded bg-red-50 p-2 text-xs text-red-700">{item.lastError}</p>}</article>)}</div>}
function Meetings({items,loading,onComplete}:{items:CalendarEvent[];loading:boolean;onComplete:(id:string)=>void}){if(loading)return <State text="Loading meetings…"/>;if(!items.length)return <State text="No meetings."/>;return <div className="grid gap-4 lg:grid-cols-2">{items.map((item)=><article key={item.id} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-primary"/><span className="rounded bg-muted px-2 py-0.5 text-[10px] font-bold uppercase">{item.cancelled?'cancelled':item.matchStatus}</span></div><h2 className="mt-2 font-bold">{item.title}</h2><p className="mt-1 text-xs text-muted-foreground">{item.organisationName||'Unmatched'} · {new Date(item.startsAt).toLocaleString()}</p></div>{!item.cancelled&&new Date(item.endsAt)<=new Date()&&<Button size="sm" variant="outline" onClick={()=>onComplete(item.id)}>Complete</Button>}</div></article>)}</div>}

function ComposeDialog({organisations,accounts,documents,initialOrganisationId,onClose,onCreated}:{organisations:Array<{id:string;name:string}>;accounts:Account[];documents:DocumentItem[];initialOrganisationId:string;onClose:()=>void;onCreated:()=>void}){
  const [accountId,setAccountId]=useState(accounts[0]?.id??'');const [organisationId,setOrganisationId]=useState(initialOrganisationId);const [to,setTo]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [documentIds,setDocumentIds]=useState<string[]>([]);const [error,setError]=useState('');
  const create=useMutation({mutationFn:()=>api.post('/api/email-drafts',{accountId,organisationId:organisationId||null,to:to.split(/[;,]/).map((value)=>value.trim()).filter(Boolean).map((address)=>({address})),cc:[],bcc:[],subject,bodyText:body,documentIds}),onSuccess:onCreated,onError:(value:Error)=>setError(value.message)});
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-2xl rounded-xl border bg-card p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Compose email draft</h2><p className="text-xs text-muted-foreground">Saving creates a local draft. Sending always requires a separate explicit confirmation.</p></div><button onClick={onClose} aria-label="Close compose dialog">×</button></div><form className="mt-5 space-y-3" onSubmit={(event)=>{event.preventDefault();create.mutate();}}><div className="grid gap-3 sm:grid-cols-2"><select required value={accountId} onChange={(event)=>setAccountId(event.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Select email account</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.name} · {item.username}</option>)}</select><select value={organisationId} onChange={(event)=>setOrganisationId(event.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">No organisation link</option>{organisations.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select></div><Input required placeholder="Recipients, separated by commas" value={to} onChange={(event)=>setTo(event.target.value)}/><Input required placeholder="Subject" value={subject} onChange={(event)=>setSubject(event.target.value)}/><textarea required className="min-h-48 w-full rounded-md border bg-background p-3 text-sm" placeholder="Message" value={body} onChange={(event)=>setBody(event.target.value)}/><div><p className="mb-2 text-xs font-bold uppercase text-muted-foreground">CRM documents</p><div className="max-h-32 space-y-1 overflow-y-auto rounded-md border p-2">{documents.map((item)=><label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={documentIds.includes(item.id)} onChange={(event)=>setDocumentIds((current)=>event.target.checked?[...current,item.id]:current.filter((id)=>id!==item.id))}/>{item.title} <span className="text-xs text-muted-foreground">{item.currentFilename}</span></label>)}{!documents.length&&<p className="text-xs text-muted-foreground">No documents available.</p>}</div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={!accountId||!to.trim()||!subject.trim()||!body.trim()||create.isPending}>Save draft</Button></div></form></div></div>}
function icon(channel:string){if(channel==='email')return <Mail className="h-5 w-5"/>;if(channel==='meeting'||channel==='teams')return <Users className="h-5 w-5"/>;if(channel==='phone'||channel==='voip')return <Phone className="h-5 w-5"/>;return <MessageSquare className="h-5 w-5"/>;}
function State({text,danger=false}:{text:string;danger?:boolean}){return <div className={`rounded-xl border bg-card p-10 text-center text-sm ${danger?'text-destructive':'text-muted-foreground'}`}>{text}</div>}
