import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { AlertTriangle, BriefcaseBusiness, Building2, CalendarClock, CircleDollarSign, MessageSquare, WalletCards } from 'lucide-react';
import type { DashboardOperationalSummary } from 'shared';
import { api } from '../lib/api';

export default function Dashboard() {
  const metrics = useQuery<DashboardOperationalSummary>({
    queryKey: ['workspace-dashboard'],
    queryFn: () => api.get('/api/workspace/dashboard'),
    refetchInterval: 30_000,
  });
  if (metrics.isLoading) return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <div key={i} className="h-28 animate-pulse rounded-xl bg-muted"/>)}</div>;
  if (metrics.isError || !metrics.data) return <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-8 text-destructive">{(metrics.error as Error)?.message || 'Dashboard could not be loaded'}</div>;
  const data = metrics.data;
  const money = (cents: number) => new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR' }).format(cents / 100);
  return <div className="space-y-7">
    <div><h1 className="text-3xl font-extrabold tracking-tight">Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Operational signals from persisted CRM and financial records.</p></div>
    <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
      <Card label="Active clients" value={data.activeClientOrganisations} icon={Building2}/><Card label="Active engagements" value={data.activeEngagements} icon={BriefcaseBusiness}/><Card label="Overdue follow-ups" value={data.overdueFollowUps} icon={AlertTriangle} danger/><Card label="Due today" value={data.dueTodayFollowUps} icon={CalendarClock}/><Card label="Collected this month" value={money(data.collectedRevenueCents)} icon={CircleDollarSign}/><Card label="Outstanding invoices" value={money(data.outstandingCents)} icon={WalletCards}/>
    </div>
    <div className="grid gap-6 xl:grid-cols-3">
      <section className="rounded-xl border bg-card p-6 shadow-sm xl:col-span-2"><div className="flex justify-between"><div><h2 className="font-bold">Needs attention</h2><p className="text-xs text-muted-foreground">Open commitments, quiet accounts and engagements ending soon.</p></div><Link to="/follow-ups" className="text-xs font-semibold text-primary">Open follow-up queue</Link></div><div className="mt-5 grid gap-5 lg:grid-cols-3"><Attention title="Follow-ups" empty="No open follow-ups" items={data.needsAttention.followUps.map((item) => ({ id: item.activityId, title: item.organisationName, detail: `${item.status} · ${item.followUpDate}`, route: `/organisations/${item.organisationId}?tab=timeline&activityId=${item.activityId}` }))}/><Attention title={`No activity in ${data.staleAfterDays}+ days`} empty="No stale active clients" items={data.needsAttention.staleOrganisations.map((item) => ({ id: item.id, title: item.name, detail: item.lastActivityAt ? `Last activity ${new Date(item.lastActivityAt).toLocaleDateString()}` : 'No activity recorded', route: `/organisations/${item.id}` }))}/><Attention title="Engagements ending soon" empty="No engagements ending soon" items={data.needsAttention.engagementsEndingSoon.map((item) => ({ id: item.id, title: item.name, detail: `${item.organisationName} · ${item.endDate}`, route: `/organisations/${item.organisationId}?tab=engagements&engagementId=${item.id}` }))}/></div></section>
      <section className="rounded-xl border bg-card p-6 shadow-sm"><h2 className="font-bold">Recently updated organisations</h2><div className="mt-4 divide-y">{data.recentlyUpdatedOrganisations.map((organisation) => <Link key={organisation.id} to={`/organisations/${organisation.id}`} className="block py-3 hover:text-primary"><p className="text-sm font-bold">{organisation.name}</p><p className="text-xs text-muted-foreground">{organisation.status.replace('_',' ')} · {new Date(organisation.updatedAt).toLocaleDateString()}</p></Link>)}</div></section>
    </div>
    <section className="rounded-xl border bg-card p-6 shadow-sm"><div><h2 className="font-bold">Recent CRM activity</h2><p className="text-xs text-muted-foreground">Canonical activities only; no simulated trend data.</p></div>{data.recentActivities.length === 0 ? <div className="mt-5 rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No activity recorded.</div> : <div className="mt-4 divide-y">{data.recentActivities.map((activity) => <Link key={activity.id} to={`/organisations/${activity.organisationId}?tab=timeline&activityId=${activity.id}`} className="flex gap-3 py-4 hover:bg-muted/30"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><MessageSquare className="h-4 w-4"/></div><div className="min-w-0"><p className="text-sm font-bold">{activity.organisationName} · <span className="capitalize">{activity.type}</span></p><p className="truncate text-xs text-muted-foreground">{activity.body}</p><p className="mt-1 text-[10px] text-muted-foreground">{activity.author} · {new Date(activity.occurredAt).toLocaleString()}</p></div></Link>)}</div>}</section>
  </div>;
}
function Card({ label, value, icon: Icon, danger = false }: { label: string; value: string | number; icon: React.ComponentType<{ className?: string }>; danger?: boolean }) { return <div className="flex items-center justify-between rounded-xl border bg-card p-5 shadow-sm"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-2 text-2xl font-black ${danger && Number(value) > 0 ? 'text-red-700' : ''}`}>{value}</p></div><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${danger ? 'bg-red-100 text-red-700' : 'bg-primary/10 text-primary'}`}><Icon className="h-5 w-5"/></div></div>; }
function Attention({ title, empty, items }: { title: string; empty: string; items: Array<{ id: string; title: string; detail: string; route: string }> }) { return <div><h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{title}</h3><div className="mt-3 space-y-2">{items.length === 0 ? <p className="rounded-lg border border-dashed p-4 text-xs text-muted-foreground">{empty}</p> : items.slice(0,5).map((item) => <Link key={item.id} to={item.route} className="block rounded-lg border p-3 hover:bg-muted/40"><p className="text-sm font-bold">{item.title}</p><p className="text-xs text-muted-foreground">{item.detail}</p></Link>)}</div></div>; }
