import { useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Boxes,Download,PackageCheck,Power,RefreshCw,ShieldAlert,Upload } from 'lucide-react';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { useIdentity } from '../hooks/useIdentity';
import { useExtensionRuntime } from '../hooks/useExtensionRuntime';

interface Release {id:string;version:string;status:string;backup_filename?:string|null;backupFilename?:string|null;installed_at?:string;installedAt?:string;}
interface Extension {id:string;packageKey:string;name:string;description:string|null;currentVersion:string;status:'enabled'|'disabled'|'failed';systemManaged:boolean;signatureStatus:string;capabilities:string[];releases:Release[];contributions:Array<{type:string;key:string;enabled:boolean}>;assets:Array<{key:string;mediaType:string;sizeBytes:number}>;dataActions:Array<{id:string;action:string;status:string;backupFilename:string|null;summary:unknown;startedAt:string}>;}
interface ExtensionList {items:Extension[];supportedCapabilities:string[];}

const SAMPLE=JSON.stringify({manifest:{formatVersion:1,packageKey:'example.specialist-pack',name:'Example specialist pack',description:'Declarative extension package',version:'1.0.0',application:{minVersion:'1.0.0'},capabilities:['custom_fields','navigation','localisation'],contributions:{customFields:[{entityType:'organisation',key:'specialist_reference',label:'Specialist reference',type:'text',options:[],required:false}],customEntities:[],forms:[],views:[],navigation:[{key:'workspace',label:'Specialist workspace',route:'/extensions/example.specialist-pack/workspace',order:100}],themes:[],reports:[],workflowTemplates:[],eventSubscriptions:[],localisations:[{locale:'en',messages:{'navigation.example.specialist-pack.workspace':'Specialist workspace'}}],assets:[]}},files:[]},null,2);

function save(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url);}

export default function Extensions(){
  const identity=useIdentity();const client=useQueryClient();const runtime=useExtensionRuntime();const [packageText,setPackageText]=useState(SAMPLE);const [approved,setApproved]=useState<string[]>([]);const [message,setMessage]=useState('');const [confirmations,setConfirmations]=useState<Record<string,string>>({});
  const list=useQuery<ExtensionList>({queryKey:['extensions'],queryFn:()=>api.get('/api/extensions')});
  const parsed=useMemo(()=>{try{return JSON.parse(packageText) as unknown;}catch{return null;}},[packageText]);
  const refresh=()=>{client.invalidateQueries({queryKey:['extensions']});client.invalidateQueries({queryKey:['extension-runtime']});};
  const validate=useMutation({mutationFn:()=>api.post('/api/extensions/validate',{package:parsed,approvedCapabilities:approved}),onSuccess:(value)=>setMessage(`Package validated: ${(value as any).checksum}`),onError:(error)=>setMessage((error as Error).message)});
  const install=useMutation({mutationFn:()=>api.post('/api/extensions/install',{package:parsed,approvedCapabilities:approved}),onSuccess:(value)=>{setMessage(`Installed ${(value as any).packageKey} ${(value as any).currentVersion}.`);refresh();},onError:(error)=>setMessage((error as Error).message)});
  const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>api.post(`/api/extensions/${id}/${enabled?'enable':'disable'}`,{}),onSuccess:()=>refresh(),onError:(error)=>setMessage((error as Error).message)});
  const purge=useMutation({mutationFn:({id,confirmation}:{id:string;confirmation:string})=>api.post(`/api/extensions/${id}/data-purge`,{confirmation}),onSuccess:(value)=>{setMessage(`Data purge completed after backup ${(value as any).backupFilename}.`);refresh();},onError:(error)=>setMessage((error as Error).message)});
  const restore=useMutation({mutationFn:({id,releaseId,confirmation}:{id:string;releaseId:string;confirmation:string})=>api.post(`/api/extensions/${id}/releases/${releaseId}/restore`,{confirmation}),onSuccess:()=>setMessage('Recovery backup restored. Restart the desktop application before further work.'),onError:(error)=>setMessage((error as Error).message)});
  if(!identity.can('extensions.read'))return <State danger text="This account cannot inspect extensions."/>;
  return <div className="space-y-6"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-primary"><Boxes className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.16em]">WI11 extension platform</span></div><h1 className="mt-2 text-3xl font-black tracking-tight">Extensions</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Install declarative packages, inspect contributions and perform explicit non-destructive lifecycle operations.</p></div><Button variant="outline" onClick={()=>{list.refetch();runtime.refetch();}}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></header>
    {identity.can('extensions.manage')&&<section className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><Upload className="h-5 w-5 text-primary"/><h2 className="font-bold">Validate or install package</h2></div><textarea value={packageText} onChange={(event)=>setPackageText(event.target.value)} spellCheck={false} className="mt-4 min-h-[360px] w-full rounded-lg border bg-slate-950 p-4 font-mono text-xs text-slate-100 outline-none focus:ring-2 focus:ring-ring"/><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" disabled={!parsed||validate.isPending} onClick={()=>validate.mutate()}><PackageCheck className="mr-2 h-4 w-4"/>Validate</Button><Button disabled={!parsed||install.isPending} onClick={()=>install.mutate()}><Upload className="mr-2 h-4 w-4"/>Install or upgrade</Button></div></div><div className="rounded-xl border bg-card p-5"><h2 className="font-bold">Approved capabilities</h2><p className="mt-1 text-xs text-muted-foreground">Approval is explicit for each installation request.</p><div className="mt-4 space-y-2">{list.data?.supportedCapabilities.map((capability)=><label key={capability} className="flex items-center gap-2 rounded-lg border p-2 text-xs"><input type="checkbox" checked={approved.includes(capability)} onChange={(event)=>setApproved((current)=>event.target.checked?[...current,capability]:current.filter((item)=>item!==capability))}/><span className="font-mono">{capability}</span></label>)}</div></div></section>}
    {message&&<div className="rounded-lg border bg-card p-3 text-sm">{message}</div>}
    {runtime.registry?.themes.length?<section className="rounded-xl border bg-card p-5"><h2 className="font-bold">Active theme package</h2><select value={runtime.theme?`${runtime.theme.packageKey}:${runtime.theme.key}`:''} onChange={(event)=>runtime.selectTheme(event.target.value)} className="control mt-3 max-w-md"><option value="">No extension theme</option>{runtime.registry.themes.map((theme)=><option key={`${theme.packageKey}:${theme.key}`} value={`${theme.packageKey}:${theme.key}`}>{String(theme.label||theme.key)} · {theme.extensionName}</option>)}</select></section>:null}
    {list.isLoading?<State text="Loading extension registry…"/>:list.isError?<State danger text={(list.error as Error).message}/>:<div className="space-y-4">{list.data?.items.map((extension)=><ExtensionCard key={extension.id} extension={extension} canManage={identity.can('extensions.manage')} confirmation={confirmations[extension.id]||''} setConfirmation={(value)=>setConfirmations((current)=>({...current,[extension.id]:value}))} toggle={(enabled)=>toggle.mutate({id:extension.id,enabled})} purge={()=>purge.mutate({id:extension.id,confirmation:confirmations[extension.id]||''})} restore={(release)=>restore.mutate({id:extension.id,releaseId:release.id,confirmation:confirmations[extension.id]||''})} download={async(kind)=>{try{const result=await api.download(`/api/extensions/${extension.id}/${kind==='metadata'?'export':'data-export'}`);save(result.blob,result.filename);}catch(error){setMessage((error as Error).message);}}/>)}</div>}
  </div>;
}

function ExtensionCard({extension,canManage,confirmation,setConfirmation,toggle,purge,restore,download}:{extension:Extension;canManage:boolean;confirmation:string;setConfirmation:(value:string)=>void;toggle:(enabled:boolean)=>void;purge:()=>void;restore:(release:Release)=>void;download:(kind:'metadata'|'data')=>void}){
  const active=extension.status==='enabled';const recovery=extension.releases.filter((release)=>Boolean(release.backup_filename||release.backupFilename));
  return <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">{extension.name}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${active?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{extension.status}</span>{extension.systemManaged&&<span className="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-bold uppercase text-blue-800">system managed</span>}</div><p className="mt-1 font-mono text-xs text-muted-foreground">{extension.packageKey} · {extension.currentVersion} · {extension.signatureStatus}</p><p className="mt-2 text-sm text-muted-foreground">{extension.description||'No package description.'}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>download('metadata')}><Download className="mr-1.5 h-4 w-4"/>Metadata</Button>{canManage&&<Button variant="outline" size="sm" onClick={()=>download('data')}><Download className="mr-1.5 h-4 w-4"/>Data</Button>}{canManage&&!extension.systemManaged&&<Button size="sm" variant="outline" onClick={()=>toggle(!active)}><Power className="mr-1.5 h-4 w-4"/>{active?'Disable':'Enable'}</Button>}</div></div><div className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="Capabilities" value={extension.capabilities.length}/><Metric label="Contributions" value={extension.contributions.length}/><Metric label="Assets" value={extension.assets.length}/><Metric label="Releases" value={extension.releases.length}/></div>
    {canManage&&!extension.systemManaged&&<div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 text-amber-900"><ShieldAlert className="h-4 w-4"/><p className="text-xs font-bold uppercase tracking-wider">Destructive and recovery controls</p></div><p className="mt-2 text-xs text-amber-900">Purge requires the extension to be disabled and the exact phrase <code>PURGE {extension.packageKey}</code>. Recovery requires <code>RESTORE {extension.packageKey} VERSION</code> and restores the entire database snapshot.</p><input value={confirmation} onChange={(event)=>setConfirmation(event.target.value)} className="control mt-3" placeholder="Type the exact confirmation phrase"/><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={active||confirmation!==`PURGE ${extension.packageKey}`} onClick={purge}>Purge extension data</Button>{recovery.map((release)=><Button key={release.id} variant="outline" size="sm" disabled={confirmation!==`RESTORE ${extension.packageKey} ${release.version}`} onClick={()=>restore(release)}>Restore before {release.version}</Button>)}</div></div>}
  </section>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-lg border bg-muted/30 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>;}
function State({text,danger=false}:{text:string;danger?:boolean}){return <div className={`rounded-xl border bg-card p-10 text-center text-sm ${danger?'text-destructive':'text-muted-foreground'}`}>{text}</div>;}
