import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { BarChart3,Boxes,FileText,FormInput,Play,Table2,Workflow } from 'lucide-react';
import { Link,useLocation,useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { useIdentity } from '../hooks/useIdentity';
import { useExtensionRuntime,type RuntimeContribution } from '../hooks/useExtensionRuntime';

export default function ExtensionWorkspace(){
  const {packageKey=''}=useParams();const location=useLocation();const identity=useIdentity();const runtime=useExtensionRuntime();const [reportOutput,setReportOutput]=useState<unknown>(null);const [message,setMessage]=useState('');
  const registry=runtime.registry;const extension=registry?.packages.find((item)=>item.packageKey===packageKey);const filter=(items:RuntimeContribution[])=>items.filter((item)=>item.packageKey===packageKey);const navigation=filter(registry?.navigation??[]).sort((a,b)=>Number(a.order??100)-Number(b.order??100));const forms=filter(registry?.forms??[]);const views=filter(registry?.views??[]);const reports=filter(registry?.reports??[]);const workflows=filter(registry?.workflowTemplates??[]);const assets=filter(registry?.assets??[]);
  const runReport=useMutation({mutationFn:(item:RuntimeContribution)=>api.get(`/api/extensions/runtime/reports/${item.extensionId}/${encodeURIComponent(item.key)}`),onSuccess:(value)=>setReportOutput(value),onError:(error)=>setMessage((error as Error).message)});
  const instantiate=useMutation({mutationFn:(item:RuntimeContribution)=>api.post(`/api/extensions/${item.extensionId}/workflow-templates/${encodeURIComponent(item.key)}/instantiate`,{}),onSuccess:(value)=>setMessage((value as any).reused?'Existing workflow opened from this template.':'Disabled workflow definition created for review.'),onError:(error)=>setMessage((error as Error).message)});
  if(runtime.isLoading)return <State text="Loading extension runtime…"/>;if(runtime.isError)return <State danger text={(runtime.error as Error).message}/>;if(!extension)return <State danger text="This extension is not enabled or does not exist."/>;
  return <div className="space-y-6"><header><div className="flex items-center gap-2 text-primary"><Boxes className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.16em]">Declarative extension runtime</span></div><h1 className="mt-2 text-3xl font-black tracking-tight">{extension.name}</h1><p className="mt-1 font-mono text-xs text-muted-foreground">{extension.packageKey} · {extension.version}</p></header>
    {navigation.length>0&&<nav className="flex flex-wrap gap-2" aria-label="Extension navigation">{navigation.map((item)=><Link key={item.key} to={String(item.route)} className={`rounded-full border px-4 py-2 text-xs font-bold ${location.pathname===item.route?'border-primary bg-primary text-primary-foreground':'bg-card hover:bg-muted'}`}>{runtime.t(`navigation.${item.packageKey}.${item.key}`,String(item.label??item.key))}</Link>)}</nav>}
    {message&&<div className="rounded-lg border bg-card p-3 text-sm">{message}</div>}
    <div className="grid gap-5 xl:grid-cols-2">{forms.map((form)=><FormCard key={form.key} form={form}/>)}{views.map((view)=><ViewCard key={view.key} view={view}/>)}</div>
    {reports.length>0&&<section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary"/><h2 className="font-bold">Extension reports</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2">{reports.map((report)=><div key={report.key} className="rounded-lg border p-4"><p className="font-bold">{String(report.name??report.key)}</p><p className="mt-1 text-xs text-muted-foreground">{String(report.description??`Based on ${report.baseReportKey}`)}</p><Button className="mt-3" size="sm" disabled={!identity.can('reports.read')||runReport.isPending} onClick={()=>runReport.mutate(report)}><Play className="mr-1.5 h-4 w-4"/>Run report</Button></div>)}</div>{reportOutput!==null&&<pre className="mt-4 max-h-[520px] overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(reportOutput,null,2)}</pre>}</section>}
    {workflows.length>0&&<section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><Workflow className="h-5 w-5 text-primary"/><h2 className="font-bold">Workflow templates</h2></div><p className="mt-1 text-xs text-muted-foreground">Templates never activate automatically. Instantiation creates a disabled workflow for human review.</p><div className="mt-4 space-y-3">{workflows.map((workflow)=><div key={workflow.key} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{String(workflow.name??workflow.key)}</p><p className="text-xs text-muted-foreground">{String(workflow.description??workflow.triggerType??'Declarative workflow')}</p></div>{identity.can('extensions.manage')&&<Button size="sm" variant="outline" onClick={()=>instantiate.mutate(workflow)}><Workflow className="mr-1.5 h-4 w-4"/>Instantiate disabled</Button>}</div>)}</div></section>}
    {assets.length>0&&<section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary"/><h2 className="font-bold">Verified static assets</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{assets.map((asset)=><a key={asset.key} href={String(asset.url)} target="_blank" rel="noreferrer" className="rounded-lg border p-4 hover:bg-muted"><p className="font-bold">{asset.key}</p><p className="mt-1 text-xs text-muted-foreground">{String(asset.mediaType)} · {Number(asset.sizeBytes).toLocaleString()} bytes</p>{String(asset.mediaType).startsWith('image/')&&<img src={String(asset.url)} alt="" className="mt-3 max-h-36 rounded object-contain"/>}</a>)}</div></section>}
    {forms.length===0&&views.length===0&&reports.length===0&&workflows.length===0&&assets.length===0&&<State text="This enabled package contributes metadata to core CRM entities but has no standalone workspace components."/>}
  </div>;
}

function FormCard({form}:{form:RuntimeContribution}){const fields=Array.isArray(form.fields)?form.fields.map(String):[];return <section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><FormInput className="h-5 w-5 text-primary"/><h2 className="font-bold">{String(form.title??form.key)}</h2></div><p className="mt-1 text-xs text-muted-foreground">{String(form.entityType)} · {String(form.placement??'detail')} placement</p><div className="mt-4 space-y-3">{fields.map((field)=><label key={field} className="block text-xs font-bold">{field}<input className="control mt-1" aria-label={field}/></label>)}</div><p className="mt-3 text-[10px] text-muted-foreground">Rendering is declarative. Persistence remains with the relevant core entity endpoint.</p></section>;}
function ViewCard({view}:{view:RuntimeContribution}){const columns=Array.isArray(view.columns)?view.columns.map(String):[];return <section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><Table2 className="h-5 w-5 text-primary"/><h2 className="font-bold">{String(view.title??view.key)}</h2></div><p className="mt-1 text-xs text-muted-foreground">View over {String(view.entityType)}</p><div className="mt-4 overflow-x-auto"><table className="w-full text-xs"><thead><tr>{columns.map((column)=><th key={column} className="border-b px-2 py-2 text-left">{column}</th>)}</tr></thead><tbody><tr>{columns.map((column)=><td key={column} className="px-2 py-4 text-muted-foreground">—</td>)}</tr></tbody></table></div><p className="mt-3 text-[10px] text-muted-foreground">Default filters: {JSON.stringify(view.defaultFilters??{})}</p></section>;}
function State({text,danger=false}:{text:string;danger?:boolean}){return <div className={`rounded-xl border bg-card p-10 text-center text-sm ${danger?'text-destructive':'text-muted-foreground'}`}>{text}</div>;}
