import { FormEvent,useEffect,useMemo,useState,type ReactNode } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { CheckCircle2,KeyRound,Laptop,LockKeyhole,ShieldCheck,UserRound } from 'lucide-react';
import type { SignedDeploymentProfile } from 'shared/onboarding';
import { Button } from '../components/ui/button';
import { api } from '../lib/api';
import { login,redeemEmployeeEnrolment,selectLocalUser } from '../hooks/useIdentity';

interface LocalUser {id:string;email:string;displayName:string;roles:Array<{key:string;name:string}>;}
interface NavigatorWithUserAgentData extends Navigator {userAgentData?:{platform?:string};}
type LoginMode='account'|'enrolment';

export default function Login(){
  const client=useQueryClient();const [mode,setMode]=useState<LoginMode>('account');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [enrolmentCode,setEnrolmentCode]=useState('');const [deviceName,setDeviceName]=useState('');const [error,setError]=useState('');const [working,setWorking]=useState(false);
  const locals=useQuery<LocalUser[]>({queryKey:['local-users'],queryFn:()=>api.get('/api/auth/local-users'),retry:false});
  const profile=useQuery<SignedDeploymentProfile|null>({queryKey:['public-deployment-profile'],queryFn:()=>api.get<SignedDeploymentProfile>('/api/onboarding/public-profile').catch(()=>null),retry:false,staleTime:60_000});
  useEffect(()=>{const browserNavigator=navigator as NavigatorWithUserAgentData;const platform=browserNavigator.userAgentData?.platform||browserNavigator.platform||'Employee device';setDeviceName(`${platform} device`);},[]);
  const refresh=async()=>{await client.invalidateQueries({queryKey:['crm-identity']});};
  const submit=async(event:FormEvent)=>{event.preventDefault();setWorking(true);setError('');try{if(mode==='account')await login(email,password);else await redeemEmployeeEnrolment(enrolmentCode,deviceName);await refresh();}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setWorking(false);}};
  const choose=async(userId:string)=>{setWorking(true);setError('');try{await selectLocalUser(userId);await refresh();}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setWorking(false);}};
  const deployment=profile.data?.profile;const businessName=deployment?.businessIdentity.displayName||'WhiteLabelCRM';const logo=deployment?.branding.logoUrl||'';const managed=deployment?.deploymentMode==='managed';
  const colours=useMemo(()=>({primary:deployment?.branding.primaryColor||'#2563eb',secondary:deployment?.branding.secondaryColor||'#0f172a',background:deployment?.branding.backgroundColor||'#020617'}),[deployment]);

  return <div className="relative flex min-h-screen items-center justify-center overflow-hidden p-5" style={{background:colours.background}}>
    <div className="pointer-events-none absolute -left-40 -top-40 h-96 w-96 rounded-full opacity-20 blur-3xl" style={{background:colours.primary}}/><div className="pointer-events-none absolute -bottom-48 -right-32 h-[30rem] w-[30rem] rounded-full opacity-20 blur-3xl" style={{background:colours.secondary}}/>
    <div className="relative grid w-full max-w-4xl overflow-hidden rounded-3xl border border-white/10 bg-slate-950/95 text-slate-100 shadow-2xl backdrop-blur lg:grid-cols-[0.9fr_1.1fr]">
      <section className="hidden border-r border-white/10 p-9 lg:flex lg:flex-col lg:justify-between" style={{background:`linear-gradient(150deg,${colours.secondary},${colours.primary})`}}>
        <div>{logo?<img src={logo} alt={`${businessName} logo`} className="max-h-20 max-w-56 rounded-xl bg-white/95 object-contain p-3"/>:<div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 text-xl font-black">{businessName[0]?.toUpperCase()||'W'}</div>}<p className="mt-6 text-xs font-bold uppercase tracking-[0.22em] text-white/65">Secure business workspace</p><h1 className="mt-3 text-4xl font-black tracking-tight">{businessName}</h1><p className="mt-4 max-w-sm text-sm leading-7 text-white/75">One controlled CRM instance, approved business configuration and user-scoped employee access.</p></div>
        <div className="space-y-3 text-sm"><TrustLine text={managed?'Connected to the approved managed business instance':'Standalone local CRM instance'}/><TrustLine text="Signed instance identity and bounded branding"/><TrustLine text="Role-based access with immutable audit history"/></div>
      </section>
      <section className="p-6 sm:p-9">
        <div className="flex items-center gap-3 lg:hidden">{logo?<img src={logo} alt="" className="h-11 w-11 rounded-xl bg-white object-contain p-1"/>:<div className="flex h-11 w-11 items-center justify-center rounded-xl text-white" style={{background:colours.primary}}><ShieldCheck className="h-6 w-6"/></div>}<div><p className="font-black">{businessName}</p><p className="text-xs text-slate-500">Secure CRM workspace</p></div></div>
        <div className="mt-7 lg:mt-0"><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-500">Employee access</p><h2 className="mt-2 text-3xl font-black">{mode==='account'?'Sign in':'Activate this device'}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{mode==='account'?'Use your named business account.':'Use the one-time enrolment token issued by your administrator. The token is exchanged for your own user session, never a shared administrator credential.'}</p></div>
        {managed&&<div className="mt-5 grid grid-cols-2 rounded-xl bg-slate-900 p-1" role="tablist" aria-label="Employee access method"><ModeButton active={mode==='account'} onClick={()=>{setMode('account');setError('');}} icon={<LockKeyhole className="h-4 w-4"/>} label="Account"/><ModeButton active={mode==='enrolment'} onClick={()=>{setMode('enrolment');setError('');}} icon={<KeyRound className="h-4 w-4"/>} label="First activation"/></div>}
        {mode==='account'&&locals.data?.length?<section className="mt-6"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Trusted local profiles</p><div className="mt-2 space-y-2">{locals.data.map((user)=><button key={user.id} disabled={working} onClick={()=>choose(user.id)} className="flex w-full items-center gap-3 rounded-xl border border-slate-800 p-3 text-left hover:bg-slate-900 disabled:opacity-50"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-900"><UserRound className="h-4 w-4"/></div><div className="min-w-0"><p className="truncate text-sm font-bold">{user.displayName}</p><p className="truncate text-xs text-slate-400">{user.email} · {user.roles.map((role)=>role.name).join(', ')}</p></div></button>)}</div><div className="my-5 flex items-center gap-3"><div className="h-px flex-1 bg-slate-800"/><span className="text-[10px] font-bold uppercase tracking-wider text-slate-600">Account login</span><div className="h-px flex-1 bg-slate-800"/></div></section>:null}
        <form onSubmit={submit} className="mt-6 space-y-4">
          {mode==='account'?<><label className="block text-xs font-bold text-slate-300">Email<input autoComplete="username" type="email" value={email} onChange={(event)=>setEmail(event.target.value)} required className="mt-1.5 h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/15"/></label><label className="block text-xs font-bold text-slate-300">Password<div className="relative mt-1.5"><LockKeyhole className="absolute left-3 top-3.5 h-4 w-4 text-slate-500"/><input autoComplete="current-password" type="password" value={password} onChange={(event)=>setPassword(event.target.value)} required className="h-11 w-full rounded-lg border border-slate-700 bg-slate-950 pl-10 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/15"/></div></label></>:<><label className="block text-xs font-bold text-slate-300">One-time enrolment token<textarea autoComplete="one-time-code" value={enrolmentCode} onChange={(event)=>setEnrolmentCode(event.target.value)} required rows={3} placeholder="wlc_enrol_…" className="mt-1.5 w-full resize-none rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 font-mono text-xs outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/15"/></label><label className="block text-xs font-bold text-slate-300">Device name<div className="relative mt-1.5"><Laptop className="absolute left-3 top-3.5 h-4 w-4 text-slate-500"/><input value={deviceName} onChange={(event)=>setDeviceName(event.target.value)} required maxLength={160} className="h-11 w-full rounded-lg border border-slate-700 bg-slate-950 pl-10 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/15"/></div><span className="mt-1.5 block text-[11px] leading-relaxed text-slate-500">Use a recognisable name so an administrator can revoke the correct device later.</span></label></>}
          {error&&<p role="alert" className="rounded-lg border border-red-900 bg-red-950/40 p-3 text-xs text-red-300">{error}</p>}<Button className="w-full" disabled={working} style={{background:colours.primary}}>{working?(mode==='account'?'Opening workspace…':'Registering device…'):(mode==='account'?'Sign in':'Activate and open workspace')}</Button>
        </form>
        {mode==='enrolment'&&<p className="mt-4 flex items-start gap-2 text-[11px] leading-relaxed text-slate-500"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500"/>The raw token is used once. This device stores a random local identifier and your normal expiring user session; it does not store the enrolment token.</p>}
      </section>
    </div>
  </div>;
}

function ModeButton({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:ReactNode;label:string}){return <button type="button" role="tab" aria-selected={active} onClick={onClick} className={`flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-xs font-bold transition ${active?'bg-slate-700 text-white shadow':'text-slate-500 hover:text-slate-200'}`}>{icon}{label}</button>;}
function TrustLine({text}:{text:string}){return <div className="flex items-center gap-2 text-white/80"><CheckCircle2 className="h-4 w-4 shrink-0"/><span>{text}</span></div>;}
