import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Archive, BriefcaseBusiness, Building2, ExternalLink, Mail, MessageSquare, Pencil, Star, UserRound } from 'lucide-react';
import type {
  ActivityCreateBody,
  ActivityType,
  ContactCreateBody,
  EngagementCreateBody,
  EngagementStatus,
  EngagementType,
  OrganisationUpdate,
  OrganisationWorkspace as OrganisationWorkspaceData,
  TimelineEventType,
  TimelineResponse,
} from 'shared';
import { api } from '../lib/api';
import { buildQueryString } from '../lib/wi4';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';

type Tab = 'overview' | 'timeline' | 'contacts' | 'engagements';

export default function OrganisationWorkspace() {
  const { organisationId = '' } = useParams();
  const [searchParams, setSearchParams] = useSearchParams();
  const queryClient = useQueryClient();
  const tab = (searchParams.get('tab') || 'overview') as Tab;
  const [dialog, setDialog] = useState<'organisation' | 'contact' | 'engagement' | 'activity' | null>(null);
  const [error, setError] = useState('');
  const [timelineType, setTimelineType] = useState<TimelineEventType | ''>('');

  const workspace = useQuery<OrganisationWorkspaceData>({
    queryKey: ['organisation-workspace', organisationId],
    queryFn: () => api.get(`/api/workspace/organisations/${organisationId}`),
    enabled: Boolean(organisationId),
  });
  const timelineQuery = useMemo(() => ({ eventTypes: timelineType ? [timelineType] : undefined, limit: 100, offset: 0 }), [timelineType]);
  const timeline = useQuery<TimelineResponse>({
    queryKey: ['organisation-timeline', organisationId, timelineQuery],
    queryFn: () => api.get(`/api/organisations/${organisationId}/timeline${buildQueryString(timelineQuery)}`),
    enabled: Boolean(organisationId) && tab === 'timeline',
  });

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['organisation-workspace', organisationId] });
    queryClient.invalidateQueries({ queryKey: ['organisation-timeline', organisationId] });
    queryClient.invalidateQueries({ queryKey: ['workspace-organisations'] });
    queryClient.invalidateQueries({ queryKey: ['search'] });
  };
  const mutation = useMutation({ mutationFn: ({ path, body, method = 'post' }: { path: string; body: unknown; method?: 'post'|'patch' }) => method === 'patch' ? api.patch(path, body) : api.post(path, body), onSuccess: () => { setDialog(null); setError(''); invalidate(); }, onError: (e: Error) => setError(e.message) });
  const archiveMutation = useMutation({ mutationFn: () => api.post(`/api/organisations/${organisationId}/archive`, {}), onSuccess: invalidate, onError: (e: Error) => setError(e.message) });

  if (workspace.isLoading) return <State text="Loading organisation workspace…"/>;
  if (workspace.isError || !workspace.data) return <State danger text={(workspace.error as Error)?.message || 'Organisation not found'}/>;
  const data = workspace.data;
  const organisation = data.organisation;

  const setTab = (nextTab: Tab) => { const next = new URLSearchParams(searchParams); next.set('tab', nextTab); setSearchParams(next); };
  const primaryName = data.primaryContact ? `${data.primaryContact.firstName ?? ''} ${data.primaryContact.lastName ?? ''}`.trim() || data.primaryContact.email || 'Unnamed contact' : 'Not assigned';

  return <div className="space-y-6">
    <div className="rounded-xl border bg-card p-6 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-5">
        <div className="flex min-w-0 gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Building2 className="h-6 w-6"/></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-extrabold tracking-tight">{organisation.name}</h1><span className="rounded-full bg-muted px-2.5 py-1 text-[10px] font-bold uppercase">{organisation.status.replace('_',' ')}</span>{organisation.archivedAt && <span className="rounded-full bg-red-100 px-2.5 py-1 text-[10px] font-bold uppercase text-red-700">Archived</span>}</div><p className="mt-1 text-sm text-muted-foreground">{organisation.industry || 'Industry not recorded'}{organisation.country ? ` · ${organisation.country}` : ''}{organisation.website ? ` · ${organisation.website}` : ''}</p></div></div>
        <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setDialog('organisation')}><Pencil className="mr-2 h-4 w-4"/>Edit</Button><Button variant="outline" onClick={() => setDialog('contact')}><UserRound className="mr-2 h-4 w-4"/>Contact</Button><Button variant="outline" onClick={() => setDialog('engagement')}><BriefcaseBusiness className="mr-2 h-4 w-4"/>Engagement</Button><Button onClick={() => setDialog('activity')}><MessageSquare className="mr-2 h-4 w-4"/>Log activity</Button>{!organisation.archivedAt && <Button variant="outline" onClick={() => archiveMutation.mutate()}><Archive className="mr-2 h-4 w-4"/>Archive</Button>}</div>
      </div>
      {error && <div className="mt-4 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
      <div className="mt-6 grid gap-4 border-t pt-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Primary contact" value={primaryName}/><Metric label="Open engagements" value={String(data.activeEngagementCount)}/><Metric label="Next follow-up" value={data.nextFollowUpDate || 'None'}/><Metric label="Last activity" value={data.lastActivityAt ? new Date(data.lastActivityAt).toLocaleDateString() : 'None'}/></div>
    </div>

    <div className="flex gap-5 overflow-x-auto border-b">{(['overview','timeline','contacts','engagements'] as Tab[]).map((name) => <button key={name} onClick={() => setTab(name)} className={`border-b-2 px-1 pb-3 text-sm font-semibold capitalize ${tab === name ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}>{name}</button>)}</div>

    {tab === 'overview' && <Overview data={data} setTab={setTab}/>} 
    {tab === 'timeline' && <TimelineView data={timeline.data} loading={timeline.isLoading} error={timeline.error as Error | null} type={timelineType} onType={setTimelineType}/>} 
    {tab === 'contacts' && <ContactsView data={data} onEdit={(contactId) => setDialog(contactId ? 'contact' : 'contact')}/>} 
    {tab === 'engagements' && <EngagementsView data={data}/>} 

    {dialog === 'organisation' && <OrganisationForm organisation={organisation} onClose={() => setDialog(null)} onSubmit={(body) => mutation.mutate({ path: `/api/organisations/${organisationId}`, body, method: 'patch' })}/>} 
    {dialog === 'contact' && <ContactForm onClose={() => setDialog(null)} onSubmit={(body) => mutation.mutate({ path: `/api/organisations/${organisationId}/contacts`, body })}/>} 
    {dialog === 'engagement' && <EngagementForm contacts={data.contacts} onClose={() => setDialog(null)} onSubmit={(body) => mutation.mutate({ path: `/api/organisations/${organisationId}/engagements`, body })}/>} 
    {dialog === 'activity' && <ActivityForm contacts={data.contacts} engagements={data.engagements} onClose={() => setDialog(null)} onSubmit={(body) => mutation.mutate({ path: `/api/organisations/${organisationId}/activities`, body })}/>} 
  </div>;
}

function Overview({ data, setTab }: { data: OrganisationWorkspaceData; setTab: (tab: Tab) => void }) {
  return <div className="grid gap-6 lg:grid-cols-3">
    <section className="space-y-4 rounded-xl border bg-card p-5 shadow-sm lg:col-span-2"><div className="flex justify-between"><div><h2 className="font-bold">Recent activity</h2><p className="text-xs text-muted-foreground">Canonical interaction history</p></div><button className="text-xs font-semibold text-primary" onClick={() => setTab('timeline')}>Full timeline</button></div>{data.recentActivities.length === 0 ? <Empty text="No activity recorded."/> : <div className="divide-y">{data.recentActivities.map((activity) => <div key={activity.id} className="py-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold capitalize">{activity.type}</p><time className="text-xs text-muted-foreground">{new Date(activity.occurredAt).toLocaleString()}</time></div><p className="mt-1 text-sm text-foreground/80">{activity.body}</p><p className="mt-1 text-xs text-muted-foreground">{activity.author}{activity.followUpDate ? ` · Follow up ${activity.followUpDate}` : ''}</p></div>)}</div>}</section>
    <div className="space-y-6"><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-bold">Active work</h2><div className="mt-3 space-y-3">{data.engagements.filter((e) => !e.archivedAt && ['active','proposed','paused'].includes(e.status)).slice(0,4).map((engagement) => <div key={engagement.id} className="rounded-lg bg-muted/40 p-3"><p className="text-sm font-bold">{engagement.name}</p><p className="text-xs text-muted-foreground capitalize">{engagement.type.replace('_',' ')} · {engagement.status}</p></div>)}{data.engagements.length === 0 && <Empty text="No engagements."/>}</div></section><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-bold">Legacy customer links</h2><div className="mt-3 space-y-3">{data.associatedCustomers.map((customer) => <Link key={customer.id} to={`/customers/${customer.id}`} className="block rounded-lg border p-3 hover:bg-muted/40"><p className="text-sm font-bold">{customer.firstName} {customer.lastName}</p><p className="text-xs text-muted-foreground">{customer.bookingCount} bookings · {customer.invoiceCount} invoices · €{(customer.outstandingCents/100).toFixed(2)} outstanding</p></Link>)}{data.associatedCustomers.length === 0 && <Empty text="No mapped legacy records."/>}</div></section></div>
  </div>;
}

function TimelineView({ data, loading, error, type, onType }: { data?: TimelineResponse; loading: boolean; error: Error | null; type: TimelineEventType | ''; onType: (type: TimelineEventType | '') => void }) {
  if (loading) return <State text="Loading unified timeline…"/>;
  if (error) return <State danger text={error.message}/>;
  return <div className="space-y-4"><div className="flex justify-between rounded-xl border bg-card p-4"><select value={type} onChange={(e) => onType(e.target.value as TimelineEventType | '')} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All event types</option>{['activity','engagement','booking','invoice','payment'].map((item) => <option key={item}>{item}</option>)}</select><span className="text-xs text-muted-foreground">{data?.total ?? 0} events</span></div>{!data?.items.length ? <Empty text="No timeline events match this filter."/> : <div className="relative ml-4 space-y-4 border-l pl-6">{data.items.map((event) => <article key={`${event.eventType}-${event.id}`} className="relative rounded-xl border bg-card p-5 shadow-sm"><div className="absolute -left-[33px] top-5 h-4 w-4 rounded-full border-4 border-background bg-primary"/><div className="flex flex-wrap justify-between gap-3"><div><span className="rounded bg-muted px-2 py-0.5 text-[10px] font-bold uppercase">{event.eventType}</span><h3 className="mt-2 font-bold">{event.title}</h3></div><time className="text-xs text-muted-foreground">{new Date(event.occurredAt).toLocaleString()}</time></div><p className="mt-2 text-sm text-foreground/75">{event.description}</p><Link className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary" to={event.sourceRoute}>Open source <ExternalLink className="h-3 w-3"/></Link></article>)}</div>}</div>;
}

function ContactsView({ data }: { data: OrganisationWorkspaceData; onEdit: (id?: string) => void }) { return <div className="grid gap-4 md:grid-cols-2">{data.contacts.map((contact) => <article key={contact.id} className={`rounded-xl border bg-card p-5 shadow-sm ${contact.archivedAt ? 'opacity-60' : ''}`}><div className="flex justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound className="h-5 w-5"/></div><div><h3 className="flex items-center gap-1 font-bold">{`${contact.firstName ?? ''} ${contact.lastName ?? ''}`.trim() || contact.email || 'Unnamed'}{contact.isPrimary && <Star className="h-3.5 w-3.5 fill-amber-400 text-amber-500"/>}</h3><p className="text-xs text-muted-foreground">{contact.jobTitle || 'Role not recorded'} · {contact.status}</p></div></div></div>{contact.email && <p className="mt-4 flex items-center gap-2 text-sm"><Mail className="h-4 w-4 text-muted-foreground"/>{contact.email}</p>}</article>)}{data.contacts.length === 0 && <Empty text="No contacts."/>}</div>; }
function EngagementsView({ data }: { data: OrganisationWorkspaceData }) { return <div className="grid gap-4 md:grid-cols-2">{data.engagements.map((engagement) => <article key={engagement.id} className={`rounded-xl border bg-card p-5 shadow-sm ${engagement.archivedAt ? 'opacity-60' : ''}`}><div className="flex justify-between gap-3"><div><h3 className="font-bold">{engagement.name}</h3><p className="text-xs capitalize text-muted-foreground">{engagement.type.replace('_',' ')} · {engagement.status}</p></div><BriefcaseBusiness className="h-5 w-5 text-primary"/></div>{engagement.summary && <p className="mt-3 text-sm text-foreground/75">{engagement.summary}</p>}<p className="mt-3 text-xs text-muted-foreground">{engagement.startDate}{engagement.endDate ? ` → ${engagement.endDate}` : ''}</p></article>)}{data.engagements.length === 0 && <Empty text="No engagements."/>}</div>; }

function OrganisationForm({ organisation, onClose, onSubmit }: { organisation: OrganisationWorkspaceData['organisation']; onClose: () => void; onSubmit: (body: OrganisationUpdate) => void }) { const [form,setForm] = useState<OrganisationUpdate>({ name: organisation.name, legalName: organisation.legalName, website: organisation.website, industry: organisation.industry, country: organisation.country, status: organisation.status, source: organisation.source }); return <Modal title="Edit organisation" onClose={onClose}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}><Input required value={form.name ?? ''} onChange={(e) => setForm({...form,name:e.target.value})}/><div className="grid gap-3 sm:grid-cols-2"><Input value={form.industry ?? ''} onChange={(e) => setForm({...form,industry:e.target.value || null})} placeholder="Industry"/><Input value={form.country ?? ''} onChange={(e) => setForm({...form,country:e.target.value.toUpperCase() || null})} placeholder="Country"/></div><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button>Save</Button></div></form></Modal>; }
function ContactForm({ onClose, onSubmit }: { onClose: () => void; onSubmit: (body: ContactCreateBody) => void }) { const [form,setForm] = useState<ContactCreateBody>({ firstName: '', lastName: '', email: null, jobTitle: null, phone: null, isPrimary: false, status: 'active' }); return <Modal title="Create contact" onClose={onClose}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}><div className="grid gap-3 sm:grid-cols-2"><Input value={form.firstName ?? ''} onChange={(e) => setForm({...form,firstName:e.target.value || null})} placeholder="First name"/><Input value={form.lastName ?? ''} onChange={(e) => setForm({...form,lastName:e.target.value || null})} placeholder="Last name"/></div><Input type="email" value={form.email ?? ''} onChange={(e) => setForm({...form,email:e.target.value || null})} placeholder="Email"/><Input value={form.jobTitle ?? ''} onChange={(e) => setForm({...form,jobTitle:e.target.value || null})} placeholder="Role"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isPrimary} onChange={(e) => setForm({...form,isPrimary:e.target.checked})}/>Primary contact</label><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button>Create</Button></div></form></Modal>; }
function EngagementForm({ contacts, onClose, onSubmit }: { contacts: OrganisationWorkspaceData['contacts']; onClose: () => void; onSubmit: (body: EngagementCreateBody) => void }) { const today = new Date().toISOString().slice(0,10); const [form,setForm] = useState<EngagementCreateBody>({ name: '', type: 'diagnostic', status: 'proposed', primaryContactId: null, summary: null, startDate: today, endDate: null }); return <Modal title="Create engagement" onClose={onClose}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}><Input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="Engagement name"/><div className="grid gap-3 sm:grid-cols-2"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.type} onChange={(e) => setForm({...form,type:e.target.value as EngagementType})}>{['diagnostic','sounding_board','guardrail','redesign','implementation','other'].map((type) => <option key={type}>{type}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.status} onChange={(e) => setForm({...form,status:e.target.value as EngagementStatus})}>{['proposed','active','paused','completed','cancelled'].map((status) => <option key={status}>{status}</option>)}</select></div><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.primaryContactId ?? ''} onChange={(e) => setForm({...form,primaryContactId:e.target.value || null})}><option value="">No primary contact</option>{contacts.filter((c) => !c.archivedAt && c.status === 'active').map((contact) => <option key={contact.id} value={contact.id}>{`${contact.firstName ?? ''} ${contact.lastName ?? ''}`.trim() || contact.email}</option>)}</select><textarea className="min-h-[90px] w-full rounded-md border bg-background p-3 text-sm" value={form.summary ?? ''} onChange={(e) => setForm({...form,summary:e.target.value || null})} placeholder="Summary"/><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={form.startDate} onChange={(e) => setForm({...form,startDate:e.target.value})}/><Input type="date" value={form.endDate ?? ''} onChange={(e) => setForm({...form,endDate:e.target.value || null})}/></div><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button>Create</Button></div></form></Modal>; }
function ActivityForm({ contacts, engagements, onClose, onSubmit }: { contacts: OrganisationWorkspaceData['contacts']; engagements: OrganisationWorkspaceData['engagements']; onClose: () => void; onSubmit: (body: ActivityCreateBody) => void }) { const [form,setForm] = useState<ActivityCreateBody>({ type: 'note', body: '', contactId: null, engagementId: null, followUpDate: null }); return <Modal title="Log activity" onClose={onClose}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.type} onChange={(e) => setForm({...form,type:e.target.value as ActivityType})}>{['note','call','email','meeting','message','other'].map((type) => <option key={type}>{type}</option>)}</select><textarea required className="min-h-[110px] w-full rounded-md border bg-background p-3 text-sm" value={form.body} onChange={(e) => setForm({...form,body:e.target.value})} placeholder="What happened?"/><div className="grid gap-3 sm:grid-cols-2"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.contactId ?? ''} onChange={(e) => setForm({...form,contactId:e.target.value || null})}><option value="">Organisation level</option>{contacts.filter((c) => !c.archivedAt).map((contact) => <option key={contact.id} value={contact.id}>{`${contact.firstName ?? ''} ${contact.lastName ?? ''}`.trim() || contact.email}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.engagementId ?? ''} onChange={(e) => setForm({...form,engagementId:e.target.value || null})}><option value="">No engagement</option>{engagements.filter((e) => !e.archivedAt).map((engagement) => <option key={engagement.id} value={engagement.id}>{engagement.name}</option>)}</select></div><label className="space-y-1 text-xs font-semibold text-muted-foreground">Follow-up date<Input type="date" value={form.followUpDate ?? ''} onChange={(e) => setForm({...form,followUpDate:e.target.value || null})}/></label><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button>Log activity</Button></div></form></Modal>; }

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl border bg-card p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button aria-label="Close" onClick={onClose}>×</button></div>{children}</div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</div>; }
function State({ text, danger = false }: { text: string; danger?: boolean }) { return <div className={`rounded-xl border p-12 text-center text-sm ${danger ? 'border-destructive/30 bg-destructive/5 text-destructive' : 'text-muted-foreground'}`}>{text}</div>; }
