import { useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { BarChart3,CalendarClock,Download,FilePlus2,LayoutDashboard,Play,RefreshCw,Save } from 'lucide-react';
import { api } from '../lib/api';
import { Button } from '../components/ui/button';
import { useIdentity } from '../hooks/useIdentity';

const REPORTS=[
  {key:'executive',name:'Executive overview'},
  {key:'revenue',name:'Revenue & receivables'},
  {key:'pipeline',name:'Client pipeline'},
  {key:'activity',name:'Activity & communications'},
  {key:'workload',name:'Workload'},
  {key:'concentration',name:'Revenue concentration'},
  {key:'operations',name:'Operational health'},
] as const;
type ReportKey=typeof REPORTS[number]['key'];
type ChartRow=Record<string,string|number>;
interface SavedReport {id:string;name:string;description:string|null;reportKey:ReportKey;filters:Record<string,string>;visibility:'private'|'team'|'all';ownerUserId:string;ownerTeamId:string|null;updatedAt:string;}
interface Dashboard {id:string;name:string;description:string|null;visibility:string;isDefault:boolean;widgets:Array<{id:string;widgetKey:string;title:string;position:number}>;}
interface ReportSchedule {id:string;saved_report_id:string;cadence:'daily'|'weekly'|'monthly';enabled:number;next_run_at:string;last_run_at:string|null;report_name:string;}
interface ScheduleRun {id:string;scheduleId:string;savedReportId:string;reportName:string;reportKey:ReportKey;status:'running'|'succeeded'|'failed';filename:string|null;byteSize:number|null;errorSummary:string|null;startedAt:string;completedAt:string|null;expiresAt:string|null;downloadAvailable:boolean;}

function dateOnly(date:Date){return date.toISOString().slice(0,10);}
function isoStart(value:string){return new Date(`${value}T00:00:00.000Z`).toISOString();}
function isoEnd(value:string){return new Date(`${value}T23:59:59.999Z`).toISOString();}
function buildQuery(values:Record<string,string|undefined>){const params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>value&&params.set(key,value));return params.toString()?`?${params}`:'';}
function money(value:number){return new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value/100);}
function label(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());}
function nextScheduleAt(){const date=new Date();date.setUTCDate(date.getUTCDate()+1);date.setUTCHours(7,0,0,0);return date.toISOString();}
const PIE_COLORS=['var(--primary)','var(--secondary)','var(--accent)','#64748b','#94a3b8','#cbd5e1'];

export default function Reporting(){
  const identity=useIdentity();const client=useQueryClient();const today=new Date();const defaultFrom=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth()-11,1));
  const [reportKey,setReportKey]=useState<ReportKey>('executive');const [from,setFrom]=useState(dateOnly(defaultFrom));const [to,setTo]=useState(dateOnly(today));const [saveName,setSaveName]=useState('');const [visibility,setVisibility]=useState<'private'|'team'|'all'>('private');const [cadence,setCadence]=useState<'daily'|'weekly'|'monthly'>('weekly');const [message,setMessage]=useState('');
  const filters=useMemo(()=>({from:isoStart(from),to:isoEnd(to)}),[from,to]);const query=buildQuery(filters);
  const report=useQuery<any>({queryKey:['report',reportKey,filters],queryFn:()=>api.get(`/api/reporting/${reportKey}${query}`)});
  const saved=useQuery<SavedReport[]>({queryKey:['saved-reports'],queryFn:()=>api.get('/api/reporting/saved')});
  const dashboards=useQuery<Dashboard[]>({queryKey:['report-dashboards'],queryFn:()=>api.get('/api/reporting/dashboards')});
  const schedules=useQuery<ReportSchedule[]>({queryKey:['report-schedules'],queryFn:()=>api.get('/api/reporting/schedules')});
  const scheduleRuns=useQuery<ScheduleRun[]>({queryKey:['report-schedule-runs'],queryFn:()=>api.get('/api/reporting/schedule-runs?limit=100'),refetchInterval:60_000});
  const save=useMutation({mutationFn:()=>api.post('/api/reporting/saved',{name:saveName,reportKey,filters,visibility,teamId:visibility==='team'?identity.user?.teams[0]?.id:undefined}),onSuccess:()=>{setSaveName('');setMessage('Saved report created.');client.invalidateQueries({queryKey:['saved-reports']});},onError:(error)=>setMessage((error as Error).message)});
  const createDashboard=useMutation({mutationFn:()=>api.post('/api/reporting/dashboards',{name:`${REPORTS.find((item)=>item.key===reportKey)?.name} dashboard`,visibility,teamId:visibility==='team'?identity.user?.teams[0]?.id:undefined,widgets:widgetSet(reportKey).map((widgetKey)=>({widgetKey}))}),onSuccess:()=>{setMessage('Dashboard created.');client.invalidateQueries({queryKey:['report-dashboards']});},onError:(error)=>setMessage((error as Error).message)});
  const createSchedule=useMutation({mutationFn:(savedReportId:string)=>api.post('/api/reporting/schedules',{savedReportId,cadence,nextRunAt:nextScheduleAt()}),onSuccess:()=>{setMessage('Scheduled report added to the download queue.');client.invalidateQueries({queryKey:['report-schedules']});},onError:(error)=>setMessage((error as Error).message)});
  const processSchedules=useMutation({mutationFn:()=>api.post('/api/reporting/schedules/process',{}),onSuccess:(result:any)=>{setMessage(`Scheduled reports processed: ${result.succeeded} succeeded, ${result.failed} failed.`);client.invalidateQueries({queryKey:['report-schedule-runs']});client.invalidateQueries({queryKey:['report-schedules']});},onError:(error)=>setMessage((error as Error).message)});
  const exportReport=async()=>{setMessage('');try{const file=await api.download(`/api/reporting/${reportKey}/export.csv${query}`);downloadBlob(file);}catch(error){setMessage(error instanceof Error?error.message:String(error));}};
  const downloadRun=async(id:string)=>{setMessage('');try{const file=await api.download(`/api/reporting/schedule-runs/${id}/download`);downloadBlob(file);}catch(error){setMessage(error instanceof Error?error.message:String(error));}};
  const openSaved=(item:SavedReport)=>{setReportKey(item.reportKey);if(item.filters.from)setFrom(item.filters.from.slice(0,10));if(item.filters.to)setTo(item.filters.to.slice(0,10));};

  return <div className="space-y-6">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2 text-primary"><BarChart3 className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.16em]">WI8 reporting</span></div><h1 className="mt-2 text-3xl font-black tracking-tight">Reporting & dashboards</h1><p className="mt-1 text-sm text-muted-foreground">Persisted CRM, finance, activity, workload and operating data. No simulated trends.</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-bold text-muted-foreground">From<input type="date" value={from} onChange={(event)=>setFrom(event.target.value)} className="mt-1 block h-9 rounded-md border bg-background px-2 text-sm text-foreground"/></label><label className="text-xs font-bold text-muted-foreground">To<input type="date" value={to} onChange={(event)=>setTo(event.target.value)} className="mt-1 block h-9 rounded-md border bg-background px-2 text-sm text-foreground"/></label><Button variant="outline" size="sm" onClick={()=>report.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>{identity.can('reports.export')&&<Button size="sm" onClick={exportReport}><Download className="mr-2 h-4 w-4"/>Export CSV</Button>}</div></header>

    <div className="flex gap-2 overflow-x-auto pb-1">{REPORTS.map((item)=><button key={item.key} onClick={()=>setReportKey(item.key)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold ${item.key===reportKey?'border-primary bg-primary text-primary-foreground':'bg-card hover:bg-muted'}`}>{item.name}</button>)}</div>

    {report.isLoading?<State text="Calculating report from local records…"/>:report.isError?<State danger text={(report.error as Error).message}/>:<ReportView reportKey={reportKey} data={report.data}/>} 

    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Save className="h-5 w-5 text-primary"/><h2 className="font-bold">Saved reports</h2></div><p className="mt-1 text-xs text-muted-foreground">Save the current report and date range for private, team or all-user reuse.</p>{identity.can('reports.manage')&&<div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input value={saveName} onChange={(event)=>setSaveName(event.target.value)} placeholder="Report name" className="h-9 rounded-md border bg-background px-3 text-sm"/><select value={visibility} onChange={(event)=>setVisibility(event.target.value as typeof visibility)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="private">Private</option><option value="team">Team</option><option value="all">All users</option></select><Button size="sm" disabled={!saveName.trim()||save.isPending} onClick={()=>save.mutate()}><FilePlus2 className="mr-2 h-4 w-4"/>Save</Button></div>}<div className="mt-4 divide-y">{saved.data?.length?saved.data.map((item)=><div key={item.id} className="flex items-center justify-between gap-4 py-3"><button onClick={()=>openSaved(item)} className="min-w-0 flex-1 text-left hover:text-primary"><p className="truncate text-sm font-bold">{item.name}</p><p className="text-xs text-muted-foreground">{REPORTS.find((value)=>value.key===item.reportKey)?.name} · {item.visibility}</p></button>{identity.can('reports.manage')&&<Button size="sm" variant="outline" disabled={createSchedule.isPending} onClick={()=>createSchedule.mutate(item.id)}><CalendarClock className="mr-1.5 h-3.5 w-3.5"/>{cadence}</Button>}</div>):<p className="py-6 text-sm text-muted-foreground">No saved reports are visible to this user.</p>}</div>{identity.can('reports.manage')&&<label className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">New schedule cadence<select value={cadence} onChange={(event)=>setCadence(event.target.value as typeof cadence)} className="h-8 rounded-md border bg-background px-2 text-xs text-foreground"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>}</section>
      <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><LayoutDashboard className="h-5 w-5 text-primary"/><h2 className="font-bold">Dashboards</h2></div><p className="mt-1 text-xs text-muted-foreground">Dashboard definitions are owned, visibility-scoped and backed by the same report queries.</p>{identity.can('reports.manage')&&<Button className="mt-4" size="sm" variant="outline" onClick={()=>createDashboard.mutate()} disabled={createDashboard.isPending}>Create from current report</Button>}<div className="mt-4 space-y-3">{dashboards.data?.map((dashboard)=><div key={dashboard.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><p className="text-sm font-bold">{dashboard.name}</p>{dashboard.isDefault&&<span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold text-primary">Default</span>}</div><p className="mt-1 text-xs text-muted-foreground">{dashboard.widgets.length} widgets · {dashboard.visibility}</p><div className="mt-2 flex flex-wrap gap-1">{dashboard.widgets.map((widget)=><span key={widget.id} className="rounded bg-muted px-2 py-1 text-[10px]">{widget.title}</span>)}</div></div>)}</div></section>
    </div>

    <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-primary"/><div><h2 className="font-bold">Scheduled report queue</h2><p className="text-xs text-muted-foreground">The server processes due schedules automatically and retains generated CSV files for 90 days.</p></div></div>{identity.can('reports.manage')&&<Button size="sm" variant="outline" disabled={processSchedules.isPending} onClick={()=>processSchedules.mutate()}><Play className="mr-2 h-4 w-4"/>Process due now</Button>}</div><div className="mt-4 grid gap-4 xl:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Active schedules</p><div className="mt-2 space-y-2">{schedules.data?.length?schedules.data.map((schedule)=><div key={schedule.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><p className="text-sm font-bold">{schedule.report_name}</p><span className="rounded bg-muted px-2 py-1 text-[10px] font-bold capitalize">{schedule.cadence}</span></div><p className="mt-1 text-xs text-muted-foreground">Next run {new Date(schedule.next_run_at).toLocaleString()}{schedule.last_run_at?` · Last ${new Date(schedule.last_run_at).toLocaleString()}`:''}</p></div>):<p className="py-5 text-sm text-muted-foreground">No active schedules.</p>}</div></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Recent generated files</p><div className="mt-2 space-y-2">{scheduleRuns.data?.length?scheduleRuns.data.map((run)=><div key={run.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{run.reportName}</p><p className="text-xs text-muted-foreground">{new Date(run.startedAt).toLocaleString()} · {run.status}{run.byteSize?` · ${(run.byteSize/1024).toFixed(1)} KB`:''}</p>{run.errorSummary&&<p className="mt-1 text-xs text-destructive">{run.errorSummary}</p>}</div>{run.downloadAvailable&&identity.can('reports.export')&&<Button size="sm" variant="outline" onClick={()=>downloadRun(run.id)}><Download className="h-4 w-4"/></Button>}</div>):<p className="py-5 text-sm text-muted-foreground">No scheduled report runs yet.</p>}</div></div></div></section>
    {message&&<p className="rounded-lg border bg-card p-3 text-sm">{message}</p>}
  </div>;
}

function downloadBlob(file:{blob:Blob;filename:string}){const url=URL.createObjectURL(file.blob);const link=document.createElement('a');link.href=url;link.download=file.filename;link.click();URL.revokeObjectURL(url);}
function widgetSet(key:ReportKey){if(key==='executive')return ['executive_kpis','revenue_trend','pipeline_status','workload','concentration'];if(key==='revenue')return ['revenue_trend','concentration'];if(key==='pipeline')return ['pipeline_status'];if(key==='activity')return ['activity_mix'];if(key==='workload')return ['workload'];if(key==='operations')return ['operations'];return ['concentration'];}
function ReportView({reportKey,data}:{reportKey:ReportKey;data:any}){if(reportKey==='executive')return <Executive data={data}/>;if(reportKey==='revenue')return <Revenue data={data}/>;if(reportKey==='pipeline')return <Pipeline data={data}/>;if(reportKey==='activity')return <Activity data={data}/>;if(reportKey==='workload')return <Workload data={data}/>;if(reportKey==='concentration')return <Concentration data={data}/>;return <Operations data={data}/>;}
function Executive({data}:{data:any}){return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.kpis||{}).map(([key,value])=><Metric key={key} label={label(key)} value={key.toLowerCase().includes('cents')?money(Number(value)):Number(value).toLocaleString()}/>)}</div><div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Revenue trend"><RevenueChart rows={data.revenue?.series||[]}/></ChartCard><ChartCard title="Client lifecycle"><Donut rows={data.pipeline?.organisationStatus||[]}/></ChartCard><ChartCard title="Workload"><WorkloadTable rows={data.workload?.owners||[]}/></ChartCard><ChartCard title="Revenue concentration"><ConcentrationTable rows={data.concentration?.organisations||[]}/></ChartCard></div></div>}
function Revenue({data}:{data:any}){return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Invoiced" value={money(data.totals?.invoicedCents||0)}/><Metric label="Collected" value={money(data.totals?.collectedCents||0)}/><Metric label="Outstanding" value={money(data.totals?.outstandingCents||0)}/></div><div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Monthly invoiced and collected"><RevenueChart rows={data.series||[]}/></ChartCard><ChartCard title="Receivables aging"><BarRows rows={data.aging||[]} dataKey="value" formatter={money}/></ChartCard></div></div>}
function Pipeline({data}:{data:any}){return <div className="grid gap-6 xl:grid-cols-3"><ChartCard title="Organisation status"><Donut rows={data.organisationStatus||[]}/></ChartCard><ChartCard title="Engagement status"><Donut rows={data.engagementStatus||[]}/></ChartCard><ChartCard title="Engagement type"><BarRows rows={data.engagementType||[]} dataKey="value"/></ChartCard></div>}
function Activity({data}:{data:any}){return <div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Monthly activity"><LineRows rows={data.monthly||[]} dataKey="value"/></ChartCard><ChartCard title="Activity type"><Donut rows={data.byType||[]}/></ChartCard><ChartCard title="Communication channels"><BarRows rows={data.communications||[]} dataKey="value"/></ChartCard><ChartCard title="Follow-up completion"><Donut rows={data.followUps||[]}/></ChartCard></div>}
function Workload({data}:{data:any}){return <ChartCard title="Tasks by owner"><WorkloadTable rows={data.owners||[]}/></ChartCard>}
function Concentration({data}:{data:any}){return <div className="space-y-4"><Metric label="Collected revenue in range" value={money(data.totalCollectedCents||0)}/><ChartCard title="Top organisations"><ConcentrationTable rows={data.organisations||[]}/></ChartCard></div>}
function Operations({data}:{data:any}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.metrics||{}).map(([key,value])=><Metric key={key} label={label(key)} value={Number(value).toLocaleString()} danger={Number(value)>0&&key!=='activeSessions'}/>)}</div>}
function Metric({label:metricLabel,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className={`rounded-xl border bg-card p-5 shadow-sm ${danger?'border-red-300':''}`}><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{metricLabel}</p><p className={`mt-2 text-2xl font-black ${danger?'text-red-700':''}`}>{value}</p></div>}
function ChartCard({title,children}:{title:string;children:React.ReactNode}){return <section className="min-h-72 rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-4 h-56">{children}</div></section>}
function RevenueChart({rows}:{rows:ChartRow[]}){return <ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={11}/><YAxis fontSize={11} tickFormatter={(value)=>money(Number(value))}/><Tooltip formatter={(value)=>money(Number(value))}/><Legend/><Line type="monotone" dataKey="invoicedCents" name="Invoiced" stroke="var(--primary)" strokeWidth={2}/><Line type="monotone" dataKey="collectedCents" name="Collected" stroke="var(--secondary)" strokeWidth={2}/></LineChart></ResponsiveContainer>}
function Donut({rows}:{rows:ChartRow[]}){return <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={45} outerRadius={75} paddingAngle={2}>{rows.map((_,index)=><Cell key={index} fill={PIE_COLORS[index%PIE_COLORS.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer>}
function BarRows({rows,dataKey,formatter}:{rows:ChartRow[];dataKey:string;formatter?:(value:number)=>string}){return <ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey={rows[0]?.name!==undefined?'name':'bucket'} fontSize={11}/><YAxis fontSize={11} tickFormatter={(value)=>formatter?formatter(Number(value)):String(value)}/><Tooltip formatter={(value)=>formatter?formatter(Number(value)):Number(value).toLocaleString()}/><Bar dataKey={dataKey} fill="var(--primary)"/></BarChart></ResponsiveContainer>}
function LineRows({rows,dataKey}:{rows:ChartRow[];dataKey:string}){return <ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={11}/><YAxis fontSize={11}/><Tooltip/><Line type="monotone" dataKey={dataKey} stroke="var(--primary)" strokeWidth={2}/></LineChart></ResponsiveContainer>}
function WorkloadTable({rows}:{rows:any[]}){return <div className="h-full overflow-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-2">Owner</th><th>Open</th><th>Overdue</th><th>Completed</th></tr></thead><tbody className="divide-y">{rows.map((row)=><tr key={row.ownerId}><td className="py-3 font-bold">{row.name}</td><td>{row.open}</td><td className={Number(row.overdue)>0?'font-bold text-red-700':''}>{row.overdue}</td><td>{row.completed}</td></tr>)}</tbody></table></div>}
function ConcentrationTable({rows}:{rows:any[]}){return <div className="h-full overflow-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-2">Organisation</th><th>Collected</th><th>Share</th></tr></thead><tbody className="divide-y">{rows.map((row)=><tr key={row.organisationId}><td className="py-3 font-bold">{row.name}</td><td>{money(Number(row.collectedCents))}</td><td>{Number(row.sharePercent).toFixed(1)}%</td></tr>)}</tbody></table></div>}
function State({text,danger=false}:{text:string;danger?:boolean}){return <div className={`rounded-xl border bg-card p-12 text-center text-sm ${danger?'border-destructive/30 text-destructive':'text-muted-foreground'}`}>{text}</div>}
