import { useEffect,useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { FilePlus2,Mail,Play,Save,Trash2 } from 'lucide-react';
import type { Customer,WorkspaceStarterReport } from 'shared';
import { Button } from '../../components/ui/button';
import { api } from '../../lib/api';
import { useIdentity } from '../../hooks/useIdentity';
import { useWorkspaceModel } from '../../hooks/useWorkspaceModel';

interface Column {key:string;label:string;type:string;}
interface Source {key:string;name:string;description:string;columns:Column[];}
interface Filter {field:string;operator:'equals'|'contains'|'not_empty'|'before'|'after';value?:string;}
interface Definition {sourceKey:string;columns:string[];filters:Filter[];groupBy?:string|null;}
interface Result {source:{key:string;name:string};columns:Column[];rows:Array<Record<string,unknown>>;groups:Array<{name:string;value:number}>;total:number;truncated:boolean;generatedAt:string;}
interface Saved {id:string;name:string;description:string|null;definition:Definition;visibility:'private'|'team'|'all';updatedAt:string;}
interface Account {id:string;kind:'email'|'calendar';name:string;enabled:boolean;}

const defaultColumns=(source?:Source)=>source?.columns.slice(0,Math.min(5,source.columns.length)).map((column)=>column.key)??[];
function downloadBlob(file:{blob:Blob;filename:string}){const url=URL.createObjectURL(file.blob);const link=document.createElement('a');link.href=url;link.download=file.filename;link.click();URL.revokeObjectURL(url);}

export default function ReportBuilder(){
  const identity=useIdentity();const model=useWorkspaceModel();const client=useQueryClient();
  const canManage=identity.can('reports.manage');const canExport=identity.can('reports.export');
  const catalog=useQuery<{sources:Source[]}>({queryKey:['report-builder-catalog'],queryFn:()=>api.get('/api/reporting/builder/catalog')});
  const saved=useQuery<Saved[]>({queryKey:['report-builder-saved'],queryFn:()=>api.get('/api/reporting/builder/saved')});
  const accounts=useQuery<Account[]>({queryKey:['communication-accounts'],queryFn:()=>api.get('/api/communication-accounts')});
  const customers=useQuery<Customer[]>({queryKey:['customers','report-delivery'],queryFn:()=>api.get('/api/customers')});
  const [sourceKey,setSourceKey]=useState('customers');const [columns,setColumns]=useState<string[]>([]);
  const [groupBy,setGroupBy]=useState('');const [filters,setFilters]=useState<Filter[]>([]);
  const [result,setResult]=useState<Result|null>(null);const [saveName,setSaveName]=useState('');const [visibility,setVisibility]=useState<'private'|'team'|'all'>('private');
  const [message,setMessage]=useState('');const [emailOpen,setEmailOpen]=useState(false);const [accountId,setAccountId]=useState('');const [customerId,setCustomerId]=useState('');const [subject,setSubject]=useState('Your report');
  const sources=catalog.data?.sources??[];const source=sources.find((item)=>item.key===sourceKey);
  const definition=useMemo<Definition>(()=>({sourceKey,columns,filters,groupBy:groupBy||null}),[sourceKey,columns,filters,groupBy]);
  const starterReports=model.data?.presentation?.starterReports??[];
  useEffect(()=>{if(!source||columns.length)return;setColumns(defaultColumns(source));},[source?.key]);
  useEffect(()=>{const email=accounts.data?.find((item)=>item.kind==='email'&&item.enabled);if(email&&!accountId)setAccountId(email.id);},[accounts.data,accountId]);
  const run=useMutation({mutationFn:(next:Definition)=>api.post<Result>('/api/reporting/builder/run',next),onSuccess:(data)=>{setResult(data);setMessage(`${data.total} record${data.total===1?'':'s'} matched.`);},onError:(error)=>setMessage((error as Error).message)});
  const save=useMutation({mutationFn:()=>api.post('/api/reporting/builder/saved',{name:saveName,definition,visibility,teamId:visibility==='team'?identity.user?.teams[0]?.id:undefined}),onSuccess:()=>{setSaveName('');setMessage('Report saved.');client.invalidateQueries({queryKey:['report-builder-saved']});},onError:(error)=>setMessage((error as Error).message)});
  const remove=useMutation({mutationFn:(id:string)=>api.delete(`/api/reporting/builder/saved/${id}`),onSuccess:()=>client.invalidateQueries({queryKey:['report-builder-saved']})});
  const draft=useMutation({mutationFn:()=>api.post<any>('/api/reporting/builder/email-draft',{accountId,targetCustomerId:customerId,subject,definition}),onSuccess:(data)=>{setEmailOpen(false);setMessage(`Email draft created for ${data.report.total} customer-scoped record${data.report.total===1?'':'s'}. Review it in Communications before sending.`);},onError:(error)=>setMessage((error as Error).message)});
  const chooseSource=(key:string)=>{const next=sources.find((item)=>item.key===key);setSourceKey(key);setColumns(defaultColumns(next));setFilters([]);setGroupBy('');setResult(null);};
  const openDefinition=(item:{definition:Definition})=>{const next=sources.find((source)=>source.key===item.definition.sourceKey);if(!next){setMessage('That report source is no longer available.');return;}setSourceKey(item.definition.sourceKey);setColumns(item.definition.columns);setFilters(item.definition.filters??[]);setGroupBy(item.definition.groupBy??'');setResult(null);};
  const openStarter=(preset:WorkspaceStarterReport)=>openDefinition({definition:{sourceKey:preset.sourceKey,columns:preset.columns,filters:[],groupBy:preset.groupBy??null}});
  const exportCsv=async()=>{try{downloadBlob(await api.downloadPost('/api/reporting/builder/export.csv',definition));}catch(error){setMessage((error as Error).message);}};
  if(catalog.isLoading)return <section className="rounded-xl border bg-card p-8 text-sm text-muted-foreground">Loading report sources…</section>;
  if(catalog.isError||!source)return <section className="rounded-xl border border-destructive/30 bg-destructive/5 p-8 text-sm text-destructive">{(catalog.error as Error)?.message||'No report source is available.'}</section>;
  return <section className="space-y-5 rounded-xl border bg-card p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><FilePlus2 className="h-5 w-5 text-primary"/><h2 className="font-bold">Report builder</h2></div><p className="mt-1 text-xs text-muted-foreground">Choose a record type, columns, filters and grouping. Templates provide starters; your saved reports remain independent and editable.</p></div><Button size="sm" disabled={run.isPending||!columns.length} onClick={()=>run.mutate(definition)}><Play className="mr-2 h-4 w-4"/>Run report</Button></div>
    {starterReports.length>0&&<div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Recommended for {model.data?.templateName}</p><div className="mt-2 flex flex-wrap gap-2">{starterReports.map((preset)=><button key={preset.key} onClick={()=>openStarter(preset)} className="rounded-full border px-3 py-1.5 text-xs font-bold hover:border-primary hover:text-primary">{preset.name}</button>)}</div></div>}
    <div className="grid gap-4 lg:grid-cols-3">
      <label className="text-xs font-bold text-muted-foreground">Report source<select value={sourceKey} onChange={(event)=>chooseSource(event.target.value)} className="mt-1 block h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground">{sources.map((item)=><option key={item.key} value={item.key}>{item.name}</option>)}</select><span className="mt-1 block font-normal">{source.description}</span></label>
      <label className="text-xs font-bold text-muted-foreground">Group counts by<select value={groupBy} onChange={(event)=>setGroupBy(event.target.value)} className="mt-1 block h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground"><option value="">No grouping</option>{source.columns.map((column)=><option key={column.key} value={column.key}>{column.label}</option>)}</select></label>
      <div className="text-xs font-bold text-muted-foreground">Filter{filters.map((filter,index)=><div key={index} className="mt-1 grid grid-cols-[1fr_auto] gap-2"><div className="grid grid-cols-3 gap-1"><select value={filter.field} onChange={(event)=>setFilters((items)=>items.map((item,i)=>i===index?{...item,field:event.target.value}:item))} className="h-9 rounded-md border bg-background px-1 text-xs text-foreground">{source.columns.map((column)=><option key={column.key} value={column.key}>{column.label}</option>)}</select><select value={filter.operator} onChange={(event)=>setFilters((items)=>items.map((item,i)=>i===index?{...item,operator:event.target.value as Filter['operator']}:item))} className="h-9 rounded-md border bg-background px-1 text-xs text-foreground"><option value="equals">equals</option><option value="contains">contains</option><option value="not_empty">is set</option><option value="before">before</option><option value="after">after</option></select><input value={filter.value??''} disabled={filter.operator==='not_empty'} onChange={(event)=>setFilters((items)=>items.map((item,i)=>i===index?{...item,value:event.target.value}:item))} className="h-9 rounded-md border bg-background px-2 text-xs text-foreground"/></div><button onClick={()=>setFilters((items)=>items.filter((_,i)=>i!==index))}>×</button></div>)}<button disabled={filters.length>=10} onClick={()=>setFilters((items)=>[...items,{field:source.columns[0].key,operator:'equals',value:''}])} className="mt-2 text-xs font-bold text-primary">+ Add filter</button></div>
    </div>
    <div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Columns</p><div className="mt-2 flex flex-wrap gap-2">{source.columns.map((column)=><label key={column.key} className={`cursor-pointer rounded-full border px-3 py-1.5 text-xs ${columns.includes(column.key)?'border-primary bg-primary/5 font-bold text-primary':''}`}><input type="checkbox" className="sr-only" checked={columns.includes(column.key)} onChange={(event)=>setColumns((items)=>event.target.checked?[...items,column.key]:items.filter((key)=>key!==column.key))}/>{column.label}</label>)}</div></div>
    {result&&<div className="space-y-3">{result.groups.length>0&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{result.groups.slice(0,12).map((group)=><div key={group.name} className="rounded-lg border p-3"><p className="truncate text-xs text-muted-foreground">{group.name}</p><p className="mt-1 text-xl font-black">{group.value}</p></div>)}</div>}<div className="max-h-96 overflow-auto rounded-lg border"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-muted"><tr>{result.columns.map((column)=><th key={column.key} className="whitespace-nowrap px-3 py-2">{column.label}</th>)}</tr></thead><tbody className="divide-y">{result.rows.map((row,index)=><tr key={index}>{result.columns.map((column)=><td key={column.key} className="max-w-72 truncate px-3 py-2">{String(row[column.key]??'')}</td>)}</tr>)}</tbody></table>{!result.rows.length&&<p className="p-6 text-center text-muted-foreground">No records matched.</p>}</div><p className="text-xs text-muted-foreground">{result.total} records{result.truncated?' · preview truncated':''}</p></div>}
    <div className="grid gap-4 border-t pt-5 xl:grid-cols-2"><div><div className="flex items-center gap-2"><Save className="h-4 w-4 text-primary"/><h3 className="text-sm font-bold">Save for your team</h3></div>{canManage&&<div className="mt-2 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input value={saveName} onChange={(event)=>setSaveName(event.target.value)} placeholder="Report name" className="h-9 rounded-md border bg-background px-3 text-sm"/><select value={visibility} onChange={(event)=>setVisibility(event.target.value as typeof visibility)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="private">Private</option><option value="team">Team</option><option value="all">All users</option></select><Button size="sm" disabled={!saveName.trim()||!columns.length||save.isPending} onClick={()=>save.mutate()}>Save</Button></div>}<div className="mt-3 space-y-2">{saved.data?.map((item)=><div key={item.id} className="flex items-center gap-2 rounded-lg border p-2"><button onClick={()=>openDefinition(item)} className="min-w-0 flex-1 text-left"><p className="truncate text-xs font-bold">{item.name}</p><p className="text-[10px] text-muted-foreground">{item.visibility} · {item.definition.sourceKey}</p></button>{canManage&&<button onClick={()=>remove.mutate(item.id)} aria-label={`Archive ${item.name}`}><Trash2 className="h-3.5 w-3.5 text-muted-foreground"/></button>}</div>)}</div></div>
      <div><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-primary"/><h3 className="text-sm font-bold">Deliver or keep local</h3></div><p className="mt-1 text-xs text-muted-foreground">CSV export stays on this computer. Customer email creates a customer-scoped draft for review; it never sends automatically.</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" disabled={!canExport||!columns.length} onClick={exportCsv}>Download CSV</Button><Button size="sm" variant="outline" disabled={!canManage||!columns.length||!accounts.data?.some((item)=>item.kind==='email'&&item.enabled)} onClick={()=>setEmailOpen(true)}>Create customer email draft</Button></div></div></div>
    {message&&<p className="rounded-lg border bg-muted/30 p-3 text-sm">{message}</p>}
    {emailOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-xl border bg-card p-6 shadow-2xl"><h2 className="text-xl font-bold">Create customer report draft</h2><p className="mt-1 text-xs text-muted-foreground">The report is automatically restricted to the selected customer. Review and explicitly send it from Communications.</p><div className="mt-5 space-y-3"><select value={accountId} onChange={(event)=>setAccountId(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm">{accounts.data?.filter((item)=>item.kind==='email'&&item.enabled).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={customerId} onChange={(event)=>setCustomerId(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Choose customer</option>{customers.data?.filter((item)=>item.email).map((item)=><option key={item.id} value={item.id}>{item.firstName} {item.lastName} · {item.email}</option>)}</select><input value={subject} onChange={(event)=>setSubject(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>setEmailOpen(false)}>Cancel</Button><Button disabled={!accountId||!customerId||!subject.trim()||draft.isPending} onClick={()=>draft.mutate()}>Create draft</Button></div></div></div>}
  </section>;
}
