import type { IOrganisationRepository, IContactRepository, IEngagementRepository, OrganisationListOptions, ContactListOptions, EngagementListOptions } from '../interfaces/IRepositories';
import type { OrganisationCreate, OrganisationUpdate, ContactCreate, ContactUpdate, EngagementCreate, EngagementUpdate } from 'shared';
import { ContactCreateSchema } from 'shared';
import { ConflictError, NotFoundError, ValidationError } from '../errors';

export class OrganisationService { constructor(private orgs:IOrganisationRepository){} async create(i:OrganisationCreate){return this.orgs.create(i)} async get(id:string){const o=await this.orgs.getById(id); if(!o)throw new NotFoundError('Organisation not found'); return o} async list(o:OrganisationListOptions){return this.orgs.list(o)} async update(id:string,p:OrganisationUpdate){const current=await this.orgs.getById(id,{includeArchived:true}); if(!current)throw new NotFoundError('Organisation not found'); if(current.archivedAt)throw new ConflictError('Archived organisations cannot be edited'); const updated=await this.orgs.update(id,p); if(!updated)throw new NotFoundError('Organisation not found'); return updated} async archive(id:string){const o=await this.orgs.archive(id,new Date().toISOString()); if(!o)throw new NotFoundError('Organisation not found'); return o} }

export class ContactService { constructor(private orgs:IOrganisationRepository, private contacts:IContactRepository){} private async activeOrg(id:string){const o=await this.orgs.getById(id,{includeArchived:true}); if(!o)throw new NotFoundError('Organisation not found'); if(o.archivedAt)throw new ConflictError('Archived organisations cannot receive new contacts'); return o} async create(i:ContactCreate){await this.activeOrg(i.organisationId); if(i.isPrimary && i.status!=='active')throw new ConflictError('An inactive contact cannot be primary'); return i.isPrimary?this.contacts.createPrimary(i):this.contacts.create(i)} async get(id:string){const c=await this.contacts.getById(id); if(!c)throw new NotFoundError('Contact not found'); return c} async list(o:ContactListOptions){await this.activeOrg(o.organisationId).catch(e=>{ if(e instanceof ConflictError) return; throw e;}); return this.contacts.list(o)} async update(id:string,p:ContactUpdate){const c=await this.contacts.getById(id,{includeArchived:true}); if(!c)throw new NotFoundError('Contact not found'); if(c.archivedAt)throw new ConflictError('Archived contacts cannot be edited'); const patch={...p}; if(p.status==='inactive') patch.isPrimary=false; const merged={...c,...patch}; if(!merged.firstName&&!merged.lastName&&!merged.email)throw new ValidationError('At least one of firstName, lastName or email is required'); if(merged.isPrimary&&merged.status!=='active')throw new ConflictError('An inactive contact cannot be primary'); return patch.isPrimary?this.contacts.updatePrimary(id,patch):this.contacts.update(id,patch)} async archive(id:string){const c=await this.contacts.archive(id,new Date().toISOString()); if(!c)throw new NotFoundError('Contact not found'); return c} }

export class EngagementService { constructor(private orgs:IOrganisationRepository, private contacts:IContactRepository, private engagements:IEngagementRepository){} private async activeOrg(id:string){const o=await this.orgs.getById(id,{includeArchived:true}); if(!o)throw new NotFoundError('Organisation not found'); if(o.archivedAt)throw new ConflictError('Archived organisations cannot receive new engagements'); return o} private async validatePrimary(orgId:string, cid:string|null|undefined){ if(cid==null)return; const c=await this.contacts.getById(cid,{includeArchived:true}); if(!c)throw new NotFoundError('Primary contact not found'); if(c.organisationId!==orgId)throw new ConflictError('Primary contact must belong to the engagement organisation'); if(c.archivedAt||c.status!=='active')throw new ConflictError('Primary contact must be active and non-archived'); } async create(i:EngagementCreate){await this.activeOrg(i.organisationId); await this.validatePrimary(i.organisationId,i.primaryContactId); return this.engagements.create(i)} async get(id:string){const e=await this.engagements.getById(id); if(!e)throw new NotFoundError('Engagement not found'); return e} async list(o:EngagementListOptions){await this.activeOrg(o.organisationId).catch(e=>{ if(e instanceof ConflictError)return; throw e;}); return this.engagements.list(o)} async update(id:string,p:EngagementUpdate){const e=await this.engagements.getById(id,{includeArchived:true}); if(!e)throw new NotFoundError('Engagement not found'); if(e.archivedAt)throw new ConflictError('Archived engagements cannot be edited'); const merged={...e,...p}; if(merged.endDate!==null&&merged.endDate<merged.startDate)throw new ValidationError('End date cannot precede start date'); await this.validatePrimary(e.organisationId,p.primaryContactId); const u=await this.engagements.update(id,p); return u!} async archive(id:string){const e=await this.engagements.archive(id,new Date().toISOString()); if(!e)throw new NotFoundError('Engagement not found'); return e} }
